const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const executablePath=process.env.CHROMIUM_PATH||undefined;
const base=process.env.BASE_URL||'http://127.0.0.1:8765';let sequence=10000,checks=0,rereolls=0,restarts=0;const errors=[];
(async()=>{
 const b=await chromium.launch({executablePath});const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
 const click=(k,v)=>p.locator(`[data-action="${k}"]${v===undefined?'':`[data-value="${v}"]`}:visible`).first().click();
 const read=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('gokurious-shape-safari-v1')));
 async function start(id,mode='doodle',round=0){await p.evaluate(({id,mode,round})=>localStorage.setItem('gokurious-shape-safari-v1',JSON.stringify({version:1,xp:70,mode,world:0,games:{[id]:{round,seed:824,assisted:1}}})),{id,mode,round});await p.goto(base+'/?learningQA='+(++sequence)+'#'+id);await p.locator('#stage svg').waitFor();}
 async function current(){return p.evaluate(()=>{const id=location.hash.slice(1),s=JSON.parse(localStorage.getItem('gokurious-shape-safari-v1')).games[id];const g=SAFARI.games.create(id,s.round,s.currentSeed,{stage(){},render(){},tell(){},complete(){},animate(){}},{mode:s.currentMode});return {q:g.q,s:g.s}})}
 async function fit(label,dialog=false){const d=await p.evaluate(dialog=>{const el=document.querySelector(dialog?'#modal':'.game-box'),r=el.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:innerWidth,h:innerHeight,scroll:el.scrollWidth,client:el.clientWidth,body:document.documentElement.scrollHeight}},dialog);assert.ok(d.x>=0&&d.y>=0&&d.right<=d.w+.5&&d.bottom<=d.h+.5,label+' outside view');assert.ok(d.scroll<=d.client+1,label+' horizontal content overflow');if(!dialog)assert.ok(d.body<=d.h+1,label+' body scroll');checks++;}
 async function points(a,b){return p.evaluate(([a,b])=>{const s=document.querySelector('#stage svg'),offset=+(s.dataset.offsetY||0);return [a,b].map(pt=>{const v=new DOMPoint(pt[0],pt[1]+offset).matrixTransform(s.getScreenCTM());return {x:v.x,y:v.y}})},[a,b])}
 const ids=await p.evaluate(()=>SAFARI.topics.map(t=>t.id));
 if(!process.env.FOCUS_TOUCH){
 // Every concept opens a continuous article with the reference typography and all existing content.
 for(const id of ids){await start(id,'arcade',7);const before=await read();await click('learn');await p.locator('.article-section').first().waitFor();assert.equal(await p.locator('.gk-article').getAttribute('data-topic'),id);assert.equal(await p.locator('.article-section').count(),3);assert.equal(await p.locator('[role=tablist]').count(),0);await fit(id+' article',true);if(id==='tester')await p.screenshot({path:__dirname+'/article-preview-v3.png'});
  const styles=await p.evaluate(()=>{const a=getComputedStyle(document.querySelector('.gk-prose p')),g=getComputedStyle(document.querySelector('.play-heading h1'));return {font:a.fontFamily,size:a.fontSize,line:a.lineHeight,color:a.color,gameFont:g.fontFamily}});assert.ok(styles.font.startsWith('system-ui'));assert.equal(styles.size,'17px');assert.equal(styles.line,'28.05px');assert.equal(styles.color,'rgb(30, 41, 59)');assert.ok(styles.gameFont.includes('Nunito'));
  const qs=await p.evaluate(id=>SAFARI.lessons[id].checks,id);for(let i=0;i<2;i++){await click('lesson-answer',`${i}:${(qs[i].answer+1)%qs[i].options.length}`);assert.ok(await p.locator('.gk-feedback.incorrect').count());await click('lesson-answer',`${i}:${qs[i].answer}`);assert.ok(await p.locator('.gk-feedback.correct').count());if(i===0)await click('lesson-next');}assert.ok((await p.locator('.gk-score').textContent()).includes('2 of 2 correct'));
  await p.locator('.gk-answers summary').click();assert.equal(await p.locator('.gk-answers[open] li').count(),2);
  assert.equal(await p.locator('.gk-faqs details').count(),3);for(let i=0;i<3;i++){await p.locator('.gk-faqs summary').nth(i).click();assert.equal(await p.locator('.gk-faqs details[open]').count(),i+1);}
  assert.equal(await p.locator('.gk-adults li').count(),2);await fit(id+' full reading',true);await p.locator('#close-modal').click();assert.deepEqual(await read(),before,'reading changed game progress');
 }
 // Restart all games in both preferences; remove only this game's earned XP and history.
 for(const mode of ['arcade','doodle'])for(const id of ids){const other=id==='loops'?'shifter':'loops',otherRecord={round:3,seed:817,assisted:1,error:0,estimated:0};await p.evaluate(({id,mode,other,otherRecord})=>localStorage.setItem('gokurious-shape-safari-v1',JSON.stringify({version:1,xp:178,mode,world:0,games:{[id]:{round:16,seed:212,assisted:2,error:34,estimated:5},[other]:otherRecord}})),{id,mode,other,otherRecord});await p.goto(base+'/?restartQA='+(++sequence)+'#'+id);await p.locator('#stage svg').waitFor();await click('restart');const s=await read();assert.equal(s.games[id].round,0);assert.equal(s.games[id].assisted,0);assert.equal(s.games[id].error,0);assert.equal(s.games[id].estimated,0);assert.equal(s.games[id].serial,1);assert.equal(s.xp,26);assert.deepEqual(s.games[other],otherRecord);assert.equal(s.mode,mode);assert.ok((await p.locator('.mission-stats').textContent()).includes('1/24'));assert.ok((await p.locator('.mission-stats').textContent()).includes('☆☆☆'));await p.reload();assert.equal((await read()).games[id].round,0);restarts++;}
 // Restart remains safe while animation is running: a cancelled old round must not score.
 await p.emulateMedia({reducedMotion:'no-preference'});await start('towers','arcade',8);while(await p.locator('[data-action=brace]').count())await p.locator('[data-action=brace]').first().click();await click('wind');await click('restart');await p.waitForTimeout(1100);assert.equal((await read()).games.towers.round,0);await p.emulateMedia({reducedMotion:'reduce'});
 // Finish, restart from the summary, then earn points again from Round 1.
 await start('degrees','arcade',23);let degree=await current();await p.locator('[data-range=main]').fill(String(degree.q.target));await p.locator('[data-range=main]').dispatchEvent('input');await click('check');await click('next');await p.locator('.done-screen').waitFor();await click('restart');degree=await current();await p.locator('[data-range=main]').fill(String(degree.q.target));await p.locator('[data-range=main]').dispatchEvent('input');await click('check');assert.equal((await read()).games.degrees.round,1);assert.equal((await read()).xp,10);
 // Both preferences generate fresh tasks on demand and preserve earned rounds / XP.
 for(const mode of ['arcade','doodle'])for(const id of ids){await start(id,mode,8);let old=await read();for(let i=0;i<6;i++){await click('remix');const next=await read(),a=old.games[id],n=next.games[id];assert.notEqual(n.currentSeed,a.currentSeed);assert.notEqual(n.lastProblem,a.lastProblem);assert.ok(!a.recent.some(q=>q.visual===n.recent.at(-1).visual));assert.equal(n.round,8);assert.equal(next.xp,70);old=next;rereolls++;}}
 // Drawing mode is available only on concepts with genuine drawing mechanics.
 await start('towers','arcade',8);await click('mode','doodle');await p.getByRole('heading',{name:'Draw the Brace',exact:true}).waitFor();assert.equal(await p.locator('[data-action=brace]').count(),0);await click('mode','arcade');await p.getByRole('heading',{name:'Bridge Builders',exact:true}).waitFor();
 await start('sticks','doodle');assert.equal(await p.locator('[data-action=mode]').count(),0);assert.ok(await p.locator('.mode-note').isVisible());assert.equal(await p.locator('body.doodle').count(),0);
 }
 // Actual touch drags, including strokes beginning directly on SVG anchors.
 for(const [id,size] of [['loops',[320,568]],['towers',[390,844]],['clock',[820,1180]]]){
  await p.setViewportSize({width:size[0],height:size[1]});await start(id,'doodle',8);const {q}=await current();const lines=id==='loops'?Array.from({length:q.n},(_,i)=>[q.points[i],q.points[q.closed?(i+1)%q.n:i+1]]):q.targets.map(t=>[t.a,t.b]);
  const cdp=await p.context().newCDPSession(p);
  for(const [a,b] of lines){const [x,y]=await points(a,b);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[x]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x.x+(y.x-x.x)*i/12,y:x.y+(y.y-x.y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  await fit(id+' touch sketch');await p.screenshot({path:__dirname+`/${id}-doodle-v2.png`});await click('check');if(id==='clock')await click('clock-family',q.angle===90?'Right':q.angle===180?'Straight':q.angle<90?'Acute':'Obtuse');await p.locator('.feedback.success').waitFor();await fit(id+' touch completed');await cdp.detach();
 }
 // Reader, FAQ and sketch layouts across phone, tablet and landscape orientations.
 for(const [w,h] of [[320,568],[390,844],[768,1024],[820,1180],[1024,768],[844,390]]){
  await p.setViewportSize({width:w,height:h});for(const id of ids.filter(id=>['loops','tester','painter','fold','yoga','garden','towers','clock','degrees','doodle'].includes(id))){await start(id);await fit(`${id} ${w}x${h}`);}
  await click('learn');await fit(`article ${w}x${h}`,true);await p.locator('.gk-faqs summary').first().click();await fit(`FAQs ${w}x${h}`,true);await p.locator('#close-modal').click();
 }
 // Keyboard alternative works without a freehand pointer.
 await p.setViewportSize({width:390,height:844});await start('fold');const {q}=await current();await click('input-mode');const anchorValues=await p.evaluate(q=>{const r=JSON.parse(localStorage.getItem('gokurious-shape-safari-v1')).games.fold,g=SAFARI.games.create('fold',r.round,r.currentSeed,{stage(){},render(){},tell(){},complete(){}},{mode:'doodle'});return [q.targets[0].a,q.targets[0].b].map(p=>g.anchors.findIndex(a=>Math.hypot(a[0]-p[0],a[1]-p[1])<.01))},q);for(const v of anchorValues){await p.locator(`[data-action=anchor][data-value="${v}"]`).focus();await p.keyboard.press('Enter');}await click('check');await p.locator('.feedback.success').waitFor();
 await start('towers');await p.screenshot({path:__dirname+'/restart-phone-v3.png'});await click('learn');await p.screenshot({path:__dirname+'/article-phone-v3.png'});await click('lesson-answer','0:0');await p.screenshot({path:__dirname+'/practice-phone-v3.png'});await p.locator('.gk-faqs summary').first().click();await p.screenshot({path:__dirname+'/faqs-phone-v3.png'});await p.locator('#close-modal').click();
 await p.setViewportSize({width:820,height:1180});await click('learn');await p.screenshot({path:__dirname+'/article-tablet-v3.png'});for(const s of await p.locator('.gk-faqs summary').all())await s.click();await p.screenshot({path:__dirname+'/faqs-tablet-v3.png'});
 assert.deepEqual(errors,[]);const result={result:'PASS',lessonTopics:16,interactiveChecks:32,faqDisclosures:48,randomPuzzleRefreshes:rereolls,restarts,articleTypography:'PASS',restartDuringAnimation:'PASS',restartAfterSummary:'PASS',layoutChecks:checks,touchDrawingFlows:3,keyboardDrawing:'PASS',errors};fs.writeFileSync(__dirname+'/learning-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
