const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined});
 const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});
 const errors=[],remote=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});
 await p.context().setOffline(true);
 await p.goto(pathToFileURL(path.join(__dirname,'../shape-safari.html')).href);
 await p.getByRole('button',{name:'Play Loop Lagoon: Open & closed shapes'}).click();
 const getMid=async n=>{const r=await p.locator(`[data-action=peg][data-value="${n}"]`).boundingBox();return [r.x+r.width/2,r.y+r.height/2]};
 await p.touchscreen.tap(...await getMid(0));await p.touchscreen.tap(...await getMid(1));
 assert.ok((await p.locator('.scene-caption').textContent()).includes('1 /'));
 await p.locator('#guide').click();await p.locator('[data-action=modal-play][data-value=doodle]').click();
 await p.locator('[data-action=reveal]').click();await p.locator('[data-action=pen]').click();
 const r=await p.locator('#stage').boundingBox();
 await p.mouse.move(r.x+40,r.y+30);await p.mouse.down();await p.mouse.move(r.x+100,r.y+60,{steps:8});await p.mouse.up();
 const stroke=p.locator('#stage polyline');assert.ok(await stroke.count()>0);
 const sb=await stroke.first().boundingBox();assert.ok(sb.y<r.y+70,'Doodle ink not visible in upper notebook');
 await p.locator('[data-action=bank]').click();await p.locator('.feedback.success').waitFor();await p.locator('[data-action=next]').click();
 await p.locator('#guide').click();await p.locator('[data-action=modal-play][data-value=fold]').click();await p.locator('[data-action=mode][data-value=doodle]').click();
 const target=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('gokurious-shape-safari-v1')).games.fold,g=SAFARI.games.create('fold',s.round,s.currentSeed,{stage(){},render(){},tell(){},complete(){}},{mode:'doodle'}),svg=document.querySelector('#stage svg'),offset=+(svg.dataset.offsetY||0);return [g.q.targets[0].a,g.q.targets[0].b].map(pt=>{const v=new DOMPoint(pt[0],pt[1]+offset).matrixTransform(svg.getScreenCTM());return [v.x,v.y]})});
 await p.mouse.move(...target[0]);await p.mouse.down();await p.mouse.move(...target[1],{steps:10});await p.mouse.up();await p.locator('[data-action=check]').click();await p.locator('.feedback.success').waitFor();
 await p.locator('[data-action=learn]:visible').click();assert.equal(await p.locator('.article-section').count(),3);await p.locator('.gk-faqs summary').first().click();assert.equal(await p.locator('.gk-faqs details[open]').count(),1);await p.locator('#close-modal').click();await p.locator('[data-action=restart]').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('gokurious-shape-safari-v1')).games.fold.round),0);
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
 await p.screenshot({path:path.join(__dirname,'standalone-offline.png')});
 const result={offlineStandalone:'PASS',remoteRequests:0,touchTaps:'PASS',upperNotebookDrawing:'PASS',guidedDoodleDrawing:'PASS',articlesAndFAQs:'PASS',restart:'PASS',errors};
 fs.writeFileSync(path.join(__dirname,'offline-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
