const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('assert'),fs=require('fs');
const {solve}=require('./qa.cjs');
const base=process.env.BASE_URL||'http://127.0.0.1:8768/';
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await b.newPage({viewport:{width:390,height:844}}),errors=[],layout=[],assets=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)assets.push([r.status(),r.url()])});await p.goto(base+'chapters/class-4-science/#ch1');await p.evaluate(()=>document.fonts.ready);const topics=await p.evaluate(()=>SAFARI.topics.map(t=>({id:t.id,name:t.name})));
await p.evaluate(()=>{const create=SAFARI.games.create;SAFARI.games.create=function(...a){const g=create(...a);window.qaGame=g;return g}});
for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:1024,height:768},{width:844,height:390}]){await p.setViewportSize(viewport);for(const {id,name}of topics){await p.evaluate(id=>location.hash=id,id);await p.locator('.play-heading h1').filter({hasText:name}).waitFor();const result=await p.evaluate(()=>{const bad=[...document.querySelectorAll('.play button,.play input,.stage,.feedback')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').flatMap(e=>{const r=e.getBoundingClientRect();return r.x<-.5||r.y<-.5||r.right>innerWidth+.5||r.bottom>innerHeight+.5?[{text:(e.textContent||'').slice(0,55),box:[r.x,r.y,r.width,r.height]}]:[]});return {bad,overflow:document.documentElement.scrollWidth>innerWidth,stageHeight:document.querySelector('.stage').getBoundingClientRect().height}});if(result.bad.length||result.overflow||result.stageHeight<70)layout.push({id,viewport,...result})}}
await p.setViewportSize({width:390,height:844});
// Real pointer drawing on a route: wrong stroke rejected, connected strokes accepted.
await p.evaluate(()=>location.hash='map-pen');await p.locator('.play-heading h1').filter({hasText:'Landmark Pencil'}).waitFor();let paths=await p.evaluate(()=>{const m=document.querySelector('#stage svg').getScreenCTM();return qaGame.q.paths.map(path=>path.map(([x,y])=>{const p=new DOMPoint(x,y).matrixTransform(m);return[p.x,p.y]}))});await p.mouse.move(...paths[0][0]);await p.mouse.down();await p.mouse.move(paths[0][0][0]+3,paths[0][0][1]+90,{steps:10});await p.mouse.up();assert.equal(await p.evaluate(()=>qaGame.s.paths.length),0);
for(const path of paths){await p.mouse.move(...path[0]);await p.mouse.down();for(const point of path.slice(1))await p.mouse.move(...point,{steps:20});await p.mouse.up()}await p.locator('[data-action="check"]').click();assert(await p.evaluate(()=>qaGame.done));const saveKey='gokurious-wondrous-world-4-v1';const saved=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)),saveKey);assert.equal(saved.games['map-pen'].round,1);await p.locator('[data-action="restart"]').click();assert.equal(await p.evaluate(()=>qaGame.round),0);
// Complete every game using its public interactions, then inspect the completed render.
await p.evaluate('window.solveGame = '+solve.toString());for(const {id,name}of topics){await p.evaluate(id=>location.hash=id,id);await p.locator('.play-heading h1').filter({hasText:name}).waitFor();await p.evaluate(()=>{if(qaGame.id==='spinner'){qaGame.api={...qaGame.api,animate(t,f,end){f(1);end()}}}solveGame(qaGame)});assert(await p.evaluate(()=>qaGame.done),id+' complete');const bad=await p.evaluate(()=>{const r=document.querySelector('.feedback').getBoundingClientRect();return r.bottom>innerHeight+1||r.left<0});if(bad)layout.push({id,successOverflow:true});}
// Reset isolation after completing all games.
const before=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)),saveKey);await p.locator('[data-action="restart"]').click();const after=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)),saveKey);assert.equal(after.games['star-pen'].round,0);assert.equal(after.games.helpers.round,before.games.helpers.round);assert.equal(after.xp,before.xp-before.games['star-pen'].round*10);
// Closed paths and pigment selection through actual buttons.
await p.evaluate(()=>location.hash='dye-pen');await p.locator('.play-heading h1').filter({hasText:'Nature-Colour Studio'}).waitFor();const pigment=await p.evaluate(()=>qaGame.q.source);await p.locator('[data-action="pigment"]').filter({hasText:pigment}).click();await p.locator('[data-action="input"]').click();for(const length of await p.evaluate(()=>qaGame.q.paths.map(p=>p.length)))for(let i=0;i<length;i++)await p.locator('svg [data-action="point"][data-value="'+i+'"]').click();await p.locator('[data-action="check"]').click();assert(await p.evaluate(()=>qaGame.done));
for(const {id,name}of topics){await p.evaluate(id=>location.hash=id,id);await p.locator('.play-heading h1').filter({hasText:name}).waitFor();const seed=await p.evaluate(()=>qaGame.seed);await p.locator('[data-action="learn"]').first().click();assert.equal(await p.locator('article').getAttribute('data-topic'),id);assert.equal(await p.locator('.gk-faqs details').count(),3);await p.locator('.gk-options button').first().click();assert.equal(await p.locator('.gk-feedback').count(),1);await p.locator('#close-modal').click();assert.equal(await p.evaluate(()=>qaGame.seed),seed)}
await p.evaluate(()=>location.hash='ch7');await p.locator('.home').waitFor();await p.screenshot({path:'/tmp/science-home-phone.png'});await p.evaluate(()=>location.hash='boats');await p.locator('.play-heading h1').filter({hasText:'Boat-Builders Bay'}).waitFor();await p.screenshot({path:'/tmp/science-game-phone.png'});await p.setViewportSize({width:768,height:1024});await p.evaluate(()=>location.hash='web');await p.locator('.play-heading h1').filter({hasText:'Web-of-Life Weavers'}).waitFor();await p.screenshot({path:'/tmp/science-tablet.png'});
await p.goto(base);assert.equal(await p.locator('.class4-card').count(),10);await p.locator('.class4-card').nth(9).click();await p.locator('.world-title h2').filter({hasText:'Our Sky'}).waitFor();const result={games:40,viewports:5,articles:40,layout,errors,assets,drawing:'passed',restart:'passed',chapters:10};fs.writeFileSync('/tmp/science-browser-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await b.close();if(layout.length||errors.length||assets.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
