'use strict';
(() => {
const S=SAFARI;
const content={
spinner:{name:'Spin & Balance Carnival',concept:'Balance, rotation, speed and stability',learn:'A model’s behaviour depends on where its weight is placed, where it is supported, its shape and how it is set in motion. Test the effect of each change.',example:'A lighter crate can balance a heavier one farther from the pivot. A low heavy base can make a tower more stable.',sections:[['Weight and support','A balance point, also called the centre of mass, describes where the distributed mass of an object balances. For a uniform symmetrical plate it is at the centre; an uneven shape or added cargo can shift it. At this age, use the visible balance marker and tests rather than formulas.'],['Rotation and speed','A push starts rotation. A stronger push can produce a higher starting speed in this model. Too little or too much may miss a particular game target; faster is not always better. Colours arriving rapidly can appear blended even though the coloured regions have not changed.'],['Stability and distribution','Support and weight distribution work together. Lowering a tower’s heavy parts lowers its balance point. Placing equal weights on opposite sides can balance a rotor. In the coasting level both wheels start at the same angular speed with the same model resistance; moving the balanced weights outward makes rotation harder to slow. This is a qualitative extension of NCERT’s spinner exploration, not a required Class 4 calculation.'],['Different shapes, different motion','A round wheel keeps its axle height relatively steady while rolling on a smooth surface. A square or triangle rolls with changing axle height. The game exaggerates the resulting bounce to make a fragile-delivery problem visible. Real toys also depend on friction, push, shape, construction and surface.']]},
shadows:{name:'Shadow Theatre Adventure',concept:'Light, distance, size and changing shadows',learn:'An opaque object blocks light. Shadow size and position depend on the positions of the source, object and screen. Each level lets you control a different part of that arrangement.',example:'With the screen fixed, bringing the object closer to a small light source makes a larger shadow. Bringing the screen closer to the object can shrink it.',sections:[['A straight-light model','This theatre uses a small point-like source, a flat opaque object and a screen. Lines from the source past the object’s edges show the shadow boundary. Light continues in straight paths in this simplified arrangement.'],['Which distance changed?','Moving the light towards the object enlarges the shadow on a fixed screen. Moving the object towards the screen shrinks it when the source stays fixed. Moving the screen changes the size too. Keep track of what you moved: “nearer” alone does not identify a meaningful distance.'],['Direction and position','Moving a light upward makes the object’s shadow move downward on the screen in this arrangement. Moving the object upward moves its shadow upward. These are different causes. With two sources, each source can produce a separate shadow region; another light may still partly illuminate a shadow region.'],['A changing day','The Sun’s apparent position changes through the day, so shadow direction and length change. The sundial level uses an idealised path with a very short noon shadow. The Sun is not overhead at noon everywhere, and real shadows depend on place, date and object. Never look directly at the Sun.'],['Making a show','A cut-out’s shape affects the outline of its shadow. Distance can enlarge that outline. Turning off the source prevents its visible shadow during a scene change. In the finale, source distance, object position and screen position perform three different stage effects.']]},
paper:{name:'Paper Rescue Factory',concept:'Waste paper, pulp, sheets and resource conservation',learn:'Suitable used paper can be softened, broken into pulp, formed into a sheet, pressed and dried. Each step changes the material or removes water. Reuse can avoid the need to make a new sheet at all.',example:'A blank-backed sheet may be useful immediately. Torn scraps may need pulping, water removal and drying before they form a usable sheet.',sections:[['Choose and prepare the material','The first levels separate clean used paper from plastic, foil and leaves, then tear it into manageable pieces. Tearing changes piece size. Soaking softens the scraps before mashing loosens them into a wet mixture of fibres. The sorting rules describe this classroom paper-making batch, not every municipal recycling service.'],['Pulp into a sheet','An even layer of pulp helps make a continuous sheet. In the sheet-shaping puzzle, twelve existing scoops must be redistributed; repeatedly adding new pulp cannot solve the problem. Thick and thin patches call for a different action.'],['Pressing and drying are different','Pressing removes excess water mechanically; drying removes remaining moisture over time. The roller level requires suitable pressure and coverage. The drying level considers spacing, moving air and protection from rain. Model time is accelerated, and the numbers are game units, not a real manufacturing recipe.'],['Using fewer resources','Recycling still takes water, energy and work. Reusing clear areas of a sheet can avoid those processes. The cutting level makes three useful items from existing material; the final order must use ready-to-reuse sheets as well as the one available recycling batch.'],['Five Rs and repair','NCERT uses Refuse, Reduce, Reuse, Repurpose and Recycle. Repair is an additional useful action requested in this package. Using the other side is reuse; changing a sheet into a new object can be repurposing; breaking paper into fibres to make a new sheet is recycling. Machine-made paper performs related transformations at a different scale.']]}
};
for(const [id,c]of Object.entries(content)){
const t=S.topics.find(t=>t.id===id),l=S.lessons[id],levels=S.campaigns[id];Object.assign(t,{name:c.name,concept:c.concept,learn:c.learn,why:c.learn,example:c.example,campaign:true,total:levels.length,edition:3,doodle:false,tag:'HANDS-ON CAMPAIGN',steps:levels.map(d=>d.name)});
Object.assign(l,{objective:c.learn,predict:'Try a change, predict its visible effect, then use the result to improve the design. The campaign changes its task and controls between levels.',explore:levels.map((d,i)=>`${i+1}. ${d.name}: ${d.goal}`),article:c.sections,reflect:'Describe one failed attempt and the change that improved it. Which observation supports your explanation?',faqs:[{q:'Does every level repeat the same activity?',a:'No. These ten levels have separately authored objectives, scenes and interactions. Progression ends after level ten. The level chooser lets you deliberately replay an unlocked level; it does not call a reskinned copy a new level.'},{q:'Can I use a finger or keyboard?',a:'Drag and draw where shown. Sliders, buttons and keyboard-focusable objects provide alternatives. Read and Hint remain available without resetting the current level.'},{q:'What does Restart reset?',a:'Restart begins this campaign at level one and resets only its campaign progress and XP. Old-edition records are preserved separately. Replaying a completed level does not award progress or XP again.'}]});
}
S.lessons.spinner.worked={q:'A 2-unit crate sits 60 units left of a pivot. Where could a 1-unit crate balance it?',steps:['Keep the heavy crate fixed and move the lighter crate on the right.','Watch the bridge tilt. In this idealised level, the lighter crate balances it at about twice the distance.','Explain the result as weight and position working together; no formula is needed to play.']};
S.lessons.shadows.worked={q:'A shadow fits the height of a window but is too low. What could you change without resizing it?',steps:['Keep source-to-object and object-to-screen distances unchanged.','Move the object upward, or aim by moving the lamp downward in this theatre arrangement.','Compare the shadow with the outline. In a real setup, moving several things at once can make the cause harder to identify.']};
S.lessons.paper.worked={q:'Six usable blank-backed sheets and two recyclable scrap units are available for an eight-sheet order.',steps:['Use the six ready sheets; they do not need to become pulp again.','Process the two scrap units in the one model recycling batch that the water budget permits.','Deliver eight sheets without claiming recycling uses no resources.']};
const scienceFAQs={
spinner:[{q:'Does the heaviest part always belong at the centre?',a:'It depends on the design. A tower can become more stable when its heavy parts are lower. On a rotor, the complete weight distribution must balance around the stem. A lighter mass farther from a beam pivot can balance a heavier one nearer it.'},{q:'Does a harder push always make a top better?',a:'A harder push can increase its starting speed, but a game may need a particular speed. Real spinning also depends on the stem, weight distribution, shape, friction and surface. Change one feature and observe the effect.'}],
shadows:[{q:'Why does moving a light change shadow size?',a:'For this small-source model with a fixed object and screen, moving the source towards the object spreads the blocked-light region more widely at the screen. Moving the object towards the screen instead makes the shadow smaller.'},{q:'Why do shadows move during the day?',a:'As Earth rotates, the Sun appears in different directions in the sky. Shadows point away from the sunlight and change length with the Sun’s height. The exact pattern depends on place and date; noon shadows are not always zero.'}],
paper:[{q:'Are tearing and pulping the same thing?',a:'No. Tearing makes smaller pieces of paper. Soaking softens them, and mashing makes a wet mixture of fibres that can be spread into a new sheet. Pressing and drying remove water at later stages.'},{q:'Why reuse paper if it can be recycled?',a:'Recycling still needs water, energy and work. A usable blank side can serve another purpose immediately. Reuse useful paper first, then recycle suitable scraps when possible.'}]
};
for(const [id,faqs]of Object.entries(scienceFAQs))S.lessons[id].faqs=[...faqs,S.lessons[id].faqs[2]];

})();
