'use strict';
window.SAFARI={};
SAFARI.util={rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=Math.imul(x^x>>>15,1|x);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296}},pick(r,a){return a[Math.floor(r()*a.length)]},shuffle(r,a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},pt(x,y,a,l){return[x+Math.cos(a*Math.PI/180)*l,y-Math.sin(a*Math.PI/180)*l]},distance(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1])},escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},fmtTime(t){return `${Math.floor(t/60)%12||12}:${String(t%60).padStart(2,'0')}`}};
const chapterRows=[
['Living Together','A','3–16','Everyone has a part. Build a caring community.','helping hands.'],
['Exploring Our Neighbourhood','A','17–32','Travel, communicate and find your way.','neighbourhood trails.'],
['Nature Trail','A','35–56','Look closely. Discover the connections.','a world of nature.'],
['Growing Up with Nature','A','57–68','Create, celebrate and care for nature.','nature & village life.'],
['Food for Health','A','71–84','Explore tastes, food groups and cooking.','colourful food plates.'],
['Happy and Healthy Living','A','85–101','Move, rest, share and look after yourself.','healthy little habits.'],
['How Things Work','A','104–116','Predict. Change one thing. Observe.','spins & splashes.'],
['How Things Are Made','B','117–127','Turn used paper into a new discovery.','making & remaking.'],
['Different Lands, Different Lives','A','130–151','Explore landscapes and respect every story.','many lands & lives.'],
['Our Sky','A','152–163','Follow the light. Watch the changing sky.','Sun, Moon & stars.']
];
SAFARI.worlds=chapterRows.map((r,i)=>({name:r[0],priority:r[1],pages:r[2],subtitle:r[3],hero:r[4],color:['#d8edc9','#ffe3ba','#dfe4fb','#dcebcf'][i%4],source:`https://ncert.nic.in/textbook/pdf/deev1${String(i+1).padStart(2,'0')}.pdf`}));
// id, name, concept, action, explanation, example, misconception, question, options, correct index.
const rows=[
['helpers','Helping-Hands Town','Public places & community helpers','MATCH & HELP','Schools, markets, health centres and parks provide different shared services. Many people contribute to each service, and all useful work deserves respect.','A school relies on teachers, cleaners, bus drivers, families and children working together.','A job is not restricted to a particular gender. Match the task and skill, not a person’s appearance.','Who can help repair a faulty public light?',['A trained electrician','A child with a metal stick','A fruit seller doing electrical work'],0],
['team','Festival Team','Cooperation & interdependence','PLAN & SHARE','A community project succeeds when tasks, tools and responsibilities are shared. Listening, including everyone and following up matter as much as finishing the event.','For Van Mahotsav, one group prepares the site, another plants, and another takes responsibility for watering afterwards.','Planting day is only the beginning. Saplings need continued care.','Which plan supports a tree after the festival?',['Leave it alone','Arrange regular care','Cover the leaves with paint'],1],
['park','Park Keepers','Care of public spaces','CARE & RESTORE','Public spaces belong to the community. We can keep paths clear, sort ordinary litter, protect plants and report damaged equipment to adults.','A fallen dry leaf can go into suitable compost; a broken swing should be reported and left unused.','Children should not handle sharp litter or repair electrical equipment. Reporting is an important contribution.','What should you do about broken glass in a park?',['Pick it up with bare hands','Kick it aside','Tell a responsible adult and keep clear'],2],
['tree-pen','Sapling Sketcher','Planting & protecting a sapling','DRAW & CARE','A young tree has roots below the soil and a shoot above it. A planting plan leaves room for growth and keeps paths open.','A shallow watering basin around the root area helps direct water towards the soil, without burying the stem deeply.','A guard should leave growing space; it must not squeeze the trunk.','Which part mainly takes up water from soil?',['Roots','Flowers','Fruit'],0],
['journey','Neighbourhood Navigator','Transport, landmarks & directions','PLAN & TRAVEL','A map shows relationships between places. North, south, east and west describe directions when the map orientation is given. Travel choices depend on the route, distance and available transport.','A river crossing without a bridge needs suitable water transport; a short safe local journey may be walked.','The shortest-looking line is not always an available route. Follow roads and marked crossings.','On a north-up map, east is…',['Left','Right','Down'],1],
['messages','Message Museum','Communication then & now','SEND & CONNECT','Letters, telephones, radio and internet messages carry information in different ways. Older and newer methods can coexist. Choose a method suited to the need and check information before sharing.','A parcel goes through a delivery service; a video call lets distant family members see and hear one another.','An instant message is not automatically true. Ask a trusted adult to help check unfamiliar claims.','Which can carry a physical parcel?',['A video call','A radio broadcast','A postal service'],2],
['savings','Pocket-Money Planner','Needs, spending & savings','BUDGET & SAVE','A simple budget divides a limited amount between planned spending and saving. Banks provide services such as keeping money in accounts and making payments. An ATM withdraws money from an account.','With ₹100, spending ₹35 on stationery leaves ₹65 that can be saved or planned for other needs.','An ATM does not create free money. This game uses pretend money and asks for no personal account information.','Saving means…',['Keeping some money for later','Getting unlimited free money','Spending every coin at once'],0],
['map-pen','Landmark Pencil','Drawing a neighbourhood route','DRAW A ROUTE','A useful map includes recognisable landmarks, connected paths and an indication of direction. It is a simplified view, not a photograph.','A route can go from school past a tree, then turn towards the library at the next junction.','Name the direction or landmark clearly; “over there” is not enough for someone unfamiliar with the route.','What helps a visitor recognise a turning point?',['A landmark','An unlabeled blank page','A random colour only'],0],
['observe','Field-Note Finders','Features & classification','OBSERVE & SORT','Careful observation records features such as leaf veins, bird beaks, legs, wings and seeds. Insects have six legs. Birds and insects are both animals, even when we study them as separate groups.','A butterfly has six legs; a spider has eight, so a spider is not an insect.','Flying alone does not make an animal a bird. Birds have feathers; some insects and mammals can fly too.','Which feature is typical of an adult insect?',['Eight legs','Six legs','Feathers'],1],
['habitat','Habitat Builders','Food, water & shelter','BUILD A HOME','A habitat provides conditions and resources that living things need. Different organisms use different foods and shelters, and a healthy place supports many kinds of life.','A pond fish needs water with suitable conditions; a seed-eating sparrow can use seeds for food and a safe nesting place.','Wild animals are not toys or pets to collect. Observe without disturbing or feeding them on a nature trail.','A habitat should provide…',['Only decoration','Only a cage','Suitable food, water and shelter'],2],
['web','Web-of-Life Weavers','Relationships among living things','CONNECT & DISCOVER','Plants, animals, water, soil and sunlight form many connected relationships. Some links provide food, others shelter or help with plant reproduction.','A tree can shelter a bird. A flower supplies nectar to a bee, which may carry pollen between flowers.','Not every nature connection means “eats”. Read whether a link is about food, shelter or another relationship.','A tree providing a nest site is a link about…',['Shelter','A machine','Transport fuel'],0],
['leaf-pen','Leaf Autographs','Leaf outlines & veins','LOOK & DRAW','Leaves vary in shape and vein pattern. An observational drawing records features that are actually visible rather than assuming every leaf looks the same.','Some leaves have a branching network of veins; others show veins running roughly alongside one another.','A drawing is a model. Real leaves have many smaller details, and leaf colour can change with age.','The lines inside a leaf are called…',['Roots','Veins','Petals'],1],
['village','Village Makers','Natural materials & homes','CHOOSE & BUILD','People use locally available materials such as clay, wood, grass and bamboo in different ways. A house’s design also responds to rain, heat and everyday needs.','A sloping roof helps rainwater run off. Clay can form walls, while dried grass may be used in a thatched roof.','No single kind of house represents every village. Families and places have diverse building methods.','What does a sloping roof help do?',['Hold all rain on top','Send rainwater down the slope','Make rain stop falling'],1],
['solar','Sun-Powered Village','Solar energy & resources','TURN & POWER','Sunlight can be used for warmth and drying. Solar panels can convert sunlight into electricity. Shade changes how much light reaches a panel.','A panel in bright daylight can power a model lamp; shade reduces the light reaching it. Stored energy may support real systems after sunset.','A solar panel does not make electricity from moonlight as effectively as from strong daylight. Night use usually needs storage or another supply.','Solar panels mainly use energy from…',['Sunlight','Plastic waste','The sound of a drum'],0],
['storage','Harvest Helpers','Grain storage & nature care','PREPARE & STORE','Harvest celebrations recognise food, nature and people’s work. Stored grain needs suitable dryness and protection from pests and rain. Traditional storage methods vary by place.','The chapter describes earthen pots, bamboo containers and neem leaves used in traditional grain storage.','Natural does not automatically mean harmless. Herbal preparations are not guaranteed pest protection and should not be tasted or applied without adult guidance.','Why should wet grain not be sealed away carelessly?',['Moisture can encourage spoilage','Water always preserves grain','A wet container stops all pests'],0],
['dye-pen','Nature-Colour Studio','Plant colours & local craft','COLOUR & CREATE','Flowers, leaves, roots and other natural materials can provide colour. Extracted colours vary with material, preparation and the surface being coloured.','Turmeric often gives yellow; beetroot can give pink-red. A small test sample helps compare the results.','Use familiar materials with an adult. Do not assume every wild plant or natural dye is safe.','Which familiar material usually gives a yellow colour?',['Turmeric','A steel spoon','Plain water'],0],
['plate','Rainbow-Plate Garden','Variety, food groups & water','BUILD A MEAL','Foods provide energy, support growth and supply nutrients for normal body functions. A varied meal includes several food groups and safe drinking water. Food groups are teaching guides; many foods contribute more than one nutrient.','Rice or millet, dal or beans, vegetables and fruit can contribute different things to a varied meal.','No one food guarantees protection from illness. This plate game teaches variety, not a personal diet or exact serving size.','Why include different foods?',['One food supplies everything','Variety helps meet different needs','Colour alone guarantees health'],1],
['cooking','Kitchen Discoveries','Cooking methods & traditional foods','MATCH & PREPARE','Boiling uses hot liquid, steaming uses steam, roasting uses dry heat and baking uses an oven. Some foods, such as washed fruit, can be eaten without cooking.','Idli is commonly steamed; rice is commonly boiled; a loaf is baked. Recipes and preparation methods can vary.','Cooking methods depend on the recipe. Hot equipment and flames are for adults to handle.','Which method commonly cooks idli?',['Steaming','Freezing','Drying in a cupboard'],0],
['tastes','Taste-Trail Detectives','Six tastes & everyday choices','EXPLORE & CHOOSE','The chapter introduces sweet, sour, salty, pungent, bitter and astringent tastes through familiar ingredients. Taste can vary with ripeness and preparation. Choose varied meals and water; foods very high in salt, sugar or oil are better limited.','Jaggery is usually sweet, tamarind sour and salt salty. Ugadi Pachadi combines different taste elements.','This is a picture activity: do not taste unknown plants or powders. Enjoying a taste does not alone tell you a food’s nutritional value.','Which ingredient is usually sour?',['Tamarind','Plain salt','Jaggery'],0],
['plate-pen','Food-Collage Pencil','Planning a varied plate','DRAW & PLAN','A food collage groups foods by the roles discussed in the chapter. It can help notice a missing group and start a conversation about a varied meal.','Draw areas for energy-giving, body-building and protective foods, then include water beside the plate.','The equal drawing spaces in this activity are labels, not instructions to eat equal quantities.','Which belongs in a varied-meal plan?',['Only sweets','Several food groups and water','Only the largest food item'],1],
['hygiene','Clean-Hands Crew','Personal hygiene & cleanliness','WASH & SEQUENCE','Clean habits include washing hands with soap and water, caring for teeth, keeping shared areas clean and handling food with clean hands. Handwashing includes rubbing all parts, rinsing and drying.','Before eating, wet hands, use soap, rub palms, backs and between fingers, rinse, then dry.','A splash of water alone does not replace careful washing with soap. This screen demonstration is not a substitute for washing real hands.','What helps remove dirt during handwashing?',['Soap, rubbing and rinsing','Painting the fingers','Only waving hands'],0],
['routine','Day-Balance Builders','Movement, meals, rest & sleep','PLAN YOUR DAY','A caring daily routine makes room for food, water, movement, learning, play and sufficient rest. People’s routines differ, and activities can be adapted to their abilities.','After active play, pause for water and rest. At bedtime, a calm routine helps prepare for sleep.','More activity is not always better. Rest is part of healthy living, and participation should suit each child.','Which is part of a balanced day?',['Skipping all sleep','Moving and resting','Only screen time'],1],
['feelings','Kindness Path','Safety, feelings & belonging','CHOOSE & SUPPORT','Feelings deserve attention. We can listen, include others, ask before touching and speak to a trusted adult when something feels unsafe or upsetting. Children are never to blame for someone else’s harmful behaviour.','If a game leaves a classmate out, invite them and adapt the rules so they can participate.','Knowing a person does not make every touch or request safe. It is okay to refuse unwanted touch and tell a trusted adult.','If someone makes you feel unsafe, you can…',['Keep it secret forever','Blame yourself','Move to safety and tell a trusted adult'],2],
['care-pen','Gratitude Trail','From farm to food & mindful care','JOIN THE JOURNEY','Food reaches us through the work of many people and natural processes. Recognising this effort encourages gratitude, mindful eating and avoiding unnecessary waste.','Seed, growing crop, harvested grain, market and kitchen are connected stages in a food journey.','Take a suitable portion and ask for more if needed. Avoiding waste does not mean forcing yourself to eat when full.','Who contributes to the journey of grain?',['Only the person eating','Farmers, transporters, sellers and cooks','Nobody else'],1],
['spinner','Spinner Workshop','Balance, spinning & fair tests','ADJUST & SPIN','A spinner’s shape, pivot position and construction affect how it moves. Change one feature at a time, keep the push similar and compare what you observe.','Move a model pivot towards the centre, then test again with the same push. Compare wobble and steadiness.','The animation is a simplified comparison model, not a prediction of an exact real-world spinning time.','For a fair comparison, change…',['Everything together','One feature while keeping others similar','Only the name of the toy'],1],
['float','Float-or-Sink Lab','Prediction, material & observation','PREDICT & TEST','Whether an object floats depends on its material, shape and how it sits in the water. Predict first, test carefully and record the result even if it differs from your prediction.','A small stone sinks, while an empty watertight bowl may float. Weight alone is not enough to decide.','Some objects behave differently if water enters or air is trapped. The game states the conditions for each test.','If an observation differs from your guess, you should…',['Hide the result','Record it and rethink','Change the record to match the guess'],1],
['boats','Boat-Builders Bay','Shape, load & floating','RESHAPE & TEST','A hollow watertight shape can move aside more water before its rim is submerged. Changing shape and distributing the load can change how a boat behaves.','The same foil can be pressed into a compact ball or opened into a broad cup-like hull. Compare these shapes with the same load.','Model load units are illustrative. Real results depend on dimensions, material, leaks and how the load is placed.','What can change when the same foil is reshaped?',['Its material must become wood','Its ability to float with a load','Nothing at all'],1],
['boat-pen','Paper-Boat Pencil','Planning a paper-boat model','DRAW & FOLD','A sketch can record a boat’s outline and planned folds before making a model. Compare designs, test them and use observations to improve the next version.','A broad base and balanced load may help a small boat stay upright; a wet or torn paper hull may fail.','A drawing cannot prove that a real boat will float. It is a plan to test.','After drawing a boat plan, the next useful step is…',['Test a safe model with an adult','Assume it will always float','Use it as a real passenger boat'],0],
['paper','Paper-Pulp Factory','Handmade & recycled paper','MAKE IN ORDER','Paper contains plant fibres. Used paper can be torn, soaked, mashed into pulp, spread, pressed and dried into a new sheet. Machines perform related stages on a larger scale.','A soaked newspaper becomes soft pulp; spreading it evenly and removing water helps make a sheet.','Recycling still uses water and energy. Using less and reusing suitable paper also matter.','What is paper pulp?',['A wet mixture of loosened fibres','A metal sheet','Only dry sand'],0],
['paper-test','Paper-Property Lab','Absorbency, strength & uses','TEST & CHOOSE','Paper types differ in thickness, surface and absorbency. A fair test uses the same size samples and the same amount of water or load. Choose a paper suited to its intended use.','Soft tissue absorbs a small spill; thicker cardboard is more suitable for a model box.','One paper is not best for every job. Compare properties for the particular task.','For a fair water test, keep the…',['Water amount and sample size the same','Labels hidden forever','Samples unrelated in size'],0],
['rs','Resource Rescuers','Five Rs, repurpose & repair','SORT & SAVE','NCERT uses Refuse, Reduce, Reuse, Repurpose and Recycle. Repair is another valuable action: fix an item so it can keep serving its purpose. These choices can overlap in real life.','Using a bag again is reuse; turning a bottle into a planter is repurpose; pulping old paper into a new sheet is recycling.','Changing an item’s use is not the same process as breaking it into material for recycling.','Turning a jar into a pencil holder is…',['Repurpose','Always refuse','Always recycle'],0],
['paper-pen','Reuse-Card Studio','Planning a reused-paper craft','DRAW & REUSE','A used sheet can have another useful life as a card or envelope. A plan marks the outline and folds while making thoughtful use of the available paper.','An old sheet with a clear side can become a folded greeting card decorated with a simple design.','Reuse and repurpose can reduce waste before recycling is needed. Avoid unnecessary new material.','Using the blank side of a sheet helps…',['Reduce paper use','Double the rubbish automatically','Make paper waterproof'],0],
['lands','Landscape Explorers','Mountains, plains, deserts & coasts','BUILD & IDENTIFY','Landforms differ in elevation, slope, water and rainfall. Deserts are defined by very little precipitation, not by being hot everywhere. Coasts meet a sea or ocean.','A broad level area suggests a plain; a high steep profile suggests mountains; a shore borders the sea.','A region has variation within it. These models show typical features, not every place in that region.','A coast is land next to…',['The sea or ocean','Only a snowy peak','Any cupboard'],0],
['pack','Weather-Wise Travellers','Climate, clothing & practical choices','PACK FOR THE DAY','Choose clothing and equipment for the stated weather and activity. Climate describes patterns over time, while today’s weather can differ from the usual pattern.','For a cold mountain walk, warm layers help; for a rainy outing, rain protection is useful.','People in a region do not all dress or live alike. Clothing also reflects culture, choice and circumstance.','Which is useful for the stated rainy outing?',['A raincoat','Only a paper hat','No protection because of a region’s name'],0],
['culture','Culture Postcards','Livelihoods, food, art & diversity','CONNECT THE STORY','NCERT’s travel stories include Punjab’s plains, Rajasthan’s desert, Odisha’s coast and Sikkim’s mountains. Food, work, houses, music and craft connect with environments and community histories.','The book describes fishing near Odisha’s coast and farming in the plains, while many other occupations also exist in both places.','A postcard gives examples, not rules about everyone who lives there. No culture is better or more authentic than another.','How should we respond to unfamiliar customs?',['Mock them','Ask respectfully and listen','Assume everyone follows them'],1],
['land-pen','Landscape Pencil','Observing landform profiles','LOOK & SKETCH','A landscape sketch can show a high peak, a broad plain, dry dunes or a shoreline. Labels explain the observed features and avoid guessing people’s lives from one outline.','A mountain outline has high changes in elevation; a coastal sketch marks where land meets water.','A simple sketch is not a complete climate map and does not describe every resident.','What is especially useful in a landscape sketch?',['Clear observed features and labels','Only a random number','A claim that all people are alike'],0],
['shadows','Shadow Seekers','Light direction & shadow length','MOVE THE LIGHT','An opaque object blocks light. Its shadow forms away from the source. In a simple ground model, a lower light makes a longer shadow; a higher light makes it shorter.','Morning and evening shadows often point in different directions because the Sun’s apparent position changes.','The Sun is not exactly overhead at noon everywhere. Observe shadows; never look directly at the Sun.','A shadow lies…',['Towards the light source','Away from the light source','Inside the lamp'],1],
['moon','Moon-Phase Trail','Moon phases, festivals & observation','TURN & OBSERVE','The Moon reflects sunlight. As it travels around Earth, we see different amounts of its sunlit half. The cycle includes new, crescent, half and full appearances and repeats in about a month.','Poornima refers to a full Moon and Amavasya to a new Moon. Many festivals use lunar calendars, with regional traditions and dates.','Ordinary Moon phases are not caused by Earth’s shadow; that explanation belongs to a lunar eclipse.','Why does the Moon appear bright?',['It reflects sunlight','It is a lamp switched on nightly','It is made of fire'],0],
['sky','Sky Observatory','Day, night, stars & Chandrayaan','OBSERVE & EXPLORE','Earth’s rotation gives places their changing day and night. Stars are present in the daytime but usually hidden by the bright sky. The Moon can sometimes be visible in daylight.','India’s Chandrayaan-3 Vikram lander reached the lunar surface on 23 August 2023; Pragyan was its rover.','Do not teach that the Moon exists only at night. A sky picture shows one possible observation, not every object always visible.','Are stars still present during daytime?',['No, they disappear','Yes, but the bright sky usually hides them','Only on Sundays'],1],
['star-pen','Stargazer’s Notebook','Recording patterns in the sky','OBSERVE & DRAW','An observer can record the positions of stars as a pattern. A drawn connecting line helps remember the arrangement but is not a real line between stars.','Copy a small observed pattern into a notebook and compare it on another clear evening.','The game’s star patterns are invented observation exercises, not named constellations or current sky predictions.','Lines joining stars in a drawing are…',['Physical ropes in space','A way to show a pattern','Always the Moon’s orbit'],1]
];
SAFARI.topics=rows.map((r,i)=>({id:r[0],name:r[1],concept:r[2],tag:r[3],learn:r[4],why:r[4],example:r[5],hint:r[6],home:r[5],chapter:Math.floor(i/4),pages:SAFARI.worlds[Math.floor(i/4)].pages,color:['#d8efdf','#fce2c8','#e8dff7','#f9edc5'][i%4],doodle:i%4===3,question:r[7],options:r[8],answer:r[9]}));
SAFARI.doodles={supports:()=>false,names:{}};
