'use strict';
(() => {
const S=SAFARI,U=S.util,A=S.art,{svg,text,line,rect,dot,poly,btn,hit,I,pick,C}=A,{icon,tree,words}=S.scienceArt;
const segment=(a,b)=>[a,b],outline=(x,y,w,h)=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h],[x,y]];
function path(points,color='#8a77c7',width=7,dash=''){return `<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linejoin="round" stroke-linecap="round" ${dash?`stroke-dasharray="${dash}"`:''}/>`}
const D={};
D['tree-pen']=g=>{const x=I(g,235,330),y=I(g,190,215),spread=I(g,60,115);g.q.paths=[segment([x,y],[x-spread,y+73]),segment([x,y],[x,y+95]),segment([x,y],[x+spread,y+73])];g.prompt='Complete three roots below the soil. Keep the public path clear.';g.background=()=>rect(53,y,494,121,'#dbc9a4')+line([53,y],[547,y],'#739767',5)+tree(x,y-78,.7)+text(460,y-13,'SOIL',17)+text(300,340,'Roots grow into soil and take up water.',19)};
D['map-pen']=g=>{const start=[I(g,90,135),I(g,78,105)],a=[I(g,250,305),start[1]],b=[a[0],I(g,231,279)],end=[I(g,455,500),b[1]];g.q.paths=[segment(start,a),segment(a,b),segment(b,end)];g.prompt='Draw the route from school via the tree to the library.';g.background=()=>g.q.paths.map(p=>path(p,'#b5cba3',24)).join('')+icon('school',start[0],start[1]-30,31)+icon('tree',a[0],a[1]-30,31)+icon('library',end[0],end[1]-30,31)+text(300,338,'East → then south ↓ then east →',20)+text(494,57,'N ↑',20)};
D['leaf-pen']=g=>{const top=I(g,49,70),bottom=I(g,275,295),parallel=g.r()<.5;g.q.parallel=parallel;g.q.paths=parallel?[-47,0,47].map(dx=>segment([300+dx,top+50],[300+dx,bottom-42])):[segment([300,top+5],[300,bottom-5]),segment([300,165],[226,117]),segment([300,210],[378,164])];g.prompt=`Record the ${parallel?'roughly parallel':'branching'} veins in this model leaf.`;g.background=()=>`<path d="M300 ${top}Q110 172 300 ${bottom}Q490 172 300 ${top}" fill="#c0daa0" stroke="#7b9c66" stroke-width="3"/>`+text(300,335,'Observe the vein pattern, not just the outline.',19)};
D['dye-pen']=g=>{const sources=[['Turmeric','#e0b448'],['Beetroot','#c77991'],['Spinach','#7ca469']],choice=pick(g,sources),x=I(g,175,205),y=I(g,110,140),w=I(g,160,220);g.q.source=choice[0];g.q.paths=[[[x,y+90],[x+w/2,y],[x+w,y+90],[x,y+90]]];g.ink=null;g.prompt=`Choose ${choice[0].toLowerCase()} colour, then decorate the reused cloth.`;g.background=()=>rect(80,67,440,231,'#fff4d7',`stroke="#b5a78d" stroke-width="3"`)+(g.ink?poly(g.q.paths[0],g.ink[1]+'55'):'')+text(300,327,'Test familiar natural colours with an adult.',18);g.extraControls=()=>sources.map(a=>btn(a[0],'pigment',a[0],g.ink?.[0]!==a[0])).join('');g.extraAction=(k,v)=>{if(k!=='pigment')return false;g.ink=sources.find(a=>a[0]===v);g.refresh();return true};g.gate=()=>g.ink?.[0]===choice[0]};
D['plate-pen']=g=>{const cx=I(g,275,310),cy=169,r=I(g,105,122),turn=I(g,0,3)*15;const ends=[0,120,240].map(a=>U.pt(cx,cy,a+turn,r));g.q.paths=ends.map(p=>segment([cx,cy],p));g.prompt='Divide the food collage into three labelled food-group spaces.';g.background=()=>dot(cx,cy,r,'#fff9',`stroke="#9db78b" stroke-width="4"`)+icon('grain',cx+44,cy-47,31)+icon('dal',cx+4,cy+61,31)+icon('vegetable',cx-60,cy-14,31)+icon('water',484,179,42)+text(300,323,'Energy • growth • protective foods • water',17)+text(300,345,'Spaces are labels, not serving-size advice.',15)};
D['care-pen']=g=>{const y=I(g,112,155),p=[[95,y],[238,y+58],[380,y],[512,y+58]];g.q.paths=p.slice(1).map((b,i)=>segment(p[i],b));g.prompt='Join the grain journey: field → harvest → market → kitchen.';g.background=()=>['grain','seed','market','dal'].map((v,i)=>icon(v,p[i][0],p[i][1]-30,37)+text(p[i][0],p[i][1]+39,['FIELD','HARVEST','MARKET','KITCHEN'][i],14)).join('')+text(300,292,'Many people and natural resources help food reach us.',17)};
D['boat-pen']=g=>{const x=I(g,125,155),y=I(g,127,155),w=I(g,290,335),h=I(g,64,90);g.q.paths=[[[x,y],[x+55,y+h],[x+w-55,y+h],[x+w,y]],segment([x,y],[x+w,y]),segment([x+w/2,y],[x+w/2,y+h])];g.prompt='Sketch a broad paper-boat hull and its centre fold.';g.background=()=>rect(40,255,520,44,'#aed6df88')+text(300,64,'Plan → make → test → improve',22)+text(300,337,'A sketch is a plan; real boats need testing.',19)};
D['paper-pen']=g=>{const x=I(g,123,155),y=I(g,65,88),w=I(g,280,315),h=190;g.q.paths=[segment([x,y+h/2],[x+w,y+h/2]),[[x+50,y+h/2+47],[x+w/2,y+24],[x+w-50,y+h/2+47]]];g.prompt='Plan a reused-paper card: mark the fold and draw its cover motif.';g.background=()=>rect(x,y,w,h,'#fff7df',`stroke="#baa988" stroke-width="3"`)+text(300,310,'Use a clear side before choosing a new sheet.',19)};
D['land-pen']=g=>{g.q.kind=pick(g,['Mountain','Plain','Coast','Dunes']);const peak=I(g,55,105),middle=I(g,245,330),p=g.q.kind==='Mountain'?[[90,252],[205,peak+35],[285,201],[middle+80,peak],[510,252]]:g.q.kind==='Plain'?[[85,222],[215,218],[350,223],[510,220]]:g.q.kind==='Coast'?[[110,70],[245,107],[300,185],[270,269],[419,291]]:[[80,245],[179,141],[282,225],[401,peak+60],[520,245]];g.q.paths=p.slice(1).map((b,i)=>segment(p[i],b));g.prompt=`Record the visible profile of this ${g.q.kind.toLowerCase()} model.`;g.background=()=>path(p,'#9cb99366',15)+(g.q.kind==='Coast'?rect(335,42,189,202,'#b2d8e677'):'')+text(300,334,g.q.kind+' • observe and label the landform',19)};
D['star-pen']=g=>{const count=I(g,4,g.level?6:4),p=Array.from({length:count},(_,i)=>[100+i*400/(count-1),I(g,90,245)]);g.q.paths=p.slice(1).map((b,i)=>segment(p[i],b));g.prompt='Copy the observed star pattern into your sky notebook.';g.background=()=>rect(56,42,488,260,'#284755')+p.map(a=>icon('star',a[0],a[1]+9,29)).join('')+text(300,333,'An invented pattern • the connecting lines are imaginary',17)};
function pointSegment(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l)):0;return U.distance(p,[a[0]+t*dx,a[1]+t*dy])}
// Require endpoint accuracy, route coverage, and closeness along the whole stroke.
function matches(stroke,target,tolerance=20){if(stroke.length<2)return false;const closed=U.distance(target[0],target.at(-1))<1;let t=target;if(!closed&&U.distance(stroke[0],t.at(-1))<U.distance(stroke[0],t[0]))t=[...t].reverse();if(U.distance(stroke[0],t[0])>tolerance||U.distance(stroke.at(-1),t.at(-1))>tolerance)return false;const segments=t.slice(1).map((p,i)=>[t[i],p]);if(stroke.some(p=>Math.min(...segments.map(([a,b])=>pointSegment(p,a,b)))>tolerance))return false;const drawn=stroke.slice(1).map((p,i)=>[stroke[i],p]);for(const [a,b]of segments)for(let j=0;j<=10;j++){const p=[a[0]+(b[0]-a[0])*j/10,a[1]+(b[1]-a[1])*j/10];if(Math.min(...drawn.map(([c,d])=>pointSegment(p,c,d)))>tolerance)return false}return true}
Object.entries(D).forEach(([id,setup])=>{S.constructors[id]=g=>{g.mode='doodle';g.drawingGame=true;setup(g);g.s={paths:[],stroke:[],input:'draw',taps:[]};const original=g.prompt;g.feedback='Follow the numbered start dots. Every stroke is checked for shape and position.';g.hint='Draw between the dots in order. Follow the requested measurement or construction. Tap points is an alternative to freehand drawing.';g.draw=()=>{const next=g.q.paths[g.s.paths.length];return svg(g.background()+g.s.paths.map(p=>path(p,C[2])).join('')+(next?next.map((p,i)=>{const closed=U.distance(next[0],next.at(-1))<1;if(closed&&i===next.length-1)return '';const index=closed&&i===0&&g.s.taps.length===next.length-1?next.length-1:i;return hit('Point '+(index+1),'point',index,dot(...p,23,'transparent')+dot(...p,7,i===0?C[0]:'#fff',`stroke="#8e77b1" stroke-width="3"`)+text(p[0]+16,p[1]-11,closed&&i===0?'1 ↩':i+1,14))}).join(''):'')+(next&&g.level===0?path(next,'#967cad66',2,'4 7'):'')+path(g.s.stroke,C[1],5)+path(g.s.taps,C[1],5)+text(90,25,`${g.s.paths.length}/${g.q.paths.length} strokes`,16),original)};g.controls=()=> (g.extraControls?g.extraControls():'')+btn('↶ Undo','undo','',true)+btn(g.s.input==='draw'?'Tap points':'Use pen','input','',true)+btn('Check drawing','check');function submit(points){const target=g.q.paths[g.s.paths.length];if(!target)return;if(matches(points,target)){g.s.paths.push(target);g.s.stroke=[];g.s.taps=[];g.scene();if(g.s.paths.length===g.q.paths.length)g.say('All strokes placed. Check your finished drawing.');else g.say('That stroke fits. Draw the next marked part.')}else{g.s.stroke=[];g.s.taps=[];g.say('Try again: begin at point 1, cover the marked route, and end at the last point.')}}g.pointer=(x,y,phase)=>{if(g.s.input!=='draw'||g.s.paths.length>=g.q.paths.length)return;if(phase==='start')g.s.stroke=[[x,y]];if(phase==='move'&&g.s.stroke.length)g.s.stroke.push([x,y]);if(phase==='end'&&g.s.stroke.length){g.s.stroke.push([x,y]);submit(g.s.stroke)}if(phase==='cancel')g.s.stroke=[];g.scene()};g.pointerOnTargets=true;g.action=(k,v)=>{if(g.extraAction&&g.extraAction(k,v))return;if(k==='input'){g.s.input=g.s.input==='draw'?'tap':'draw';g.s.stroke=[];g.s.taps=[];g.refresh()}if(k==='undo'){g.s.paths.pop();g.s.stroke=[];g.s.taps=[];g.scene()}if(k==='point'&&g.s.input==='tap'){const p=g.q.paths[g.s.paths.length];if(!p)return;const i=+v;if(i!==g.s.taps.length){g.say('Tap the numbered points in order, starting with 1.');return}g.s.taps.push(p[i]);if(g.s.taps.length===p.length)submit(g.s.taps);g.scene()}if(k==='check'){if(g.s.paths.length===g.q.paths.length&&(!g.gate||g.gate()))g.success('Your drawing matches the scientific model. Beautifully done!');else g.say(g.gate&&!g.gate()?'Choose the requested natural colour, then complete the drawing.':`Complete all ${g.q.paths.length} strokes before checking.`)}}}});
S.drawingMatches=matches;
})();
