'use strict';
(() => {
const S=SAFARI,U=S.util,E=U.escape,C=['#ee8b58','#8a77c7','#3b9d91','#d5a83a'];
const text=(x,y,t,size=20,color='#234b42')=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" font-weight="800" fill="${color}">${E(t)}</text>`;
const line=(a,b,c='#375e52',w=4,extra='')=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${c}" stroke-width="${w}" stroke-linecap="round" ${extra}/>`;
const rect=(x,y,w,h,c='#fff9',extra='')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="10" fill="${c}" ${extra}/>`;
const dot=(x,y,r=10,c=C[0],extra='')=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" ${extra}/>`;
const poly=(p,c=C[0],extra='')=>`<polygon points="${p.map(a=>a.join(',')).join(' ')}" fill="${c}" stroke="#375e52" stroke-width="3" stroke-linejoin="round" ${extra}/>`;
const hit=(label,k,v,body)=>`<g role="button" tabindex="0" aria-label="${E(label)}" data-action="${k}" data-value="${v}">${body}</g>`;
const svg=(body,label='Interactive science model')=>`<svg viewBox="0 0 600 360" xmlns="http://www.w3.org/2000/svg" role="group" aria-label="${E(label)}"><defs><pattern id="dots" width="25" height="25" patternUnits="userSpaceOnUse">${dot(2,2,1,'#234b4218')}</pattern></defs><rect width="600" height="360" fill="url(#dots)"/><path d="M35 305Q280 270 565 307" fill="none" stroke="#42654812" stroke-width="18" stroke-linecap="round"/>${body}</svg>`;
const btn=(label,k,v='',secondary=false)=>`<button class="btn ${secondary?'secondary':''}" data-action="${k}" data-value="${v}">${E(label)}</button>`;
const choices=(a,k='choice')=>a.map(v=>btn(v.label??v,k,v.value??v,true)).join('');
function cube(x,y,z=38,c=C[2]){return poly([[x,y],[x+z,y-z*.5],[x+2*z,y],[x+z,y+z*.5]],'#d9ecc2')+poly([[x,y],[x+z,y+z*.5],[x+z,y+z*1.5],[x,y+z]],c)+poly([[x+z,y+z*.5],[x+2*z,y],[x+2*z,y+z],[x+z,y+z*1.5]],'#99baa0')}
function clock(t,x=300,y=176,r=128){const pt=(a,l)=>[x+Math.sin(a)*l,y-Math.cos(a)*l];return dot(x,y,r,'#fffc',`stroke="#769988" stroke-width="4"`)+Array.from({length:60},(_,i)=>line(pt(i*Math.PI/30,r-5),pt(i*Math.PI/30,r-(i%5?10:18)),'#809889',i%5?1:3)).join('')+Array.from({length:12},(_,i)=>text(...pt((i+1)*Math.PI/6,r-36),i+1,19)).join('')+line([x,y],pt((t%720)*Math.PI/360,r*.49),C[1],9)+line([x,y],pt((t%60)*Math.PI/30,r*.73),C[0],6)+dot(x,y,8,'#345a50')}
const I=(g,a,b)=>a+Math.floor(g.r()*(b-a+1)),pick=(g,a)=>U.pick(g.r,a),sum=a=>a.reduce((s,v)=>s+v,0);
function base(id,round,seed,api){return{id,round,seed,api,r:U.rng(seed+round*15485863),level:Math.min(2,Math.floor(round/8)),q:{},s:{},done:false,mode:'arcade',prompt:'',controls:()=>'',draw:()=>svg(''),action(){},scene(){api.stage()},refresh(){api.render()},say(t){api.tell(t)},success(t){if(!this.done){this.done=true;api.complete(t)}}}}
function check(g,ok,yes,no='Look closely at the model and try again.'){ok?g.success(yes):g.say(no)}
function numeric(g,target,body,max=9999){g.q.answer=target;g.s.value=0;g.controls=()=>`<label class="number-entry">Your answer <input inputmode="numeric" type="number" min="0" max="${max}" value="${g.s.value}" data-number aria-label="Your answer"></label>`+btn('Check','check');g.draw=()=>svg(body()+rect(205,282,190,53,'#fff9')+text(300,318,g.s.value,28));g.action=(k,v)=>{if(k==='number'){g.s.value=Math.max(0,Math.min(max,Math.trunc(Number(v)||0)));g.scene()}if(k==='check')check(g,g.s.value===target,`${target} — you found it!`,g.hint||'Use the picture to work through each part.')}}
function slider(g,min,max,step,label,format=v=>v){g.s.value=min;g.formatValue=format;g.controls=()=>`<div class="range-wrap"><button data-action="step" data-value="-${step}" aria-label="Decrease ${E(label)}">−</button><input type="range" aria-label="${E(label)}" min="${min}" max="${max}" step="${step}" value="${g.s.value}" data-range="main"><button data-action="step" data-value="${step}" aria-label="Increase ${E(label)}">+</button><output>${E(format(g.s.value))}</output></div>`+btn('Check','check');g.action=(k,v)=>{if(k==='range'||k==='step'){g.s.value=Math.max(min,Math.min(max,k==='range'?+v:g.s.value+(+v)));g.scene()}if(k==='check')check(g,g.s.value===g.q.answer,'Right on target!',g.hint)}}
function sortGame(g,values,labels,descending=false){g.q.values=values;g.q.order=values.map((v,i)=>i).sort((a,b)=>descending?values[b]-values[a]:values[a]-values[b]);g.s.chosen=[];g.draw=()=>svg(values.map((v,i)=>{const x=80+i*145,on=g.s.chosen.includes(i);return hit(labels[i],'card',i,rect(x-55,95,110,142,on?'#a7d5ad':'#fff9',`stroke="${C[i%4]}" stroke-width="3"`)+text(x,155,labels[i],21)+text(x,202,on?g.s.chosen.indexOf(i)+1:'↗',25))}).join('')+text(300,286,descending?'Greatest → smallest':'Smallest → greatest',21));g.controls=()=>btn('Start order again','clear','',true);g.action=(k,v)=>{if(k==='clear'){g.s.chosen=[];g.scene()}if(k==='card'){const i=+v;if(g.s.chosen.includes(i))return;if(i!==g.q.order[g.s.chosen.length]){g.say('Compare the unused cards. Which comes next?');return}g.s.chosen.push(i);g.scene();if(g.s.chosen.length===values.length)g.success('A complete, carefully ordered trail!')}}}
function compare(g,a,b,la,lb,art=''){g.q={a,b,answer:a===b?'=':a<b?'<':'>'};g.prompt='Compare the two quantities.';g.draw=()=>svg(rect(45,82,225,140)+rect(330,82,225,140)+text(157,150,la,27)+text(442,150,lb,27)+text(300,167,'?',35)+art);g.controls=()=>choices(['<','=','>']);g.action=(k,v)=>{if(k==='choice')check(g,v===g.q.answer,`${la} ${g.q.answer} ${lb}`,g.hint||'Express both quantities in the same units first.')}}
const F={};

S.art={text,txt:text,line,rect,dot,poly,hit,svg,btn,choices,cube,clock,C,I,pick,sum,numeric,slider,sortGame,check};S.constructors=F;
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
S.games={create(id,round,seed,api,options={}){let g,best=null;for(let tries=0;tries<50;tries++){g=base(id,round,(seed+Math.imul(tries,2654435761))>>>0,api);if(!F[id])throw Error('Missing game '+id);F[id](g);g.problemKey=hash(JSON.stringify(g.q));g.visualKey=hash(g.draw()+g.prompt);if(g.problemKey!==options.previous&&!(options.recent||[]).some(p=>p.visual===g.visualKey))best=g;if(g.problemKey!==options.previous&&!(options.recent||[]).some(p=>p.problem===g.problemKey||p.visual===g.visualKey))return g}return best||g}};
})();
