'use strict';
(() => {
const S=SAFARI;
const chapters=[
['A park has a damaged light and dry saplings. How can people cooperate?',['Ask a trained adult to arrange the electrical repair. Children can help with an adult-led watering group.','Agree who will keep checking the saplings after the event. Shared responsibility continues beyond one day.'],'What does interdependence mean?',['People and places support one another','Nobody needs anyone else','Only one job matters'],0],
['Plan ₹100: ₹40 for stationery and ₹30 to save. What remains?',['Set aside ₹40 for the planned purchase and ₹30 for savings.','₹100 − ₹40 − ₹30 = ₹30 remains. A plan helps avoid spending the same money twice.'],'What does a map landmark do?',['Guarantees every road is open','Helps identify a place or turning','Replaces every direction'],1],
['A bee visits a flower beside a tree with a bird’s nest. Name two links.',['The flower offers nectar to the bee; visits may also move pollen between flowers.','The tree offers a nesting place to the bird. Food and shelter are different kinds of links.'],'Which is an observation?',['I counted six legs','It must like my favourite song','It can never change'],0],
['How can a village celebration use resources thoughtfully?',['Use suitable local or reused materials and include people with different skills.','Plan clean-up and continued care. Solar energy can provide power when the system has sufficient sunlight or stored energy.'],'Does “natural” always mean safe?',['Yes, for every plant','No; material and use matter','Only if it is colourful'],1],
['A meal has rice only. How could its variety be increased?',['Consider a growth-supporting food such as dal or beans and vegetables or fruit.','Include safe water and discuss suitable portions with the family. The aim is variety, not a rigid serving rule.'],'Which habit supports thoughtful food choices?',['Judge everything only by taste','Read labels and include variety','Replace all water with soft drinks'],1],
['A child feels tired after playing and is worried about a message. What could help?',['Pause for water and rest, and allow time for adequate sleep later.','Share the worry with a trusted adult. Physical needs and emotional safety both matter.'],'Is it okay to refuse an unwanted hug?',['No, never','Only with strangers','Yes, and ask for support if needed'],2],
['A foil ball sinks but a broad foil cup floats in a classroom test. What changed?',['The material stayed the same while the shape changed.','Record both observations. Then keep the load similar while comparing another shape; do not explain the result using weight alone.'],'If a prediction is wrong, the result should be…',['Recorded honestly','Erased','Replaced by the prediction'],0],
['Choose between using a sheet again and pulping it.',['If a clear side remains suitable, use it before getting new paper. This reduces new use and reuses the sheet.','When no longer useful as a sheet, suitable paper may be recycled into new fibre-based material. Recycling still uses resources.'],'Which R is in NCERT’s five but is different from Repair?',['Repurpose','Repeat a wrong answer','Rush'],0],
['Compare a rainy coastal visit with a cold mountain visit.',['Read the stated weather and activities, then choose useful clothing and equipment for each.','Do not assume all people in either region live the same way. Ask respectfully about their particular experiences.'],'A climate description tells us…',['Only one person’s habits','Typical weather patterns over time','The exact weather every hour'],1],
['A shadow points right when a lamp is on the left. What happens if the lamp moves right?',['The opaque object blocks the new light direction. Its shadow forms on the opposite side.','Compare the shadow again. Its length can also change when the height or distance of the source changes.'],'Ordinary Moon phases are caused by…',['Earth’s shadow every night','Our changing view of its sunlit half','The Moon changing its actual shape'],1]
];
S.lessons=Object.fromEntries(S.topics.map((t,i)=>{const c=chapters[t.chapter],w=S.worlds[t.chapter];return[t.id,{
objective:`Discover ${t.concept.toLowerCase()} through ${t.name}. ${t.learn}`,
predict:`Before playing, think about this: ${t.question} Make a prediction and say what you would observe to check it.`,
explore:[`Try the first challenge in ${t.name}. Read the scene and labels before acting.`,`Change one choice or try a new puzzle. Notice what changes and what stays the same.`,t.example],
article:[['Look closely at the idea',t.learn],['A connection to everyday life',t.example],['Reason carefully',t.hint],['Observe, explain and try again',`Use the game’s labels and visible result to explain your choice. A prediction can change after observation. This activity connects with ${w.name}, NCERT Our Wondrous World Grade 4, printed pages ${w.pages}. The model simplifies the real world; compare it with familiar examples and discuss differences with an adult.`]],
worked:{q:c[0],steps:c[1]},checks:[{q:t.question,options:t.options,answer:t.answer,why:t.learn},{q:c[2],options:c[3],answer:c[4],why:c[1].join(' ')}],
reflect:`Explain one discovery from ${t.name}. Which observation or clue supports it? Give a new example, and say what the model leaves out.`,
faqs:[{q:`What does ${t.name} teach?`,a:t.learn},{q:'What important distinction should I remember?',a:t.hint},{q:t.doodle?'What does the drawing checker look for?':'How can I continue practising?',a:t.doodle?'Complete the marked construction using the observed shape or route. The checker checks endpoints and the whole path; a blank page or unrelated scribble does not pass. Tap points provides the same construction without freehand movement.':'There are 24 expedition rounds, followed by generated practice. New puzzle changes the current challenge without clearing progress. Restart begins only this game again. Science sometimes revisits a small set of fundamental ideas with different arrangements or contexts.'}],
activities:[{title:'Observe and discuss',text:`Find an everyday example related to ${t.concept.toLowerCase()}. Let the child describe the visible evidence before offering an explanation. ${t.hint}`},{title:'Create a new challenge',text:`Use paper, a drawing or a familiar safe object to make a related challenge. Compare the result with this game’s simplified model. ${t.example}`}],
related:[S.topics[t.chapter*4+(i+1)%4].id,S.topics[t.chapter*4+(i+2)%4].id]
}]}));
})();
