'use strict';
(() => {
const S=SAFARI;
// Retire shallow drills into richer investigations. Existing public bookmarks keep working.
S.aliases={team:'helpers','tree-pen':'park',messages:'journey','map-pen':'journey',habitat:'web','leaf-pen':'observe',solar:'village','dye-pen':'village','plate-pen':'plate',tastes:'cooking',hygiene:'routine','care-pen':'plate',float:'boat-pen',boats:'boat-pen',rs:'paper-test','paper-pen':'paper',culture:'lands','land-pen':'lands',sky:'moon','star-pen':'moon'};
const plans=[
['helpers','Neighbourhood Crew','Services, teamwork & continuing care',['Guide a visitor','Allocate helpers','Respond to a hazard','Plan continued care'],['team'],false,'How does a useful team plan change when something unexpected happens?'],
['park','Park Rescue','Planting, soil evidence & shared spaces',['Choose a planting site','Sort litter and leaves','Respond to soil moisture','Find an accessible route'],['tree-pen'],false,'Why can the same watering action help on one day and be unnecessary on another?'],
['journey','Neighbourhood Navigator','Transport, directions & communication',['Choose a suitable journey','Navigate a street map','Send a purposeful message','Give landmark directions'],['messages','map-pen'],false,'What information makes a route or a message useful to another person?'],
['savings','Pocket-Money Mission','Needs, spending, saving & bank balances',['Build a basket','Transfer savings','Predict a withdrawal balance','Respond to a new need'],[],false,'Where did each rupee go? Show that a transfer did not create more money.'],
['observe','Nature Detective','Close observation, classification & leaf sketches',['Magnify and count','Classify from evidence','Sketch observed veins','Plan respectful observation'],['leaf-pen'],true,'Which feature did you actually observe, and how does your drawing record it?'],
['web','Habitat Rescue','Interdependence, disruption & restoration',['Connect light, food and shelter','Predict a disruption','Plan habitat repair','Interpret the follow-up journal'],['habitat'],false,'Follow one connection to explain why removing a plant can affect an animal.'],
['village','Village Makers','Local materials, solar light & natural colours',['Build a model home','Follow rainwater','Test solar-panel sites','Choose a plant pigment'],['solar','dye-pen'],false,'Explain how materials, shape and position affected three different parts of the village.'],
['storage','Harvest Guardians','Drying, grain storage & prevention',['Prepare the grain','Inspect a container','Find a storage fault','Repair and monitor'],[],false,'Why does protecting a harvest involve repeated observation as well as a good container?'],
['plate','Food-Stall Challenge','Varied meals, water & thoughtful serving',['Compose a varied meal','Compare drink labels','Plan first servings','Reconstruct the food journey'],['plate-pen','care-pen'],false,'Explain a food choice using variety or the situation, without judging a person by their food.'],
['cooking','Kitchen Investigators','Cooking processes, tastes & food checks',['Arrange the cooking setup','Run and observe heating','Explore a festival taste','Inspect a food packet'],['tastes'],false,'How does the position of food relative to water and heat distinguish cooking methods?'],
['routine','My Healthy Evening','Movement, rest, hygiene & changing needs',['Arrange an evening','Practise hand coverage','Adapt to a new body or weather cue','Write a useful habit plan'],['hygiene'],false,'Which part of your plan changed when you received new information, and why?'],
['feelings','Kindness Quest','Listening, cooperation & trusted help',['Ask rather than assume','Respond supportively','Make turns fair','Build a safety plan'],[],false,'Describe how listening became a practical action instead of just kind words.'],
['spinner','Top-Test Workshop','Predictions, fair comparisons & wobble',['Make a prediction','Observe the first spin','Move only the stem','Compare a second test','Use the evidence'],[],false,'Which factor did you change, what stayed similar, and what did you observe?'],
['boat-pen','Doodle Boat Lab','Shape, cargo, evidence & redesign',['Predict about shape','Draw a functional hull','Load and test it','Diagnose the result','Improve for a new delivery'],['float','boats'],true,'Explain how your drawn hull and cargo placement affected the trial; compare the two designs.'],
['paper','Paper-Making Studio','Fibres, pulp, sheets & resource use',['Collect used material','Soak and mash','Spread an even sheet','Press, dry and colour'],['paper-pen'],false,'Which steps changed the material, and why could they not happen in any order?'],
['paper-test','Materials Mission','Fair tests, properties, uses & the Rs',['Control the test conditions','Collect property readings','Choose for a real purpose','Reuse, recycle or repair'],['rs'],false,'Use a measured property to justify a choice. Would the same paper be best for a different job?'],
['lands','Landscape Field Trip','Landforms, adaptation & cultural respect',['Observe a land feature','Plan a local response','Adapt to a weather warning','Write a careful postcard'],['culture','land-pen'],false,'Which statement is an observation, which is a local example, and which would unfairly describe everyone alike?'],
['pack','Weather-Wise Expedition','Forecasts, resources & cooperative travel',['Pack from the forecast','Adapt the bag','Share useful information','Follow local route guidance'],[],false,'Why should actual weather and a current warning guide a trip more than a general climate label?'],
['shadows','Shadow Sketch Lab','Prediction, light height & useful shade',['Draw a prediction','Compare the observation','Change light height','Position a marker in shade'],[],true,'Use the observed shadow to explain its direction and what happened when the light moved higher.'],
['moon','Sky-Journal Adventure','Moon phases, day and night & lunar exploration',['Match an observed phase','Predict a later observation','Turn the Earth model','Explain Moon phases','Build a lunar mission timeline'],['sky','star-pen'],false,'Distinguish a Moon-phase change from day and night on Earth. Which model explains each?']
];
const oldTopics=S.topics,oldLessons=S.lessons;
S.topics=plans.map(([id,name,concept,steps,merged,doodle,reflect],i)=>{
const old=oldTopics.find(t=>t.id===id),t={...old,name,concept,doodle,chapter:Math.floor(i/2),tag:doodle?'DRAW & INVESTIGATE':'MISSION & DISCOVERY',steps};
t.pages=S.worlds[t.chapter].pages;
const l=oldLessons[id];
S.lessons[id]={...l,objective:`Explore ${concept.toLowerCase()} through a connected mission. ${old.learn}`,predict:`What do you expect to happen, and what evidence would change your mind? ${reflect}`,explore:steps.map((s,n)=>`${n+1}. ${s}. Use what you discovered in the previous stage.`),article:[...l.article,...merged.flatMap(other=>{const o=oldTopics.find(t=>t.id===other);return[[o.concept,o.learn+' '+o.example+' '+o.hint]]}),['How this mission develops',`The game follows one connected situation: ${steps.join(' → ')}. Stages ask for different actions; a completed stage is followed by a new task, rather than the same question with a changed label. You can revise a plan after feedback. A wrong prediction is not a failure: a useful investigation records what happened.`],['What the model can and cannot show','These are classroom illustrations. Numerical scores, resource tokens, simplified streets and model test readings make comparisons visible; they are not measurements from a real place or predictions for real equipment. Use supervised observations to discover where actual results differ.']],reflect,faqs:[{q:`What do I learn in ${name}?`,a:`${concept}. The mission progresses through ${steps.join(', ').toLowerCase()}.`},{q:doodle?'Does the drawing have a learning purpose?':'Why does the activity change after each stage?',a:doodle?(id==='boat-pen'?'Yes. The hull’s measured width and depth affect its model cargo capacity; loading and redesign happen after drawing. A blank page or an unusable stroke cannot become a hull. Buttons offer a motor-accessible way to build the same shape.':id==='observe'?'Yes. The sketch records the parallel or branching pattern observed on a leaf. Draw two clear veins inside the notebook leaf, or use the accessible vein tools.':'Yes. Your line records a shadow prediction, which is then compared with the light model. Predictions may be wrong; the purpose is to compare, explain and investigate. Direction buttons offer the same prediction without freehand drawing.'):'Different stages develop different skills: observe, decide, try, interpret and apply. The next stage depends on the same situation, so completing isolated guesses is not enough.'},{q:'How do extended play and Restart work?',a:'Each completed mission contains four or five different stages. Twenty-four missions form an expedition, followed by free play. Scenarios are regenerated; some scientific ideas and investigation procedures recur for practice. Restart clears only this game’s current-edition progress. Earlier-edition records stay separately on your device.'}],related:[],worked:l.worked};
return t;
});
S.topics.forEach((t,i)=>{S.lessons[t.id].related=[S.topics[i%2?i-1:i+1].id,S.topics[(i+2)%S.topics.length].id]});
const boat=S.lessons['boat-pen'];boat.worked={q:'A narrow hull carries three model blocks, but four are requested. How can you investigate?',steps:['Keep the foil material the same. Record the width, depth, load and whether the load is balanced.','Test and record the result honestly. A hull may sit too low or tip with a one-sided load.','Widen the hollow hull and distribute the load. Retest under the stated conditions. The simplified capacity score is not a physical formula for real boats.']};
const boatTopic=S.topics.find(t=>t.id==='boat-pen');boatTopic.learn='A hollow hull and a balanced load can help a model boat float. Draw, test, record what happened and improve the design for a new cargo.';boatTopic.example='Keep the foil material the same while changing the hull width. Then compare trials with the same load.';boatTopic.hint='Draw an open U with a lower base, or use the shape buttons. Load both sides. Widen the hull if the test shows insufficient model capacity.';boat.article[0]=['A design you can test',boatTopic.learn];boat.article[1]=['Compare shape and load',boatTopic.example];boat.article[2]=['Model limits','The same material may behave differently when shaped into a hollow hull. This game uses a simple capacity rule based on drawing dimensions. Real floating also depends on watertightness, material, dimensions and displaced water.'];boat.objective=boatTopic.learn;
const spin=S.lessons.spinner;spin.worked={q:'The first top wobbles with its stem away from the centre. How can you compare a new design fairly?',steps:['Keep the shape, stem and push similar. Record the first observation.','Move only the stem closer to the centre and test again.','Compare the wobble readings. A changed prediction is useful learning; the model cannot guarantee an exact real spinning time.']};
const shadow=S.lessons.shadows;shadow.worked={q:'A light is on the left of a pole. Predict, test, then raise the light.',steps:['Draw the expected shadow from the foot of the pole. The drawing is a prediction, not yet an observation.','Reveal the model result: the shadow extends to the right, away from the light.','Move the light higher while keeping the pole unchanged. The ground shadow becomes shorter in this model.']};
S.doodles={supports:id=>S.topics.some(t=>t.id===id&&t.doodle),names:Object.fromEntries(S.topics.filter(t=>t.doodle).map(t=>[t.id,t.name]))};
})();
