'use strict';
(() => {
const S=SAFARI,F=S.constructors,{text,line,rect,dot,poly,hit,btn,choices,I,pick,C}=S.art;
const {words,icon,tree,building}=S.scienceArt;
const {journey,phase,choose,need,toggle,cards,panel,shuffled}=S.missionTools;

F.village=g=>{g.q={rain:pick(g,[true,false]),clear:pick(g,[0,2,3]),dye:pick(g,[['Yellow','Turmeric','#e1b443'],['Pink-red','Beetroot','#c86783'],['Green','Spinach','#73a76b']])};g.s.wall=0;g.s.roof=0;g.s.panel=1;g.s.rain=false;g.s.stamps=[];
 const house=()=>rect(170,154,260,140,['#f7efd8','#d3ae87','#adc58e'][g.s.wall])+ (g.s.roof?poly([[145,155],[300,68],[455,155]],g.s.roof===1?'#ceaf74':'#c88c70'):rect(153,139,294,20,'#bbc5b1'))+rect(273,231,54,63,'#9c7655')+[217,379].map(x=>rect(x-25,184,50,43,'#e8f0da')).join('');
 journey(g,[
 phase('home','construction','Build with local materials',()=>`${g.q.rain?'Rain is expected':'A sunny day is forecast'}. Build walls and a rain-shedding roof.`,()=>house()+text(300,328,['No walls','Clay walls','Bamboo panels'][g.s.wall]+' · '+['Flat roof','Sloping thatch','Sloping tiles'][g.s.roof],20),()=>btn('Walls','wall','',true)+btn('Roof','roof','',true)+btn('Test weather','weather'),(k)=>{if(k==='wall')g.s.wall=(g.s.wall+1)%3;if(k==='roof')g.s.roof=(g.s.roof+1)%3;if(k==='weather')need(g,g.s.wall>0&&g.s.roof>0,'Build the walls and choose a slope so rain can run off.','The model roof sheds water. Real homes also need sound construction and maintenance.');else g.scene()}),
 phase('weather-evidence','trace-runoff','Follow the rain','Trace where water runs from the sloping roof: choose both outlets.',()=>house()+[0,1].map(i=>line([300,62],[i?464:136,165],'#77aabe',5)).join('')+cards(['Left ground channel','Through the doorway','Right ground channel'],'drain',g.s.stamps,268),()=>btn('Check drainage','draincheck'),(k,v)=>{if(k==='drain')toggle(g,'stamps',v);if(k==='draincheck')need(g,g.s.stamps.length===2&&g.s.stamps.includes('Left ground channel')&&g.s.stamps.includes('Right ground channel'),'Guide both roof streams away from the doorway.','Roof shape and safe drainage work together.')}),
 phase('solar','position-experiment','Power the festival lamp','Move the panel; test each spot until sunlight reaches it.',()=>[0,1,2,3].map(i=>rect(55+i*135,109,118,85,i===g.q.clear?'#ffe5a1':'#9baa9488')+(i!==g.q.clear?tree(111+i*135,84,.5):icon('sun',111+i*135,86,39))).join('')+rect(65+g.s.panel*135,159,100,47,'#719cac')+line([115+g.s.panel*135,210],[300,266],C[1],4)+dot(300,277,25,g.s.power?'#ffe06d':'#b0bba7')+text(300,332,g.s.power?'Lamp on':'Model solar lamp',20),()=>btn('← Panel','panel',-1,true)+btn('Panel →','panel',1,true)+btn('Test light','test')+ (g.s.power?btn('Use this site','use'):''),(k,v)=>{if(k==='panel'){g.s.panel=Math.max(0,Math.min(3,g.s.panel+(+v)));g.s.power=false;g.refresh()}if(k==='test'){g.s.power=g.s.panel===g.q.clear;g.say(g.s.power?'Light reaches the panel: the model lamp lights.':'Shade blocks light here. Try another site.');g.refresh()}if(k==='use')need(g,g.s.power,'Test a sunlit site first.','The panel works with sunlight reaching it.')}),
 phase('natural-colour','paint-design','Make a harvest welcome',()=>`Choose a plant pigment for a ${g.q.dye[0].toLowerCase()} welcome banner.`,()=>rect(87,106,426,155,g.s.pigment===g.q.dye[0]?g.q.dye[2]:'#fffaf2')+words(300,151,'WELCOME TO OUR HARVEST CELEBRATION',28,27)+text(300,315,'Plants provide materials, food and colour.',19),()=>choices(['Turmeric','Beetroot','Spinach'],'pigment'),(k,v)=>{if(k==='pigment'){if(v!==g.q.dye[1]){g.say('Compare the plant colours: turmeric yellow, beetroot pink-red, spinach green.');return}g.s.pigment=g.q.dye[0];g.advance('Natural pigments come from plants; an adult guides handling, and natural does not always mean safe.')}})
 ],()=>`Village prepared: a model home, drainage, solar lighting and a plant-colour welcome.`);
};

F.storage=g=>{g.q={grain:pick(g,['rice','wheat','millet']),wet:I(g,2,4),leak:pick(g,['Cracked lid','Damp base'])};g.s.moisture=g.q.wet;g.s.cover=false;g.s.checked=false;g.s.jar=-1;
 journey(g,[
 phase('dry','process-control','Rescue the harvest',()=>`The ${g.q.grain} is damp. Spread it, then allow drying before storage.`,()=>rect(90,172,420,99,'#d4b47f')+Array.from({length:25},(_,i)=>dot(110+i%10*40,196+Math.floor(i/10)*25,6,'#f3d887')).join('')+icon(g.s.spread?'sun':'water',300,110,55)+text(300,317,g.s.moisture?'Moisture meter: '+g.s.moisture:'Model grain is dry',22),()=>btn('Spread grain','spread','',true)+btn('Dry one interval','dry','',true)+btn('Store batch','store'),(k)=>{if(k==='spread'){g.s.spread=true;g.scene()}if(k==='dry'){if(!g.s.spread){g.say('Spread the damp grain first so it can dry more evenly.');return}g.s.moisture=Math.max(0,g.s.moisture-1);g.scene()}if(k==='store')need(g,g.s.moisture===0,'Dry the grain before closing it in a container.','Drying reduces moisture before storage. The meter is a learning model, not a real moisture reading.')}),
 phase('container','inspect-select','Choose a store',()=>`Keep your dried ${g.q.grain} dry and protected. Inspect the containers.`,()=>[0,1,2].map(i=>hit(['Damp pot','Clean dry pot','Open basket'][i],'jar',i,rect(70+i*180,102,126,156,g.s.jar===i?'#bbd39c':'#dcc099')+(i!==2?rect(60+i*180,89,146,20,'#9d8060'):'')+icon(i===0?'water':i===1?'✓':'grain',133+i*180,165,37)+words(133+i*180,291,['Damp inside','Clean, dry, covered','No cover'][i],17,18))).join(''),()=>btn('Fill chosen store','fill'),(k,v)=>{if(k==='jar'){g.s.jar=+v;g.scene()}if(k==='fill')need(g,g.s.jar===1,'Do not add moisture back. Use a clean, dry, covered container.','The container protects the dried grain.')}),
 phase('inspection','find-fault','A week later: inspect',()=>`A warning appears: ${g.q.leak.toLowerCase()}. Find the place to repair.`,()=>rect(177,129,246,172,'#d7b785')+hit('Inspect lid','inspect','Cracked lid',rect(161,95,278,35,g.q.leak==='Cracked lid'?'#bc8b66':'#a28b69')+text(300,120,'LID',18))+hit('Inspect base','inspect','Damp base',rect(177,270,246,35,g.q.leak==='Damp base'?'#72969a':'#ad956f')+text(300,293,'BASE',18))+icon('grain',300,228,65),null,choose(g,null,'inspect',g.q.leak,'Inspection found the problem before storing the next batch.','Match the visible warning to the part of the store.')),
 phase('prevention','cause-remedy','Prevent the problem returning','Choose a repair and a continuing care plan.',()=>icon('tools',300,108,60)+cards(g.q.leak==='Cracked lid'?['Replace the damaged lid','Keep checking for pests','Hide the crack under grain']:['Move onto a dry raised base','Check for dampness regularly','Add more damp grain'],'repair',g.s.repairs||[],177),()=>btn('Protect the harvest','protect'),(k,v)=>{if(k==='repair')toggle(g,'repairs',v);if(k==='protect'){let r=g.s.repairs||[];need(g,r.length===2&&!r.some(v=>v.startsWith('Hide')||v.startsWith('Add')),'Choose a practical fix AND a regular check.','Traditions include neem leaves, but clean dry storage and inspection still matter.')}})
 ],()=>`Harvest saved through drying, suitable storage, inspection and repair.`);
};

const FOOD=[['Rice','energy','grain'],['Millet roti','energy','grain'],['Dal','growth','dal'],['Beans','growth','dal'],['Carrot','protective','vegetable'],['Guava','protective','fruit']];
F.plate=g=>{g.q={base:pick(g,FOOD.slice(0,2)),protein:pick(g,FOOD.slice(2,4)),veg:pick(g,FOOD.slice(4)),guests:I(g,2,4),leftovers:pick(g,[true,false])};g.s.food=[];g.s.servings=1;g.s.water=false;
 journey(g,[
 phase('variety','compose-meal','Open your food stall','Your plate has an energy food. Add two foods for variety.',()=>dot(300,120,65,'#fff9',`stroke="#9ab183" stroke-width="4"`)+icon(g.q.base[2],300,122,47)+text(300,161,g.q.base[0],17)+cards([g.q.protein[0],g.q.veg[0],'Another rice helping'],'food',g.s.food,204)+text(300,316,'Groups overlap; this is a simple variety guide.',16),()=>btn('Serve this selection','serve'),(k,v)=>{if(k==='food')toggle(g,'food',v);if(k==='serve')need(g,g.s.food.length===2&&g.s.food.includes(g.q.protein[0])&&g.s.food.includes(g.q.veg[0]),'Add a body-building food and a fruit or vegetable to the energy food.','Your selection adds different kinds of nutrients. The picture does not prescribe portion sizes.')}),
 phase('water','label-inspect','Choose a regular drink','Compare the labels for a drink to accompany the meal.',()=>[0,1].map(i=>rect(91+i*282,100,137,152,i?'#dbb68e':'#b8dce1')+words(160+i*282,148,i?'Sweet drink':'Clean drinking water',15,20)+text(160+i*282,228,i?'Added sugar':'No added sugar',17)).join(''),()=>choices(['Clean drinking water','Sweet drink'],'drink'),choose(g,null,'drink','Clean drinking water','Clean water is a useful everyday drink; frequent sugary drinks add extra sugar.','Choose the everyday drink without added sugar.')),
 phase('portions','resource-allocation','Serve without needless waste',()=>`${g.q.guests} guests each ask for one small first serving. Prepare that many.`,()=>Array.from({length:g.q.guests},(_,i)=>icon('walk',120+i*110,118,49)).join('')+Array.from({length:g.s.servings},(_,i)=>dot(85+i*85,237,32,'#fff9')+icon('dal',85+i*85,247,35)).join('')+text(300,322,g.s.servings+' first servings prepared',24),()=>btn('− Serving','portion',-1,true)+btn('+ Serving','portion',1,true)+btn('Send plates','send'),(k,v)=>{if(k==='portion'){g.s.servings=Math.max(1,Math.min(6,g.s.servings+(+v)));g.scene()}if(k==='send')need(g,g.s.servings===g.q.guests,'Meet the guests’ stated requests. They can ask for more if hungry.','Small first servings with more available can reduce waste without forcing anyone to eat.')}),
 phase('food-journey','dependency-order','Thank the people behind food','Build the journey of grain to this meal.',()=>cards(['Cook','Farmer','Transporter','Market'],'chain',g.s.chain||[],115)+text(300,322,(g.s.chain||[]).join(' → ')||'Tap the first contributor.',18),()=>btn('Clear journey','clear','',true),(k,v)=>{const order=['Farmer','Transporter','Market','Cook'];g.s.chain??=[];if(k==='clear'){g.s.chain=[];g.scene()}if(k==='chain'){if(v!==order[g.s.chain.length]){g.say('Think about growing, carrying, selling and preparing food.');return}g.s.chain.push(v);if(g.s.chain.length===4)g.advance('Soil, water and many people help make a meal possible.');else g.scene()}})
 ],()=>`Food stall complete: variety, clean water, thoughtful serving and respect for food workers.`);
};

F.cooking=g=>{g.q={recipe:pick(g,[['Idli','Steam','In rising steam'],['Rice','Boil','In hot water'],['Roasted corn','Roast','Over dry heat']]),taste:pick(g,[['Jaggery','Sweet'],['Tamarind','Sour'],['Salt','Salty'],['Chilli','Pungent'],['Bitter gourd','Bitter'],['Raw banana','Astringent']])};g.s.position=-1;g.s.water=0;g.s.heat=false;g.s.observed=false;
 const pot=()=>rect(178,176,244,116,'#b4c9b4')+rect(191,218,218,61,g.s.water?'#8fbfce':'#d5ded0')+line([181,176],[418,176],C[2],6)+(g.s.heat?icon('♨',300,331,32):'')+icon('grain',300,g.s.position===0?249:g.s.position===1?147:94,40);
 journey(g,[
 phase('method','apparatus-build','Set up the kitchen',()=>`Make ${g.q.recipe[0].toLowerCase()}: place the food ${g.q.recipe[2].toLowerCase()}.`,()=>pot()+text(80,220,'Adult',17)+text(80,243,'cooks',17),()=>choices([{label:'In water',value:0},{label:'Above water',value:1},{label:'Dry heat',value:2}],'position')+btn('Use this setup','setup'),(k,v)=>{if(k==='position'){g.s.position=+v;g.scene()}if(k==='setup')need(g,g.s.position==={Steam:1,Boil:0,Roast:2}[g.q.recipe[1]],'Choose where the food sits relative to water and heat.','You matched the cooking method to the recipe.')}),
 phase('heat-test','controlled-observation','Watch a model cook','Set the water needed by this method, then ask the adult to heat.',()=>pot()+words(300,69,g.s.observed?(g.s.position===0?'Water bubbles around food':g.s.position===1?'Steam rises to the food':'Dry heat warms the food'):'Set up before heating.',39,21),()=>btn('Water on / off','water','',true)+btn('Adult heats','heat')+(g.s.observed?btn('Record observation','record'):''),(k)=>{if(k==='water'){g.s.water=1-g.s.water;g.s.observed=false;g.refresh()}if(k==='heat'){const correct=g.s.position===2?!g.s.water:!!g.s.water;if(!correct){g.say(g.s.position===2?'This roasting model uses dry heat.':'Boiling and steaming need water in the pot.');return}g.s.heat=true;g.s.observed=true;g.refresh()}if(k==='record')need(g,g.s.observed,'Run the model first.','Heat reaches the food in a different way for boiling, steaming and roasting.')}),
 phase('taste','sensory-classification','A festival ingredient',()=>`The festival dish includes ${g.q.taste[0].toLowerCase()}. Match its usual taste.`,()=>icon('fruit',300,116,64)+text(300,163,g.q.taste[0],28)+cards(shuffled(g,[g.q.taste[1],...['Sweet','Sour','Salty','Pungent','Bitter','Astringent'].filter(t=>t!==g.q.taste[1]).slice(0,2)]),'taste',[],228),null,choose(g,null,'taste',g.q.taste[1],'Taste describes a food; it does not tell you every nutrient in it.','Think of the usual taste. Ripeness and preparation can change tastes.')),
 phase('label','food-safety-inspection','Check before serving','A sealed food packet has a damaged seal. Find the safe decision.',()=>rect(167,80,267,181,'#edd7ac')+line([171,89],[419,110],'#ad6467',7,'stroke-dasharray="16 11"')+text(300,162,'SEAL: DAMAGED',24)+text(300,208,'Date: still in range',20)+cards(['Ask an adult; do not serve','Serve because the date is fine'],'serve',[],276),null,choose(g,null,'serve','Ask an adult; do not serve','Packaging condition matters as well as the printed date.','A date alone does not make damaged packaging safe.'))
 ],()=>`Kitchen investigation complete: method, observed change, taste and a careful label check.`);
};

F.routine=g=>{g.q={after:pick(g,['outdoor play','gardening','using the toilet']),tired:pick(g,[true,false]),slots:shuffled(g,['Move / play','Quiet rest','Bedtime routine'])};g.s.schedule={};g.s.selected='Move / play';g.s.rub=[];g.s.food=[];
 journey(g,[
 phase('day-plan','timeline-placement','Build a balanced evening','Place play, quiet rest and bedtime in a sensible order.',()=>[0,1,2].map(i=>hit('Time slot '+(i+1),'slot',i,rect(48+i*185,116,169,150,'#fffaf0')+text(132+i*185,151,['After school','Later','Before sleep'][i],18)+words(132+i*185,197,g.s.schedule[i]||'Tap to place',16,21))).join('')+text(300,315,'Holding: '+g.s.selected,21),()=>choices(g.q.slots,'activity')+btn('Try my evening','plan'),(k,v)=>{if(k==='activity'){g.s.selected=v;g.scene()}if(k==='slot'){g.s.schedule[v]=g.s.selected;g.scene()}if(k==='plan')need(g,['Move / play','Quiet rest','Bedtime routine'].every((a,i)=>g.s.schedule[i]===a),'Include movement, then time to settle, then a bedtime routine.','Movement, rest and sleep all have a place. Activities can be adapted to different abilities.')}),
 phase('hygiene','coverage-action','Soap reaches every part',()=>`After ${g.q.after}: soap is on. Rub palms, backs and between fingers.`,()=>icon('hands',300,132,89)+cards(['Palms','Backs','Between fingers'],'rub',g.s.rub,205)+text(300,320,g.s.rub.length+'/3 areas rubbed in this model',20),()=>btn('Rinse and dry','rinse'),(k,v)=>{if(k==='rub'&&!g.s.rub.includes(v)){g.s.rub.push(v);g.scene()}if(k==='rinse')need(g,g.s.rub.length===3,'Cover all the areas shown before rinsing and drying.','Real handwashing also includes nails and thumbs; practise with an adult.')}),
 phase('body-cue','adaptation','Listen to a body signal',()=>g.q.tired?'During play, you feel tired and thirsty. Adapt the plan.':'It starts raining during outdoor play. Adapt the plan.',()=>icon(g.q.tired?'water':'umbrella',300,126,76)+cards(g.q.tired?['Water + a rest break','Keep racing without a break']:['Move to a safe indoor game','Keep playing in the storm'],'adapt',[],234),null,choose(g,null,'adapt',g.q.tired?'Water + a rest break':'Move to a safe indoor game','A healthy plan changes when your body or surroundings change.','Use the cue in the situation instead of following a plan blindly.')),
 phase('reflection','journal-edit','Write an honest health journal','Choose two habits from this evening to continue tomorrow.',()=>cards(['Movement suited to me','Time to rest and sleep','Ignore every body signal'],'habit',g.s.food,150)+text(300,310,'Your journal records habits, not a score for your body.',17),()=>btn('Save tomorrow’s plan','journal'),(k,v)=>{if(k==='habit')toggle(g,'food',v);if(k==='journal')need(g,g.s.food.length===2&&!g.s.food.includes('Ignore every body signal'),'Choose habits that support both movement and recovery.','Health includes daily care, flexible activity and enough rest.')} )
 ],()=>`Evening planned: movement, rest, hygiene and a thoughtful response to changing needs.`);
};

F.feelings=g=>{g.q={story:pick(g,[['A new child stands alone','left out'],['A friend’s model breaks','upset'],['A teammate is not getting a turn','frustrated']]),players:I(g,3,5)};g.s.turns=Array(g.q.players).fill(0);g.s.help=[];g.s.asked=false;
 journey(g,[
 phase('notice','perspective-taking','Notice, then ask',()=>g.q.story[0]+'. Find a way to understand how they feel.',()=>icon('walk',160,156,77)+words(388,109,'An expression is a clue, not proof of a feeling.',23,23)+cards(['Ask how they feel','Decide without asking'],'notice',[],243),null,choose(g,null,'notice','Ask how they feel','Listening gives the person a chance to tell you.','People can feel differently in the same situation. Ask rather than assume.')),
 phase('listen','dialogue-response','Choose words that help',()=>`They say “I feel ${g.q.story[1]}.” Respond without dismissing the feeling.`,()=>rect(65,82,470,96,'#fff8')+words(300,122,'“I feel '+g.q.story[1]+'.”',36,25)+cards(['I hear you. What would help?','You should not feel that way'],'reply',[],224),null,choose(g,null,'reply','I hear you. What would help?','You acknowledged the feeling and invited a useful next step.','A supportive reply listens without telling someone their feeling is wrong.')),
 phase('cooperate','fair-allocation','Turn kindness into action',()=>`Give each of ${g.q.players} players one first turn before anyone gets two.`,()=>g.s.turns.map((n,i)=>hit('Give player '+(i+1)+' a turn','turn',i,dot(75+i*450/(g.q.players-1),154,39,n?'#b8d692':'#efcda5')+icon('walk',75+i*450/(g.q.players-1),157,38)+text(75+i*450/(g.q.players-1),226,'Turns '+n,19))).join('')+text(300,303,'Tap a player to give a turn.',20),()=>btn('Start the fair game','fair'),(k,v)=>{if(k==='turn'){if(g.s.turns[+v]){g.say('Someone else is still waiting for a first turn.');return}g.s.turns[+v]=1;g.scene()}if(k==='fair')need(g,g.s.turns.every(n=>n===1),'Check that everyone has a first turn.','A fair turn plan makes inclusion visible.')}),
 phase('trusted-help','safety-plan','Some problems need an adult','Someone keeps making a child uncomfortable. Choose two helpful actions.',()=>icon('school',300,111,65)+cards(['Move to a safer place','Tell a trusted adult','Keep the worrying secret'],'help',g.s.help,176)+text(300,326,'The child is never to blame for unwanted behaviour.',16),()=>btn('Save the safety plan','safe'),(k,v)=>{if(k==='help')toggle(g,'help',v);if(k==='safe')need(g,g.s.help.length===2&&g.s.help.includes('Move to a safer place')&&g.s.help.includes('Tell a trusted adult'),'Choose a safer place and trusted help. Keep telling until someone helps.','If one adult does not help, keep telling another trusted adult. It is not the child’s fault.')} )
 ],()=>`Care mission complete: listen, respond kindly, share turns and seek trusted help.`);
};
})();
