'use strict';
(() => {
const S=SAFARI,A=S.art,F=S.constructors,U=S.util;
const {svg,text,line,rect,dot,poly,hit,btn,choices,I,pick,C}=A;
const {words,icon,tree,building,moon,phases}=S.scienceArt;
const sum=a=>a.reduce((x,y)=>x+y,0), shuffled=(g,a)=>U.shuffle(g.r,a);
const panel=(title,body,symbol='✦')=>icon(symbol,300,112,58)+words(300,157,title,36,24)+words(300,224,body,45,19);
const cards=(items,key,selected=[],y=179)=>items.map((item,i)=>{const a=typeof item==='string'?{label:item,value:item}:item;const n=Math.min(3,items.length),w=520/n,x=300+(i%n-(n-1)/2)*w,yy=y+Math.floor(i/n)*79;return hit(a.label,key,a.value,rect(x-w/2+5,yy,w-10,70,selected.includes(a.value)?'#badca8':'#fffaf1',`stroke="${selected.includes(a.value)?'#56836b':'#c3cbb2'}" stroke-width="2"`)+words(x,yy+29,a.label,n===3?17:24,19))}).join('');
const count=(label,n,total)=>text(300,330,`${label}: ${n} / ${total}`,19);
function choose(g,items,key,answer,yes,no){return(k,v)=>{if(k!==key)return;if(v!==String(typeof answer==='function'?answer():answer)){g.say(no);return}g.advance(yes)}}
function toggle(g,key,value){g.s[key]??=[];g.s[key]=g.s[key].includes(value)?g.s[key].filter(v=>v!==value):[...g.s[key],value];g.scene()}
function need(g,condition,message,next){if(!condition){g.say(message);return false}g.advance(next);return true}
function journey(g,steps,conclusion){g.steps=steps;g.s.phase=0;g.s.evidence=[];g.s.history=[];g.hint='Read the mission above the scene. Use the evidence you collect; changing a design after a test is part of learning.';g.enter=()=>{const s=steps[g.s.phase];g.phaseKey=s.key;g.mechanic=s.kind;g.prompt=s.title();g.feedback=g.s.evidence.at(-1)||'Your choices change what happens. Explore, test and improve.';s.init?.();g.refresh()};g.advance=note=>{if(note)g.s.evidence.push(note);g.s.history.push(g.phaseKey);if(g.s.phase===steps.length-1){g.success(conclusion(g));return}g.s.phase++;g.enter()};g.draw=()=>{const s=steps[g.s.phase];return svg(text(300,25,`${g.s.phase+1}/${steps.length} · ${s.label}`,17)+steps.map((_,i)=>rect(160+i*280/steps.length,36,270/steps.length,5,i<=g.s.phase?'#678b61':'#d3dfc8')).join('')+s.draw(),s.label)};g.controls=()=>steps[g.s.phase].controls?.()||'';g.action=(k,v)=>{if(!g.done)steps[g.s.phase].action?.(k,v)};const s=steps[0];g.phaseKey=s.key;g.mechanic=s.kind;g.prompt=s.title();s.init?.()}
function phase(key,kind,label,title,draw,controls,action,init){return{key,kind,label,title:typeof title==='function'?title:()=>title,draw,controls,action,init}}
function numberControl(label,value,key,min,max){return btn('− '+label,key,-1,true)+`<span class="mission-value">${value}</span>`+btn('+ '+label,key,1,true)}
function adjust(g,k,v,key,min,max){if(k===key){g.s[key]=Math.max(min,Math.min(max,g.s[key]+Number(v)));g.scene();return true}return false}
const routeSVG=(g,position,goal,blocked,marks={})=>Array.from({length:25},(_,i)=>{let x=166+i%5*54,y=61+Math.floor(i/5)*52;return rect(x,y,48,46,blocked.includes(i)?'#8c9b89':i===goal?'#ffe1a0':'#fff9')+icon(i===position?'walk':blocked.includes(i)?'×':marks[i]|| (i===goal?'star':''),x+24,y+32,26)}).join('')+text(95,92,'N ↑',23)+text(495,319,'Map model',16);
function move(g,v,blocks){const pos=g.s.pos,n=pos+Number(v);if(n<0||n>24||(Math.abs(Number(v))===1&&Math.floor(pos/5)!==Math.floor(n/5))||blocks.includes(n)){g.say('That street is closed or outside the map. Try another direction.');return false}g.s.pos=n;g.scene();return true}
const compass=()=>choices([{label:'← West',value:-1},{label:'↑ North',value:-5},{label:'↓ South',value:5},{label:'East →',value:1}],'walk');

F.helpers=g=>{
 const jobs=[['A visitor needs a check-up','Health centre','health'],['A child wants to borrow a book','Library','library'],['A family needs vegetables','Market','market']];g.q={visitor:pick(g,jobs),crowd:I(g,3,5),event:pick(g,['Tree festival','Neighbourhood fair','Park opening'])};g.s.teams={welcome:0,garden:0};g.s.selected=[];
 journey(g,[
 phase('service','dispatch','Help a neighbour',()=>`${g.q.event}: guide your first visitor.`,()=>personScene(g.q.visitor[0])+cards(['Library','Market','Health centre'],'place',[],217),null,choose(g,null,'place',g.q.visitor[1],'A public service meets a real need.','Read the visitor’s need, then choose a place that provides that service.')),
 phase('teams','allocation','Make a team plan',()=>`Share 4 helpers: ${g.q.crowd>3?2:1} for welcoming; at least 2 for planting.`,()=>building('Welcome','school',160,142,155)+tree(435,142,.8)+text(160,288,g.s.teams.welcome+' helpers',23)+text(435,288,g.s.teams.garden+' helpers',23)+text(300,80,(4-g.s.teams.welcome-g.s.teams.garden)+' helpers available',22),()=>btn('+ Welcome','assign','welcome',true)+btn('+ Plant','assign','garden',true)+btn('Clear','clear','',true)+btn('Open event','open'),(k,v)=>{if(k==='assign'&&g.s.teams[v]!==undefined&&sum(Object.values(g.s.teams))<4)g.s.teams[v]++;if(k==='clear')g.s.teams={welcome:0,garden:0};if(k==='open')need(g,g.s.teams.welcome>=(g.q.crowd>3?2:1)&&g.s.teams.garden>=2,'Both jobs need enough people. Clear the plan to reassign helpers.','Welcoming and planting can happen together.');else g.scene()}),
 phase('repair','prioritise','An unexpected problem','The entrance light has a loose wire. Make the event safe.',()=>icon('tools',300,122,62)+cards(['Keep people away','Call trained adult','Children repair it'],'safe',g.s.selected,181),()=>btn('Put plan into action','act'),(k,v)=>{if(k==='safe')toggle(g,'selected',v);if(k==='act')need(g,g.s.selected.length===2&&g.s.selected.includes('Keep people away')&&g.s.selected.includes('Call trained adult'),'Choose two actions: protect visitors and get the right adult help.','Children report the danger; trained adults repair electrical equipment.')}),
 phase('followup','schedule','Tomorrow matters too','Festival finished! Choose a plan that keeps the saplings alive.',()=>tree(165,165,1)+words(418,113,'Your planting team needs a continuing job.',21,23)+cards(['Watering rota + checks','One photo, then leave'],'plan',[],243),null,choose(g,null,'plan','Watering rota + checks','Care continues after a celebration.','Planting is only the beginning. Think about what the sapling needs tomorrow.'))
 ],()=>`Community mission complete: services, teamwork, safe repairs and continuing care.`);
};
function personScene(s){return icon('walk',90,143,58)+words(340,113,s,29,24)}

F.park=g=>{g.q={dry:pick(g,[true,false]),blocked:I(g,1,3),species:pick(g,['neem','amaltas','jamun'])};g.s.site=-1;g.s.cleaned=[];g.s.water=0;g.s.days=[];
 journey(g,[
 phase('plant-site','spatial-plan','Find room to grow',()=>`Choose a ${g.q.species} planting site with space, away from the path.`,()=>line([280,67],[280,303],'#d8bd8f',45)+[0,1,2].map((n)=>hit(['Open soil','On the path','Under a wire'][n],'site',n,rect(55+n*180,135,135,111,g.s.site===n?'#bbdca7':'#fff9')+icon(n===0?'seed':n===1?'walk':'tools',122+n*180,179,34)+words(122+n*180,217,['Open soil','Footpath','Low wire'][n],13,18))).join(''),()=>btn('Plant here','plant'),(k,v)=>{if(k==='site'){g.s.site=+v;g.scene()}if(k==='plant')need(g,g.s.site===0,'Roots and branches need room. Keep the walking route and wires clear.','The sapling has growing space and the path stays open.')}),
 phase('cleanup','sort-materials','Restore the space','Send each material to a useful destination.',()=>tree(480,100,.7)+cards(['Dry leaves','Plastic wrapper'],'waste',g.s.cleaned,102)+cards(['Compost pile','Litter bin'],'destination',[],226)+text(300,199,g.s.waste?'Holding: '+g.s.waste:'Select a material first',19),null,(k,v)=>{if(k==='waste'&&!g.s.cleaned.includes(v)){g.s.waste=v;g.scene()}if(k==='destination'&&g.s.waste){if(v!==(g.s.waste==='Dry leaves'?'Compost pile':'Litter bin')){g.say('Leaves can compost. Plastic does not belong in that pile.');return}g.s.cleaned.push(g.s.waste);g.s.waste=null;if(g.s.cleaned.length===2)g.advance('Organic leaves and plastic need different destinations.');else g.scene()}}),
 phase('soil','measure-respond','Read the soil',()=>`Soil check: ${g.q.dry?'dry below the surface':'already damp after rain'}. Choose today’s care.`,()=>tree(300,130,1.2)+rect(164,260,273,31,g.q.dry?'#c6a16e':'#856c55')+icon(g.q.dry?'sun':'water',100,110,46)+text(300,325,g.q.dry?'Dry soil':'Damp soil',22),()=>choices(['Water the soil','Wait; check tomorrow'],'soil'),choose(g,null,'soil',g.q.dry?'Water the soil':'Wait; check tomorrow','Care changes with what you observe.','Use the soil evidence. A damp plant does not need automatic extra watering.')),
 phase('access','route-repair','Make room for everyone','A fallen branch blocks the path. Reopen a safe route.',()=>routeSVG(g,g.s.pos??0,24,[g.q.blocked,12],{24:'park'}),compass,(k,v)=>{if(k==='walk'&&move(g,v,[g.q.blocked,12])&&g.s.pos===24)g.advance('You found an open route and reported the fallen branch to an adult.');},()=>{g.s.pos=0})
 ],()=>`Park restored: suitable planting, sorted waste, soil-based care and an open route.`);
};

F.journey=g=>{g.q={goal:pick(g,[4,9,14,19,24]),landmark:pick(g,['Library','Health centre','Market']),block:pick(g,[6,7,8,11,12,13]),parcel:pick(g,[true,false])};g.s.pos=20;g.s.transport='';
 journey(g,[
 phase('mode','compare-options','Plan a real journey',()=>`Reach the ${g.q.landmark.toLowerCase()}: it is 1 km away on a safe footpath.`,()=>panel('Choose with a reason','An adult can accompany you. No heavy bags.','walk')+cards(['Walk: no fuel','Bus: several stops','Car: needs parking'],'transport',[],258),null,(k,v)=>{if(k!=='transport')return;if(v!=='Walk: no fuel'){g.say('All can move people, but which uses no fuel and suits this short, safe trip?');return}g.s.transport=v;g.advance('For this short safe route, walking uses no vehicle fuel.')}),
 phase('navigate','grid-navigation','Use directions',()=>`Walk to ★ ${g.q.landmark}. Grey streets are closed.`,()=>routeSVG(g,g.s.pos,g.q.goal,[g.q.block]),compass,(k,v)=>{if(k==='walk'&&move(g,v,[g.q.block])&&g.s.pos===g.q.goal)g.advance('North, south, east and west helped you navigate around a closure.')}),
 phase('message','communication','Tell someone you arrived',()=>g.q.parcel?'Send a paper invitation to a relative in another town.':'Tell family immediately that you arrived; they have a phone.',()=>icon(g.q.parcel?'letter':'phone',300,125,63)+cards(['Post the letter','Phone call','Wait for a visit'],'send',[],208),null,choose(g,null,'send',g.q.parcel?'Post the letter':'Phone call','Choose communication for its purpose, not just because it is newer.','A physical letter needs delivery. An immediate spoken update can use a phone.')),
 phase('directions','map-recall','Give a useful landmark',()=>`A friend starts at the ${g.q.landmark}. Describe the way to the bus stop.`,()=>routeSVG(g,g.q.goal,g.q.goal<20?g.q.goal+5:g.q.goal-5,[],{[g.q.goal]:'star',[g.q.goal<20?g.q.goal+5:g.q.goal-5]:'bus'})+text(87,220,'★ You',19),()=>choices(['One street north','One street south'],'direction'),choose(g,null,'direction',g.q.goal<20?'One street south':'One street north','A landmark plus a direction makes a useful instruction.','North is up on this map. Compare the two neighbouring rows.'))
 ],()=>`Journey complete: transport, navigation, communication and a clear return instruction.`);
};

F.savings=g=>{g.q={cash:I(g,8,12)*10,book:I(g,2,4)*10,pencil:10,goal:20+10*g.level};g.q.cash=Math.max(g.q.cash,g.q.book+g.q.pencil+g.q.goal);g.s.cart=[];g.s.deposit=0;g.s.bank=0;g.s.withdraw=0;
 journey(g,[
 phase('shop','budget-build','Needs before extras',()=>`Wallet ₹${g.q.cash}. Buy a notebook and pencil; keep ₹${g.q.goal} to save.`,()=>icon('money',300,94,43)+text(300,141,'Basket ₹'+sum(g.s.cart.map(i=>[g.q.book,10,40][i])),27)+cards([{label:'Notebook ₹'+g.q.book,value:0},{label:'Pencil ₹10',value:1},{label:'Toy ₹40',value:2}],'buy',g.s.cart,183)+text(300,310,'Cash left ₹'+(g.q.cash-sum(g.s.cart.map(i=>[g.q.book,10,40][i]))),24),()=>btn('Pay for basket','pay'),(k,v)=>{if(k==='buy')toggle(g,'cart',+v);if(k==='pay'){let spent=sum(g.s.cart.map(i=>[g.q.book,10,40][i]));if(need(g,g.s.cart.includes(0)&&g.s.cart.includes(1)&&g.q.cash-spent>=g.q.goal,'Cover both needs and keep enough for your savings goal. You can remove an item.','Your basket covers the needs without spending the savings.'))g.s.left=g.q.cash-spent}}),
 phase('deposit','bank-transfer','Make the money trail',()=>`Move at least ₹${g.q.goal} from your wallet into the pretend bank.`,()=>building('Bank account','bank',435,133,170)+icon('money',151,132,63)+text(151,224,'Wallet ₹'+(g.q.cash-sum(g.s.cart.map(i=>[g.q.book,10,40][i]))-g.s.deposit),23)+text(435,284,'Account ₹'+g.s.deposit,23),()=>btn('Deposit ₹10','deposit',10,true)+btn('Return ₹10','deposit',-10,true)+btn('Save plan','bank'),(k,v)=>{if(k==='deposit'){let left=g.q.cash-sum(g.s.cart.map(i=>[g.q.book,10,40][i]));g.s.deposit=Math.max(0,Math.min(left,g.s.deposit+Number(v)));g.scene()}if(k==='bank'){g.s.bank=g.s.deposit;need(g,g.s.deposit>=g.q.goal,'Move enough existing money into the account to meet your goal.','A deposit moves money; it does not create extra money.')}}),
 phase('atm','conservation','An ATM request','You need ₹10 from the account. Predict the new bank balance.',()=>panel('Withdraw ₹10','The ATM gives money from your account.','bank')+cards(shuffled(g,[g.s.bank-10,g.s.bank,g.s.bank+10]).map(n=>({label:'₹'+n,value:n})),'balance',[],259),null,choose(g,null,'balance',()=>g.s.bank-10,'The account decreases by the amount withdrawn.','A withdrawal takes money out of an account; subtract ₹10.')),
 phase('surprise','tradeoff','A new need appears','Your pencil breaks. Choose a plan that avoids an unnecessary purchase.',()=>icon('pencil',300,114,70)+cards(['Use the spare at home','Buy a whole new set','Discard all stationery'],'respond',[],192)+words(300,315,'A spare pencil is available at home.',42,18),null,choose(g,null,'respond','Use the spare at home','Checking what you already have helps use resources wisely.','You have a usable spare. Which choice solves the problem with no extra spending?'))
 ],()=>`Budget keeper: needs paid, money tracked and a resource-saving decision made.`);
};

// A free stroke is measured as evidence, never compared with a decorative dotted outline.
function enableInk(g,onChange){g.drawingGame=true;g.mode='doodle';g.s.ink=[];g.pointer=(x,y,type)=>{if(!g.inkActive||g.done)return;if(type==='start'){g.s.ink=[[x,y]];g.onInkStart?.();}if(type==='move')g.s.ink.push([x,y]);if(type==='cancel')g.s.ink=[];if(type==='end'){g.s.ink.push([x,y]);onChange?.(g.s.ink)}g.scene()}}
const ink=(g,color='#805b9f')=>g.s.ink.length>1?`<polyline points="${g.s.ink.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>`:'';
F.observe=g=>{g.q={legs:pick(g,[6,8]),leaf:pick(g,['parallel','branching']),animal:pick(g,['bee','butterfly']),offset:I(g,-30,30)};g.s.lens=false;g.s.count=0;g.s.veins=[];enableInk(g,path=>{if(g.s.phase!==2)return;let a=path[0],b=path.at(-1);if(path.length>2&&Math.hypot(b[0]-a[0],b[1]-a[1])>45&&path.every(p=>p[0]>335&&p[0]<530&&p[1]>96&&p[1]<293)){g.s.veins.push(path);g.s.ink=[]}else g.feedback='Draw a clear vein inside the right leaf.'});
 const leaf=(x,reference)=>poly([[x,95],[x+74,151],[x+74,231],[x,291],[x-73,231],[x-73,151]],'#b4d58e')+line([x,112],[x,279],'#628452',4)+(reference?(g.q.leaf==='parallel'?[-31,31].map(d=>line([x+d,137],[x+d,253],'#628452',3)).join(''):[-1,1].map(d=>[157,212].map(y=>line([x,y+28],[x+d*55,y],'#628452',3)).join('')).join('')):'');
 journey(g,[
 phase('inspect','magnify-count','Be a field observer','Use the magnifier. Count legs before deciding what you found.',()=>dot(300,170,g.s.lens?79:43,'#ead09a')+Array.from({length:g.q.legs},(_,i)=>{let side=i%2?-1:1,y=135+Math.floor(i/2)*22;return line([300+side*25,y],[300+side*(g.s.lens?119:66),y-17],C[2],g.s.lens?7:3)}).join('')+text(300,311,g.s.lens?'Count legs, not antennae.':'Look more closely.',21),()=>btn('Magnifier','lens','',true)+choices([6,8].map(v=>({label:v+' legs',value:v})),'legs'),(k,v)=>{if(k==='lens'){g.s.lens=true;g.scene()}if(k==='legs')need(g,g.s.lens&&+v===g.q.legs,'Magnify first, then count the legs on both sides.','Observation: '+g.q.legs+' legs.')}),
 phase('classify','evidence-classify','Use your evidence','Which group fits your leg count?',()=>icon(g.q.legs===6?g.q.animal:'spider',300,121,71)+text(300,170,'Field note: '+g.q.legs+' legs',24)+cards(['Insect','Spider (not an insect)'],'group',[],223),null,choose(g,null,'group',g.q.legs===6?'Insect':'Spider (not an insect)','Features help us classify; appearance alone can mislead.','Insects have six legs. A spider has eight.')),
 phase('leaf-sketch','observational-drawing','Record a leaf feature','Sketch two veins in the notebook to show the observed pattern.',()=>text(171,78,'Observed leaf',20)+text(431,78,'Your notebook',20)+leaf(170,true)+leaf(430,false)+g.s.veins.map(p=>`<polyline points="${p.map(a=>a.join(',')).join(' ')}" fill="none" stroke="#6c8750" stroke-width="4"/>`).join('')+ink(g)+text(300,331,'Draw on the right, or use the accessible vein tools.',16),()=>btn('Add parallel vein','vein','parallel',true)+btn('Add branch','vein','branching',true)+btn('Clear','erase','',true)+btn('Save sketch','sketch'),(k,v)=>{if(k==='vein'){let d=g.s.veins.length%2?-1:1;g.s.veins.push(v==='parallel'?[[430+d*28,137],[430+d*28,250]]:[[430,237],[430+d*54,169]]);g.scene()}if(k==='erase'){g.s.veins=[];g.s.ink=[];g.scene()}if(k==='sketch'){let okay=g.s.veins.filter(p=>{let a=p[0],b=p.at(-1);return g.q.leaf==='parallel'?Math.abs(a[0]-b[0])<20&&p.every(q=>Math.abs(q[0]-a[0])<22):Math.abs(a[0]-b[0])>35&&Math.min(Math.abs(a[0]-430),Math.abs(b[0]-430))<20}).length>=2;need(g,okay,'Compare the real leaf: parallel veins run alongside; branches spread from a main vein.','Your sketch records a feature rather than collecting or damaging the plant.')}},()=>{g.inkActive=true}),
 phase('habitat','field-decision','Leave the habitat safe','You want to observe the animal again tomorrow. Make a field plan.',()=>tree(165,140,.95)+icon(g.q.legs===6?g.q.animal:'spider',388,155,70)+cards(['Watch quietly; leave it here','Take it home in a closed jar'],'plan',[],238),null,choose(g,null,'plan','Watch quietly; leave it here','Observe without disturbing food, shelter or the animal.','The animal needs its habitat. Observation does not require taking it home.'),()=>{g.inkActive=false})
 ],()=>`Field journal saved: a counted feature, an evidence-based group and a leaf sketch.`);
};

F.web=g=>{g.q={place:pick(g,['school garden','village grove','park edge']),removed:pick(g,['Flowers','Tree'])};g.s.link=0;g.s.links=[];g.s.support=[];
 const nodes=['Sun','Plant','Flowers','Bee','Tree','Bird'],pairs=[[0,1],[2,3],[4,5]],coords=[[95,97],[300,97],[95,191],[300,191],[95,285],[300,285]];
 journey(g,[
 phase('connections','network-link','Build a living network',()=>`At the ${g.q.place}, connect light, food and shelter.`,()=>nodes.map((n,i)=>hit(n,'node',i,dot(...coords[i],39,g.s.link===i?'#f3c58c':'#e3efcc')+words(coords[i][0],coords[i][1]+6,n,12,18))).join('')+g.s.links.map(i=>line(coords[pairs[i][0]],coords[pairs[i][1]],'#7fa47c',5)).join('')+words(476,129,['Sun → light','Flowers → nectar','Tree → shelter'].join(' / '),15,19),null,(k,v)=>{if(k!=='node')return;const n=+v;if(n%2===0){g.s.link=n;g.scene();return}const pair=pairs.findIndex(p=>p[0]===g.s.link&&p[1]===n);if(pair<0){g.say('Use the kind of connection: light, nectar food or nesting shelter.');return}if(!g.s.links.includes(pair))g.s.links.push(pair);if(g.s.links.length===3)g.advance('The network includes light, food and shelter; not every link means eating.');else g.scene()}),
 phase('disturbance','predict-consequence','One part is lost',()=>`${g.q.removed} are removed. Which animal directly loses this resource?`,()=>icon(g.q.removed==='Flowers'?'flower':'tree',168,142,70)+text(168,195,'Removed',23)+line([230,153],[370,153],'#bd7672',5)+cards(['Bee: nectar food','Bird: nesting shelter'],'loss',[],231),null,choose(g,null,'loss',g.q.removed==='Flowers'?'Bee: nectar food':'Bird: nesting shelter','A change in one part affects a connected living thing.','Follow the link that starts at the removed resource.')),
 phase('restore','resource-plan','Repair the broken connection','Spend two care tokens on a plan that restores food or shelter.',()=>icon(g.q.removed==='Flowers'?'bee':'bird',300,109,64)+cards(g.q.removed==='Flowers'?['Grow suitable flowers','Keep a patch unsprayed','Put plastic flowers']:['Protect nesting tree','Plant future shelter','Remove every branch'],'support',g.s.support,170)+count('Care tokens used',g.s.support.length,2),()=>btn('Try restoration','restore'),(k,v)=>{if(k==='support')toggle(g,'support',v);if(k==='restore')need(g,g.s.support.length===2&&(g.q.removed==='Flowers'?g.s.support.includes('Grow suitable flowers')&&g.s.support.includes('Keep a patch unsprayed'):g.s.support.includes('Protect nesting tree')&&g.s.support.includes('Plant future shelter')),'Choose two actions that provide the missing living resource.','The plan restores habitat; recovery takes time.')}),
 phase('follow-evidence','interpret-observation','Check after a few weeks','The journal shows more visits after care. What can you conclude?',()=>[2,3,6].map((n,i)=>rect(110+i*155,285-n*25,92,n*25,C[i])+text(156+i*155,314,['Before','Week 1','Week 3'][i],17)+text(156+i*155,276-n*25,n+' visits',19)).join(''),()=>choices(['Visits increased in this journal','All animals are now safe forever'],'claim'),choose(g,null,'claim','Visits increased in this journal','Use the evidence you have, without claiming more than it shows.','The counts show visits here. They cannot prove every animal is safe forever.'))
 ],()=>`Nature network repaired: you traced a cause, chose care and checked the evidence.`);
};

S.missionTools={journey,phase,choose,need,toggle,cards,panel,numberControl,adjust,enableInk,ink,shuffled,compass,routeSVG,move};
})();
