'use strict';
(() => {
const S=SAFARI,F=S.constructors,{text,line,rect,dot,poly,hit,btn,choices,I,pick,C}=S.art;
const {words,icon}=S.scienceArt;
const {journey,phase,choose,need,toggle,cards,panel,enableInk,ink,shuffled}=S.missionTools;

F.spinner=g=>{g.q={offset:pick(g,[-55,-40,40,55]),shape:pick(g,['circle','square','triangle']),colour:pick(g,C),stem:I(g,2,4)};g.s.pivot=g.q.offset;g.s.trials=[];g.s.angle=0;g.s.spinning=false;
 const wobble=p=>Math.round(Math.abs(p)/8);
 const top=()=>`<g transform="translate(300 174) rotate(${g.s.angle})">`+(g.q.shape==='circle'?dot(0,0,90,g.q.colour):g.q.shape==='square'?rect(-80,-80,160,160,g.q.colour):poly([[0,-95],[-88,64],[88,64]],g.q.colour))+line([-78,0],[78,0],'#fff8',4)+line([0,-77],[0,77],'#fff8',4)+dot(g.s.pivot,0,12,'#476659')+'</g>'+text(300,308,'Pivot offset '+g.s.pivot+' · same shape, stem and push',18);
 const spin=()=>{g.s.spinning=true;g.api.animate(900,t=>{g.s.angle=t*720;g.scene()},()=>{g.s.spinning=false;g.s.trials.push({pivot:g.s.pivot,wobble:wobble(g.s.pivot)});g.refresh()})};
 journey(g,[
 phase('predict','hypothesis','Predict before spinning','The stem is away from the centre. Predict what you may observe.',()=>top(),()=>choices(['More wobble','Less wobble'],'predict'),(k,v)=>{if(k==='predict'){g.s.prediction=v;g.advance('Prediction recorded: '+v+'. A test may change your mind.')}}),
 phase('baseline','experiment','Test the first spinner','Spin it once and observe the wobble meter.',()=>top()+text(300,76,g.s.trials.length?'Observed wobble: '+g.s.trials[0].wobble:'Ready for first test',23),()=>btn('Spin this top','spin')+(g.s.trials.length?btn('Keep observation','record'):''),(k)=>{if(k==='spin'&&!g.s.spinning&&!g.s.trials.length)spin();if(k==='record')need(g,g.s.trials.length===1,'Spin before recording an observation.','First test: off-centre stem, wobble '+g.s.trials[0]?.wobble+'.')}),
 phase('change-one','design-adjust','Change just one thing','Move the stem towards the centre. Keep shape and push unchanged.',()=>top(),()=>btn('Stem ←','pivot',-10,true)+btn('Stem →','pivot',10,true)+btn('Use this design','design'),(k,v)=>{if(k==='pivot'){g.s.pivot=Math.max(-65,Math.min(65,g.s.pivot+(+v)));g.scene()}if(k==='design')need(g,Math.abs(g.s.pivot)<Math.abs(g.q.offset),'Move the stem closer to the centre so the second test compares a real change.','Only the stem position changed; the comparison is fair.')}),
 phase('compare-test','comparative-experiment','Test and compare','Spin the new design, then compare both observations.',()=>top()+(g.s.trials.length===2?text(300,76,'Wobble '+g.s.trials[0].wobble+' → '+g.s.trials[1].wobble,24):''),()=>btn('Test new design','spin')+(g.s.trials.length===2?btn('Open evidence','evidence'):''),(k)=>{if(k==='spin'&&!g.s.spinning&&g.s.trials.length===1)spin();if(k==='evidence')need(g,g.s.trials.length===2,'Test the changed design first.','The model recorded both trials, including your original prediction.')}),
 phase('explain','evidence-claim','Choose what the test supports','What changed when the stem moved closer to the centre?',()=>g.s.trials.map((t,i)=>rect(130+i*235,278-t.wobble*24,103,t.wobble*24+3,C[i])+text(180+i*235,309,i?'After':'Before',20)+text(180+i*235,250-t.wobble*24,t.wobble+' wobble',21)).join(''),()=>choices(['Less wobble in this model','Changing the material caused it'],'claim'),choose(g,null,'claim','Less wobble in this model','A model supports a comparison, not an exact prediction for every real toy.','Compare the two wobble readings. Real results also depend on the push, surface and construction.'))
 ],()=>`Investigation complete: prediction → two fair trials → an evidence-based conclusion.`);
};

F['boat-pen']=g=>{g.q={load:I(g,3,4)+g.level,wind:pick(g,['left','right']),harbour:pick(g,['School pond','Lotus bay','Village tank'])};g.s.hull=null;g.s.load=[0,0];g.s.trials=[];g.s.width=180;g.s.depth=70;g.s.observed=false;
 const capacity=(w,d)=>Math.max(1,Math.floor(w/65)+Math.floor(d/50));
 const measure=path=>{if(path.length<3)return null;let a=path[0],b=path.at(-1),xs=path.map(p=>p[0]),ys=path.map(p=>p[1]),width=Math.max(...xs)-Math.min(...xs),rim=(a[1]+b[1])/2,depth=Math.max(...ys)-rim,dir=Math.sign(b[0]-a[0]);let backtrack=0,length=0;for(let i=1;i<path.length;i++){const dx=path[i][0]-path[i-1][0];backtrack+=Math.max(0,-dx*dir);length+=Math.hypot(dx,path[i][1]-path[i-1][1])}return width>=100&&width<=400&&depth>=35&&depth<=145&&Math.abs(a[1]-b[1])<35&&Math.abs(a[0]-b[0])>width*.75&&backtrack<width*.18&&length<3*(width+depth)&&path.every(p=>p[0]>=85&&p[0]<=515&&p[1]>=Math.max(90,rim-18)&&p[1]<=295)?{width,depth,points:path}:null};
 enableInk(g,path=>{const m=measure(path);if(m){g.s.hull=m;g.s.width=m.width;g.s.depth=m.depth;g.feedback='Hull saved. Its width and depth will affect the model load test.'}else{g.s.hull=null;g.feedback='Draw an open U: two ends near the same height, a lower base, all inside the tank.'}g.refresh()});
 g.onInkStart=()=>{g.s.hull=null};
 const hullPoints=()=>[[300-g.s.width/2,140],[300-g.s.width/2+25,140+g.s.depth],[300+g.s.width/2-25,140+g.s.depth],[300+g.s.width/2,140]];
 const makeHull=()=>{g.s.hull={width:g.s.width,depth:g.s.depth,points:hullPoints()};g.s.ink=g.s.hull.points;g.scene()};
 const result=()=>{const total=g.s.load[0]+g.s.load[1],balance=Math.abs(g.s.load[0]-g.s.load[1])<=1;return{capacity:capacity(g.s.width,g.s.depth),total,balance,afloat:balance&&total<=capacity(g.s.width,g.s.depth)}};
 const tank=(draw=false)=>rect(77,84,446,213,'#c7e0dd88')+rect(77,211,446,86,'#9fcdd699')+line([82,211],[518,211],'#72adb8',3)+`<g transform="translate(0 ${g.s.observed?(result().afloat?4:35)*(g.s.motion??1):0}) rotate(${g.s.observed&&!result().balance?(g.s.load[0]>g.s.load[1]?-10:10)*(g.s.motion??1):0} 300 211)">`+(g.s.hull?`<polyline points="${g.s.hull.points.map(p=>p.join(',')).join(' ')}" fill="#ecd6a999" stroke="#8e7b60" stroke-width="5"/>`:draw?words(300,126,'Draw an open U-shaped hull here',33,20):'')+(!g.s.hull?ink(g):'')+[0,1].map(side=>Array.from({length:g.s.load[side]},(_,i)=>rect(232+side*97+i%2*22,190-Math.floor(i/2)*24,19,19,'#9c82be')).join('')).join('')+'</g>'+text(300,328,g.s.observed?(result().afloat?'Trial: afloat':'Trial: tipped or too low in water'):'Illustrative model • not a real load forecast',17);
 const drawControls=()=>btn('Narrower','width',-40,true)+btn('Wider','width',40,true)+btn('Make U / clear pen','template','',true)+btn('Use hull','hull');
 const drawAction=(k,v)=>{if(k==='width'){g.s.width=Math.max(120,Math.min(380,g.s.width+(+v)));makeHull()}if(k==='template')makeHull();if(k==='hull')need(g,!!g.s.hull,'Draw a usable U-shaped hull, or build one with the shape controls.','The drawing is now a boat design that can be tested.');};
 journey(g,[
 phase('material','predict-material','Foil can change shape',()=>`${g.q.harbour}: can the same foil behave differently as a cup?`,()=>icon('boat',425,142,67)+dot(160,139,35,'#a7b5b4')+words(160,213,'Compact foil ball',18,22)+words(425,213,'Hollow foil cup',18,22)+text(300,310,'Same foil material • different shape',21),()=>choices(['Yes, shape may change floating','No, material is all that matters'],'predict'),(k,v)=>{if(k==='predict'){g.s.prediction=v;g.advance('Prediction saved. Build a hollow hull and investigate; predictions are not scored.')}}),
 phase('draw-hull','design-drawing','Your drawing becomes the model','Draw a U-shaped hull. Its width and depth will matter in the test.',()=>tank(true),drawControls,drawAction,()=>{g.inkActive=true}),
 phase('load-test','load-experiment','Load and test your design',()=>`Deliver ${g.q.load} cargo blocks. Spread the load and test the boat.`,()=>tank()+text(300,67,'Cargo '+(g.s.load[0]+g.s.load[1])+' / '+g.q.load,22),()=>btn('+ Left','load',0,true)+btn('+ Right','load',1,true)+btn('Unload','unload','',true)+btn('Test boat','test')+(g.s.observed?btn('Inspect result','inspect'):''),(k,v)=>{if(k==='load'&&g.s.load[0]+g.s.load[1]<g.q.load){g.s.load[+v]++;g.s.observed=false;g.refresh()}if(k==='unload'){g.s.load=[0,0];g.s.observed=false;g.refresh()}if(k==='test'){if(g.s.load[0]+g.s.load[1]!==g.q.load){g.say('Put the requested cargo aboard before testing.');return}g.s.observed=true;g.s.trials=[{...result(),width:g.s.width,depth:g.s.depth}];g.api.animate(650,t=>{g.s.motion=t;g.scene()},()=>{g.s.motion=1;g.refresh()})}if(k==='inspect')need(g,g.s.observed,'Test the loaded boat first.','Test recorded, whether the boat floated or failed.');},()=>{g.inkActive=false}),
 phase('diagnose','evidence-diagnosis','Read the result before changing',()=>g.s.trials[0].afloat?'Your boat floated. What feature helped?':'Use the trial to find what needs attention.',()=>tank()+cards(g.s.trials[0].afloat?['Hollow hull + balanced load','Only weight decides floating']:!g.s.trials[0].balance?['Load is too one-sided','The foil material changed']:['Hull capacity is too small','Material alone decides floating'],'diagnose',[],256),null,(k,v)=>{if(k==='diagnose'){const correct=g.s.trials[0].afloat?'Hollow hull + balanced load':!g.s.trials[0].balance?'Load is too one-sided':'Hull capacity is too small';if(v!==correct){g.say('Use the visible load and the result you actually observed.');return}g.advance('Choose a wider hull and balanced cargo for the next harbour challenge.')}}),
 phase('improve','redesign-transfer','Improve and deliver',()=>`Now carry ${g.q.load+1} blocks. Widen the hull; keep the same foil material.`,()=>tank()+text(300,67,'New cargo '+(g.q.load+1)+' · model capacity '+capacity(g.s.width,g.s.depth),21),()=>btn('Widen hull','widen','',true)+btn('Balance cargo','balance','',true)+btn('Launch delivery','launch'),(k)=>{if(k==='widen'){g.s.width=Math.min(380,g.s.width+40);g.s.depth=100;makeHull();g.s.observed=false;g.refresh()}if(k==='balance'){g.s.load=[Math.floor((g.q.load+1)/2),Math.ceil((g.q.load+1)/2)];g.s.observed=false;g.refresh()}if(k==='launch'){g.s.observed=true;g.s.trials.push(result());need(g,g.s.load[0]+g.s.load[1]===g.q.load+1&&result().afloat,'Check the new cargo, widen the hollow hull and spread blocks across both sides.','The revised design passed the new model challenge.');}})
 ],()=>`Delivery made! Your hull, load test, diagnosis and redesign produced a working model.`);
};

F.paper=g=>{g.q={scraps:I(g,3,5),pigment:pick(g,[['Turmeric','#e9bf52'],['Beetroot','#c27691'],['Spinach','#87af76']]),use:pick(g,['greeting card','bookmark','gift tag'])};g.s.scraps=[];g.s.water=0;g.s.pulp=false;g.s.cells=[];g.s.pressed=false;g.s.dry=false;g.s.policy=[];
 journey(g,[
 phase('collect','resource-selection','Start with existing paper',()=>`Make a ${g.q.use}. Collect ${g.q.scraps} used-paper scraps.`,()=>Array.from({length:g.q.scraps+1},(_,i)=>hit(i===g.q.scraps?'New notebook':'Used scrap '+(i+1),'scrap',i,rect(82+i%3*180,95+Math.floor(i/3)*103,128,81,g.s.scraps.includes(i)?'#c1d99e':i===g.q.scraps?'#ccbddf':'#fff9')+words(146+i%3*180,133+Math.floor(i/3)*103,i===g.q.scraps?'New notebook':'Used scrap',15,21))).join(''),()=>btn('Shred collected paper','shred'),(k,v)=>{if(k==='scrap')toggle(g,'scraps',+v);if(k==='shred')need(g,g.s.scraps.length===g.q.scraps&&!g.s.scraps.includes(g.q.scraps),'Collect the available used scraps; keep the new notebook for its intended use.','Used paper can become raw material for a new sheet.')}),
 phase('pulp','material-transformation','Loosen the fibres','Add water to soak the scraps, then mash the softened paper.',()=>rect(113,132,374,150,g.s.pulp?'#bdbda5':g.s.water?'#a7ced3':'#eee1bc')+Array.from({length:g.s.pulp?35:12},(_,i)=>rect(137+i%7*47,164+Math.floor(i/7)*19,g.s.pulp?18:32,g.s.pulp?5:14,'#fff9')).join('')+text(300, ninety(),g.s.pulp?'Wet pulp: loosened fibres':g.s.water?'Scraps soaking':'Dry torn scraps',24),()=>btn('Add water / soak','soak','',true)+btn('Mash softened scraps','mash','',true)+btn('Use the pulp','pulp'),(k)=>{if(k==='soak'){g.s.water=1;g.scene()}if(k==='mash'){if(!g.s.water){g.say('Soak the scraps to soften them before mashing.');return}g.s.pulp=true;g.scene()}if(k==='pulp')need(g,g.s.pulp,'Soak and mash before spreading a sheet.','Dry pieces became a wet mixture of fibres.')}),
 phase('spread','coverage-design','Make an even sheet','Spread pulp into every tray patch; avoid a hole in your sheet.',()=>Array.from({length:6},(_,i)=>hit('Tray patch '+(i+1),'patch',i,rect(147+i%3*103,100+Math.floor(i/3)*101,96,94,g.s.cells.includes(i)?'#bbc4a5':'#fff7',`stroke="#adba9c" stroke-width="2"`)+text(195+i%3*103,156+Math.floor(i/3)*101,g.s.cells.includes(i)?'Fibres':'Empty',18))).join(''),()=>btn('Lift the sheet','lift'),(k,v)=>{if(k==='patch'&&!g.s.cells.includes(+v)){g.s.cells.push(+v);g.scene()}if(k==='lift')need(g,g.s.cells.length===6,'Cover every patch so the new sheet has no intended hole.','An even spread joins fibres across the sheet.')}),
 phase('finish','process-sequence','Remove water and finish',()=>`Press, dry, then colour your ${g.q.use} with ${g.q.pigment[0].toLowerCase()}.`,()=>rect(119,112,362,170,g.s.coloured?g.q.pigment[1]:g.s.dry?'#e6dfb9':'#b9c5b4')+words(300,160,g.s.coloured?'Ready to make a '+g.q.use:g.s.dry?'Dry sheet':g.s.pressed?'Pressed: less water':'Wet sheet',30,25)+text(300,317,'Hand and machine methods both process fibres.',17),()=>btn('Press','press','',true)+btn('Allow to dry','dry','',true)+btn('Add plant colour','colour'),(k)=>{if(k==='press'){g.s.pressed=true;g.scene()}if(k==='dry'){if(!g.s.pressed){g.say('Press out excess water before drying in this process.');return}g.s.dry=true;g.scene()}if(k==='colour'){if(!g.s.dry){g.say('Finish drying the sheet before decorating it.');return}g.s.coloured=true;g.advance('Making paper uses water, energy and effort. Reuse suitable sheets before recycling.')}})
 ],()=>`Your ${g.q.use} sheet is ready: collected, pulped, spread, pressed, dried and coloured.`);
};
function ninety(){return 88}

F['paper-test']=g=>{g.q={job:pick(g,['Mop a small spill','Support a model roof']),water:I(g,2,4),reuse:pick(g,[true,false])};g.s.size=[1,2];g.s.drops=[g.q.water,g.q.water+1];g.s.tested=[];g.s.readings=[];g.s.choice='';g.s.actions=[];
 const samples=['Tissue','Writing paper','Cardboard'],absorb=[5,2,1],strength=[1,3,5];
 journey(g,[
 phase('fair-test','variable-control','Set up a fair comparison',()=>`Job: ${g.q.job.toLowerCase()}. Match sample size and test-water amount.`,()=>[0,1].map(i=>rect(123+i*236,111,70+g.s.size[i]*22,95+g.s.size[i]*15,'#fff9')+text(178+i*236,266,'Size '+g.s.size[i]+' · '+g.s.drops[i]+' drops',20)).join('')+text(300,320,'Change the paper type, not the test conditions.',17),()=>btn('Match sample sizes','size','',true)+btn('Match water amounts','drops','',true)+btn('Begin fair test','begin'),(k)=>{if(k==='size'){g.s.size[1]=g.s.size[0];g.scene()}if(k==='drops'){g.s.drops[1]=g.s.drops[0];g.scene()}if(k==='begin')need(g,g.s.size[0]===g.s.size[1]&&g.s.drops[0]===g.s.drops[1],'Both sample sizes and water amounts must match.','Only paper type varies in this comparison.')}),
 phase('measure','test-samples','Collect comparison evidence','Test the three papers. Watch the property readings appear.',()=>samples.map((s,i)=>hit('Test '+s,'test',i,rect(60+i*183,94,157,109,i===2?'#ccaf86':'#fff9')+words(138+i*183,136,s,15,22)+(g.s.tested.includes(i)?text(138+i*183,185,'Tested ✓',19):text(138+i*183,185,'Tap to test',17)))).join('')+g.s.tested.map(i=>text(300,235+g.s.tested.indexOf(i)*31,samples[i]+': absorbs '+absorb[i]+' · support '+strength[i],20)).join(''),()=>btn('Compare the results','compare'),(k,v)=>{if(k==='test'&&!g.s.tested.includes(+v)){g.s.tested.push(+v);g.scene()}if(k==='compare')need(g,g.s.tested.length===3,'Test each paper before choosing from the evidence.','These relative model scores describe one set of samples, not every brand.')}),
 phase('choose-use','data-application','Choose paper for a purpose',()=>`Use the results to ${g.q.job.toLowerCase()}. Higher scores mean more of the property.`,()=>samples.map((s,i)=>text(120+i*180,87,s,18)+rect(94+i*180,270-(g.q.job.startsWith('Mop')?absorb[i]:strength[i])*31,52,(g.q.job.startsWith('Mop')?absorb[i]:strength[i])*31,C[i])+text(120+i*180,306,g.q.job.startsWith('Mop')?absorb[i]:strength[i],23)).join(''),()=>choices(samples,'paper'),choose(g,null,'paper',g.q.job.startsWith('Mop')?'Tissue':'Cardboard','The best choice depends on the job and the tested property.','Use absorbency for a spill and support for the model roof.')),
 phase('resource','repair-repurpose','Give leftovers another life','Choose a useful action for each leftover. Tap an item, then its new plan.',()=>cards(['Blank-backed sheet','Torn paper scraps','Loose book cover'],'item',g.s.actions,91)+cards(['Use the other side','Make new pulp','Repair the cover'],'reuse',[],228)+text(300,193,g.s.item||'Choose an item.',19),null,(k,v)=>{if(k==='item'&&!g.s.actions.includes(v)){g.s.item=v;g.scene()}if(k==='reuse'&&g.s.item){const plans={'Blank-backed sheet':'Use the other side','Torn paper scraps':'Make new pulp','Loose book cover':'Repair the cover'};if(plans[g.s.item]!==v){g.say('Keep useful items in use; recycle scraps and repair the cover.');return}g.s.actions.push(g.s.item);g.s.item=null;if(g.s.actions.length===3)g.advance('Reuse, recycling and repair are different actions. Refuse and reduce can avoid waste before it starts.');else g.scene()}})
 ],()=>`Materials scientist: you controlled conditions, compared evidence and conserved resources.`);
};
})();
