'use strict';
(() => {
const S=SAFARI,F=S.constructors,{text,line,rect,dot,poly,hit,btn,choices,I,pick,C}=S.art;
const {words,icon,tree,moon,phases}=S.scienceArt;
const {journey,phase,choose,need,toggle,cards,panel,enableInk,ink,shuffled}=S.missionTools;
const regions=[{name:'Sikkim mountains',land:'Mountains',feature:'High, steep land',roof:'Sloping roof',story:'Loosong / Namsoong celebrations',work:'Many farms, crafts and other jobs',cold:true},{name:'Punjab plains',land:'Plains',feature:'Broad, mostly level land',roof:'Rain drainage',story:'Langar: people share a meal',work:'Farming is one of many livelihoods',cold:false},{name:'Rajasthan desert',land:'Desert',feature:'Very little rainfall',roof:'Water storage',story:'Bandhani: tie-dye craft',work:'Crafts, farming and many other jobs',cold:false},{name:'Odisha coast',land:'Coast',feature:'Land meets the sea',roof:'Storm preparation',story:'Puri: art, food and coastal stories',work:'Fishing is one of many livelihoods',cold:false}];
function landscape(r){if(r.land==='Mountains')return poly([[45,290],[177,75],[279,232],[380,98],[557,290]],'#98b5a1')+poly([[144,128],[177,75],[208,128]],'#f6f4e5');if(r.land==='Coast')return rect(38,164,526,130,'#a9cfd6')+poly([[38,133],[233,147],[308,221],[205,294],[38,294]],'#e0c994');if(r.land==='Desert')return poly([[40,235],[145,152],[272,233],[409,160],[561,260],[561,295],[40,295]],'#ddbd7e')+icon('sun',444,104,47);return rect(39,188,522,109,'#b4cb87')+[0,1,2].map(i=>line([70,226+i*25],[530,216+i*25],'#809c62',3)).join('')+tree(465,125,.6)}
F.lands=g=>{g.q={region:pick(g,regions),clueOrder:I(g,0,2)};g.s.features=[];g.s.plan=[];g.s.roof=0;
 journey(g,[
 phase('land-observe','field-survey','Read a landscape',()=>`Explore the travel sketch. Select its defining feature.`,()=>landscape(g.q.region)+cards(shuffled(g,[g.q.region.feature,...regions.filter(r=>r!==g.q.region).map(r=>r.feature).slice(0,2)]),'feature',[],269),null,choose(g,null,'feature',g.q.region.feature,'A landform clue comes from the landscape, not from assumptions about its people.','Look at height, slope, dryness or the boundary with the sea.')),
 phase('home-adapt','build-response','A home responds to place',()=>`${g.q.region.name}: choose a useful local design response.`,()=>landscape(g.q.region)+rect(194,154,194,128,'#e4d0a3')+(g.s.roof?poly([[174,154],[291,89],[407,154]],'#b4906b'):rect(180,141,223,17,'#ac987d'))+text(300,326,g.s.selected||'Plan a response to the setting.',20),()=>choices([g.q.region.roof,...['Sloping roof','Water storage','Storm preparation','Rain drainage'].filter(s=>s!==g.q.region.roof).slice(0,1)],'design')+btn('Try the plan','build'),(k,v)=>{if(k==='design'){g.s.selected=v;g.s.roof=v==='Sloping roof'?1:0;g.scene()}if(k==='build')need(g,g.s.selected===g.q.region.roof,'Consider the important local condition: mountain rain, scarce water, coastal storms or drainage.','People adapt homes and services to conditions; no single design describes all homes.')}),
 phase('weather-event','emergency-planning','Conditions can change','A heavy-rain warning interrupts the trip. Choose two sensible actions.',()=>icon('umbrella',300,114,61)+cards(['Follow local adult guidance','Move plans to a safe place','Visit a flooded road'],'safety',g.s.plan,182),()=>btn('Update our trip','update'),(k,v)=>{if(k==='safety')toggle(g,'plan',v);if(k==='update')need(g,g.s.plan.length===2&&g.s.plan.includes('Follow local adult guidance')&&g.s.plan.includes('Move plans to a safe place'),'Respond to the actual warning instead of relying on the region’s usual climate.','Today’s weather can differ from a region’s usual conditions.')}),
 phase('postcard','edit-claim','Write a respectful postcard',()=>`Your ${g.q.region.name} postcard must describe an example without stereotyping.`,()=>rect(75,83,450,178,'#fffaf0')+words(300,126,g.q.region.story,34,23)+words(300,200,g.q.region.work,37,20)+cards(['This is one local example','Everyone here lives identically'],'caption',[],276),null,choose(g,null,'caption','This is one local example','Regions contain many ways of living. A travel story is one example.','A postcard cannot describe every person in a region.'))
 ],()=>`Travel journal completed with landscape evidence, adaptation, safety and respect.`);
};

F.pack=g=>{g.q={cold:pick(g,[true,false]),rainLater:pick(g,[true,false]),destination:pick(g,['a hill walk','a coastal visit','a village trip']),supply:I(g,2,4)};g.s.bag=[];g.s.shared=0;g.s.alert=[];
 const items=['Water bottle',g.q.cold?'Warm layer':'Sun hat','Raincoat','Toy telescope'];
 journey(g,[
 phase('pack','limited-space','Pack for the actual forecast',()=>`${g.q.cold?'Cold and dry':'Warm and sunny'} ${g.q.destination}. Pack two essentials; leave one space spare.`,()=>icon('box',300,108,62)+cards(items,'bag',g.s.bag,167)+countBag(g.s.bag.length,3),()=>btn('Begin trip','depart'),(k,v)=>{if(k==='bag')toggle(g,'bag',v);if(k==='depart')need(g,g.s.bag.length===2&&g.s.bag.includes(items[0])&&g.s.bag.includes(items[1]),'Use the stated weather: take water and the useful clothing item; keep space for changing needs.','Weather evidence guided the first packing decision.')}),
 phase('forecast-change','adapt-kit','A forecast update arrives','Rain is now expected. Use the spare space without losing your essentials.',()=>icon('umbrella',300,118,67)+g.s.bag.map((s,i)=>rect(48+i*182,197,169,72,'#fff9')+words(132+i*182,229,s,16,20)).join('')+text(300,315,g.s.bag.includes('Raincoat')?'Rain protection added':'One spare space remains',21),()=>btn('Add raincoat','rain')+btn('Check new bag','ready'),(k)=>{if(k==='rain'&&!g.s.bag.includes('Raincoat')){g.s.bag.push('Raincoat');g.scene()}if(k==='ready')need(g,g.s.bag.includes('Raincoat')&&g.s.bag.includes('Water bottle'),'Keep the existing essentials and add rain protection.','Packing is a plan that can change with a reliable forecast.')}),
 phase('share','cooperative-distribution','Prepare together',()=>`${g.q.supply} companions need route cards. Share one with each person.`,()=>Array.from({length:g.q.supply},(_,i)=>hit('Give route card to companion '+(i+1),'share',i,dot(100+i*400/(g.q.supply-1),152,39,(g.s.given||[]).includes(i)?'#bad7a0':'#eac9a9')+icon('walk',100+i*400/(g.q.supply-1),157,41)+text(100+i*400/(g.q.supply-1),232,(g.s.given||[]).includes(i)?'Card ✓':'Waiting',18))).join(''),()=>btn('Check group','group'),(k,v)=>{g.s.given??=[];if(k==='share'&&!g.s.given.includes(+v)){g.s.given.push(+v);g.scene()}if(k==='group')need(g,g.s.given.length===g.q.supply,'Give each companion the same important route information.','A shared plan helps the group stay together.')}),
 phase('local-knowledge','information-quality','Listen before exploring','A local guide warns that the beach path is closed. Build your response.',()=>cards(['Follow the open marked route','Ask the adult guide for help','Ignore the closure for a photo'],'response',g.s.alert,155)+text(300,325,'Respect local knowledge and current safety guidance.',17),()=>btn('Set our route plan','finish'),(k,v)=>{if(k==='response')toggle(g,'alert',v);if(k==='finish')need(g,g.s.alert.length===2&&!g.s.alert.includes('Ignore the closure for a photo'),'Choose both a safe route and help from the guide.','A beautiful location can still have temporary hazards.')} )
 ],()=>`Weather-wise trip ready: a flexible bag, informed companions and a safe local plan.`);
};
function countBag(n,total){return text(300,340,'Bag spaces '+n+' / '+total,18)}

F.shadows=g=>{g.q={side:pick(g,[-1,1]),height:pick(g,[70,115]),place:pick(g,['school yard','park','terrace'])};g.s.lightX=300+g.q.side*120;g.s.lightY=g.q.height;g.s.prediction=null;g.s.reveal=false;g.s.picnic=300;
 const shadowTip=()=>300+(300-g.s.lightX)*80/(260-g.s.lightY-80);
 enableInk(g,p=>{if(p.length<2||Math.hypot(p[0][0]-300,p[0][1]-260)>30||Math.abs(p.at(-1)[1]-260)>32||Math.abs(p.at(-1)[0]-300)<30){g.s.prediction=null;g.feedback='Start at the pole’s foot and draw your prediction along the ground.'}else g.s.prediction=p.at(-1)[0];g.refresh()});
 const scene=()=>line([60,264],[540,264],'#9bb580',7)+(g.s.reveal?line([300,260],[shadowTip(),260],'#727b7f',14):'')+line([300,260],[300,180],'#b0825d',12)+icon('sun',g.s.lightX,g.s.lightY,42)+line([g.s.lightX,g.s.lightY],[300,180],'#e5b957',2,'stroke-dasharray="7 7"')+ink(g)+text(300,322,'A side-view model • never look directly at the Sun',16);
 journey(g,[
 phase('draw-prediction','prediction-drawing','Predict a shadow',()=>`At the ${g.q.place}, draw the shadow you expect from the pole’s foot.`,scene,()=>btn('Predict left','predict',-1,true)+btn('Predict right','predict',1,true)+btn('Shine the light','shine'),(k,v)=>{if(k==='predict'){g.s.prediction=300+(+v)*125;g.s.ink=[[300,260],[g.s.prediction,260]];g.scene()}if(k==='shine'){if(!g.s.prediction){g.say('Draw or choose a direction first. Predictions are welcome even when they change.');return}g.s.reveal=true;g.advance('Your prediction is purple; the model observation is grey. Compare them.');}},()=>{g.inkActive=true}),
 phase('compare','observation-judgment','Compare prediction and observation','Where did the observed shadow form relative to the light?',scene,()=>choices(['Away from the light','Towards the light'],'relation'),choose(g,null,'relation','Away from the light','The pole blocks light; the shadow extends on the opposite side.','Look at the grey shadow and the Sun icon, not only at your prediction.'),()=>{g.inkActive=false}),
 phase('height-test','variable-experiment','Change the light height','Move the light higher to shorten the shadow. Keep the pole unchanged.',()=>scene()+text(300,77,'Model shadow length '+Math.round(Math.abs(shadowTip()-300)),21),()=>btn('Light higher','height',-15,true)+btn('Light lower','height',15,true)+btn('Keep shorter shadow','keep'),(k,v)=>{if(k==='height'){g.s.lightY=Math.max(50,Math.min(135,g.s.lightY+(+v)));g.s.ink=[];g.scene()}if(k==='keep')need(g,g.s.lightY<g.q.height,'Raise the source above its original height; watch the shadow shorten.','A higher light made this ground shadow shorter.')}),
 phase('shade-transfer','spatial-application','Use the shadow in a new task','Move the picnic marker into the pole’s model shadow.',()=>scene()+icon('fruit',g.s.picnic,239,32)+text(300,110,'Use the grey shaded ground.',20),()=>btn('Picnic ←','picnic',-20,true)+btn('Picnic →','picnic',20,true)+btn('Check shade','shade'),(k,v)=>{if(k==='picnic'){g.s.picnic=Math.max(80,Math.min(520,g.s.picnic+(+v)));g.scene()}if(k==='shade'){const t=shadowTip();need(g,g.s.picnic>Math.min(t,300)+5&&g.s.picnic<Math.max(t,300)-5,'Put the marker between the pole and the shadow tip.','As the Sun’s apparent position changes, a shaded place can change too.');}})
 ],()=>`Shadow notebook complete: prediction, observation, a fair change and a shade decision.`);
};

F.moon=g=>{g.q={start:pick(g,[0,2,4,6]),observer:pick(g,['Mira','Kabir','Tara']),turn:pick(g,[0,180])};g.s.phaseIndex=(g.q.start+3)%8;g.s.days=0;g.s.earth=g.q.turn;g.s.mission=[];
 journey(g,[
 phase('sky-observation','visual-comparison','Open the sky journal',()=>`${g.q.observer} sketched this Moon. Turn the wheel to match the lit part.`,()=>rect(52,65,496,243,'#2c4658')+moon(g.q.start,170,175,63)+moon(g.s.phaseIndex,432,175,63)+text(170,281,'Observed',19,'#fff2c8')+text(432,281,'Your wheel',19,'#fff2c8'),()=>btn('← Earlier','wheel',-1,true)+btn('Later →','wheel',1,true)+btn('Record match','match'),(k,v)=>{if(k==='wheel'){g.s.phaseIndex=(g.s.phaseIndex+(+v)+8)%8;g.scene()}if(k==='match')need(g,g.s.phaseIndex===g.q.start,'Match the side and amount of the lit area. The dark part of the Moon is still there.','Journal: '+phases[g.q.start]+'. The Moon reflects sunlight.')}),
 phase('calendar','temporal-prediction','Predict the next observation','About a week later, which picture belongs next in the model cycle?',()=>moon(g.q.start,300,122,49)+[0,1,2].map((_,i)=>{const p=(g.q.start+[2,4,6][i])%8;return hit('Moon option '+(i+1),'nextphase',p,rect(54+i*183,202,154,110,'#2c4658')+moon(p,131+i*183,252,39))}).join(''),null,choose(g,null,'nextphase',(g.q.start+2)%8,'About a week moves roughly a quarter of the way through the phase cycle. Exact dates vary.','In this model, about a week advances two of the eight phase pictures.')),
 phase('day-night','rotation-model','A different sky change','Turn Earth until the marked home faces away from the Sun.',()=>icon('sun',93,169,62)+line([134,153],[252,153],'#e2bc62',3)+line([134,189],[252,189],'#e2bc62',3)+dot(342,176,90,'#79aeb6')+`<path d="M342 86 A90 90 0 0 1 342 266Z" fill="#354e68"/>`+icon('school',342+Math.cos(g.s.earth*Math.PI/180)*70,185+Math.sin(g.s.earth*Math.PI/180)*70,29)+text(300,320,'Earth turns; different places face sunlight.',18),()=>btn('Turn Earth','rotate','',true)+btn('Record nighttime','night'),(k)=>{if(k==='rotate'){g.s.earth=(g.s.earth+45)%360;g.scene()}if(k==='night')need(g,Math.cos(g.s.earth*Math.PI/180)>.5,'The Sun is on the left. Put the marked home on the right, facing away from it.','Earth’s rotation changes day and night. Stars remain present in daylight.')}),
 phase('moon-reason','explain-mechanism','Keep the two ideas separate','What explains ordinary Moon phases?',()=>moon(3,172,169,76)+moon(5,425,169,76)+cards(['Different views of the sunlit half','Earth’s shadow every night'],'reason',[],277),null,choose(g,null,'reason','Different views of the sunlit half','Ordinary phases are not Earth’s shadow; that is involved in a lunar eclipse.','The Moon keeps its round shape and reflects sunlight as it travels around Earth.')),
 phase('lunar-mission','event-timeline','Chandrayaan mission journal','Build the journey: launch, travel into lunar orbit, then land.',()=>cards(['Lunar orbit','Launch','Vikram lands'],'event',g.s.mission,122)+words(300,257,g.s.mission.join(' → ')||'Which event must happen first?',40,21)+text(300,330,'Chandrayaan-3 landing: 23 August 2023',18),null,(k,v)=>{if(k!=='event')return;const order=['Launch','Lunar orbit','Vikram lands'];if(v!==order[g.s.mission.length]){g.say('A spacecraft launches from Earth before reaching the Moon and landing.');return}g.s.mission.push(v);if(g.s.mission.length===3)g.advance('Vikram landed and Pragyan explored. A mission timeline is different from a phase calendar.');else g.scene()})
 ],()=>`Sky journal complete: phase observation, a calendar prediction, Earth’s turn and a lunar mission.`);
};
})();
