'use strict';
window.SAFARI = {};
SAFARI.worlds = [
  {name:'Shape island',subtitle:'Build it. Bend it. Find what changes.',color:'#d8edc9'},
  {name:'Angle town',subtitle:'Meet the corners hiding all around you.',color:'#ffe3ba'},
  {name:'Discovery garden',subtitle:'Take your angles into the real world.',color:'#dcebcf'},
  {name:'Measure mountain',subtitle:'Aim, estimate and make your best discovery.',color:'#dfe4fb'}
];
SAFARI.topics = [
  {id:'loops',name:'Loop Lagoon',concept:'Open & closed shapes',tag:'CONNECT & BUILD',color:'#d8efdf',pages:'16–17, 19, 27',learn:'A shape closes when its last side joins its first. Count the straight sides and the corners separately.',example:'A closed 6-sided shape has 6 corners. Two 6-sided shapes can still look different.',hint:'Tap different pegs to add sides. To close your shape, tap the first peg again. Avoid crossing sides.',why:'Every new segment adds a side. Joining back to the first peg closes the boundary.',home:'Make a closed shape with a piece of string, then make an opening.'},
  {id:'shifter',name:'Jelly Joint',concept:'Same sides, new angles',tag:'SQUISH & MATCH',color:'#fce2c8',pages:'17, 19, 26–27',learn:'Moving a joint changes the angle between two sides. Four sticks can make many shapes while keeping their lengths.',example:'A square can lean into a rhombus: the same 4 rods, different corner angles.',hint:'Slide or drag the top joint until your solid shape sits on the dotted outline.',why:'The rods keep the same lengths, but their openings change. Side count alone does not describe a shape.',home:'Join 4 equal card strips with split pins. Push gently and watch the corners.'},
  {id:'match',name:'Angle Twins',concept:'Compare & match angles',tag:'SPOT THE TWIN',color:'#e8dff7',pages:'17–18, 20',learn:'An angle measures an opening. Turning the whole picture or changing the arm lengths does not change that opening.',example:'A small drawing of a right angle and a large one both measure 90°.',hint:'Look between the two arms, not at their lengths. The curved mark shows the opening to compare.',why:'Matching angles have the same opening even if they face different directions.',home:'Make an angle tester from two card strips. Compare corners around your room.'},
  {id:'sticks',name:'Stick Studio',concept:'Matchstick puzzles',tag:'PICK & REBUILD',color:'#f9e9aa',pages:'19, 29',learn:'A stick can belong to more than one triangle. Moving only a few sticks can change a whole picture.',example:'Two overlapping triangles made from 6 sticks contain 8 triangles: 6 little ones and 2 large ones.',hint:'Tap an orange stick, then an empty dashed place. Keep the green sticks where they are.',why:'Reusing shared edges and changing the positions of a few sticks creates a new arrangement.',home:'Try the fish and house puzzles using craft sticks. Use the outlines here to check.'},
  {id:'tester',name:'Angle Inspector',concept:'Use an angle tester',tag:'OPEN & COMPARE',color:'#d3ecf3',pages:'20–21',learn:'An angle tester has two arms joined at a pivot. Match both arms to an object’s sides to compare their opening.',example:'A book corner matches an L-shaped opening: a right angle.',hint:'Move the tester arm to cover the pale target arm. The pivot and the first arm already line up.',why:'When both arms lie along the target sides, the tester copies that angle.',home:'Use two card strips joined with a paper fastener to test a pencil-box corner.'},
  {id:'painter',name:'Corner Carnival',concept:'Less, equal or more than 90°',tag:'PICK A PAINT',color:'#ffdfd4',pages:'21–23',learn:'An acute angle is smaller than a right angle. An obtuse angle is larger than a right angle and smaller than a straight angle.',example:'45° is acute, 90° is right, and 120° is obtuse. Follow the marked opening.',hint:'Pick a paint label, then tap a marked corner. Use the little square as the right-angle reference.',why:'Comparing each opening with an L-shaped corner tells us its angle family.',home:'Find and sketch one example of each angle family in your classroom.'},
  {id:'fold',name:'Fold & Fly',concept:'Angles in paper folds',tag:'FOLD & DISCOVER',color:'#d4ebf9',pages:'23, 31–32',learn:'Folding makes creases that meet at angles. Folding a right angle exactly in half makes two 45° angles.',example:'Paper-plane folds include 45° and 90° angles. Other creases can make 135°.',hint:'Tap Fold to make the creases. Then choose the marked opening requested in the mission.',why:'The half-fold splits the opening evenly: 90° ÷ 2 = 45°. A right angle plus 45° makes 135°.',home:'Fold a square into a paper aeroplane. Open it and look for 45° and 90° corners.'},
  {id:'yoga',name:'Robot Yoga',concept:'Angles with the body',tag:'POSE & BALANCE',color:'#e7ddfb',pages:'23, 33',learn:'Two parts of an arm or leg meet at a joint. Their opening can be smaller than, equal to, or larger than a right angle.',example:'A bent elbow can show a right angle. Opening it wider makes an obtuse angle.',hint:'Move the glowing hand or the slider. Measure the marked opening at the elbow.',why:'The elbow is the vertex. Its two arm segments are the sides of the angle.',home:'Sketch stick figures showing different arm angles; label the marked openings.'},
  {id:'garden',name:'Bee Line',concept:'Angles in the garden',tag:'AIM & POLLINATE',color:'#e5efc3',pages:'24–25',learn:'Angles appear between branches, in an open beak and between directions. A bee can communicate a direction using an angle.',example:'A narrow beak makes an acute angle. The wider opening between two branches is the larger angle.',hint:'Turn the dotted flight path toward the flower, then send the bee. The sun ray is the starting direction.',why:'The marked angle compares the flower direction with the fixed sun direction.',home:'Find leaf veins and twigs. Draw the openings you can see between them.'},
  {id:'names',name:'Letter Detectives',concept:'Angles in names',tag:'FIND THE CORNERS',color:'#fce0d3',pages:'25',learn:'Straight-line letters contain angles where their strokes meet. Look carefully at which opening is marked.',example:'L has a right-angle corner. V has an acute opening. The drawing style matters.',hint:'Only the circled, marked corners count in this game. Tap every one in the requested family.',why:'Letters are made from line segments. Their marked openings can be compared with a right angle.',home:'Write 3 names using straight strokes. Mark and count the different angle families.'},
  {id:'ramps',name:'Ramp Racers',concept:'Steepness & angles',tag:'BUILD & RACE',color:'#ffe7b5',pages:'25–26',learn:'A ramp with a larger angle to the ground is steeper. In the same ideal conditions, a ball speeds up more on the steeper ramp.',example:'Use the same ramp length and the same ball. Change just the angle for a fair comparison.',hint:'Adjust your ramp to the mission. Race both equal-length ramps and observe which ball reaches the end first.',why:'The steeper ramp gives a larger pull along the slope. This simple model uses equal friction-free ramps.',home:'Compare a book ramp on 6 books and on 10 books. Keep the ramp and ball the same.'},
  {id:'towers',name:'Bridge Builders',concept:'Triangles make frames rigid',tag:'BRACE & TEST',color:'#d1e9e5',pages:'26–28',learn:'A triangle with fixed side lengths cannot change its angles without bending or stretching a side. A four-sided frame with loose joints can lean.',example:'A diagonal brace splits a four-sided frame into two triangles and stops the joints from folding.',hint:'Add one diagonal to each unbraced bay. Then test your bridge against the wind.',why:'Triangular bracing fixes the shape of each bay in this ideal pin-jointed model.',home:'Look for triangular braces in bridges, gates and towers near you.'},
  {id:'clock',name:'Tick Tock Trail',concept:'Clock hands & angles',tag:'TURN BACK TIME',color:'#ecddfa',pages:'28–29',learn:'Both clock hands start at the same centre. The smaller opening between them can be acute, right, obtuse, straight or zero.',example:'At 3:00 and 9:00 the smaller angle is 90°. At 6:00 it is 180°. The hour hand moves between numbers.',hint:'Move the time control to match the mission. Compare the smaller marked opening between the hands.',why:'The minute hand turns 6° each minute; the hour hand turns 0.5° each minute. Their difference gives the opening.',home:'Find a time with an acute angle, a right angle and an obtuse angle on a clock.'},
  {id:'carrom',name:'Carrom Comets',concept:'Equal angles in a rebound',tag:'AIM & REBOUND',color:'#f8dfba',pages:'30',learn:'In an ideal bounce off a straight edge, the incoming and outgoing paths make equal angles with the edge.',example:'A steep approach leaves at a steep angle. Changing your aim changes where the striker goes.',hint:'Set where the striker meets the top cushion. Imagine an equally slanting path on the other side.',why:'The top wall reverses the vertical part of the motion. The two angles at the bounce are equal.',home:'Draw a rebound path with a ruler. Compare the incoming and outgoing angles using a protractor.'},
  {id:'degrees',name:'Degree Orbit',concept:'Degree clock & measurement',tag:'ROTATE & DOCK',color:'#dce3fa',pages:'30–32',learn:'Degrees measure a turn. A right angle is 90°, half a right angle is 45°, and two right angles make a straight angle of 180°.',example:'One-third of a right angle is 30°. A full turn is 360°.',hint:'Start at the zero ray and turn anticlockwise. Use the slider, plus/minus buttons or the movable hand.',why:'A degree clock compares a turn with a full circle divided into 360 equal parts.',home:'Fold a paper circle into halves, quarters and eighths. Mark 180°, 90° and 45°.'},
  {id:'doodle',name:'The Doodle D Game',concept:'Estimate, then measure',tag:'GUESS & REVEAL',color:'#f9edc5',pages:'33',learn:'First estimate an angle. Then use the D-shaped protractor to measure it. The difference is your error score: smaller is better.',example:'Guess 65° for a 70° angle: the error is 5°. Start reading from the zero on the base ray.',hint:'Compare with 45°, 90° and 180°. Make your guess before revealing the protractor.',why:'The error is the positive difference between the guess and the measured angle. Practice makes estimates more precise.',home:'Draw angles for a friend to guess, measure them, and add the error scores. Lowest total wins.'}
];
SAFARI.util = {
  rng(seed){let x=seed>>>0;return ()=>{x+=0x6D2B79F5;let t=Math.imul(x^x>>>15,1|x);t^=t+Math.imul(t^t>>>7,61|t);return ((t^t>>>14)>>>0)/4294967296}},
  pick(r,a){return a[Math.floor(r()*a.length)]},
  shuffle(r,a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},
  pt(x,y,a,l){return [x+Math.cos(a*Math.PI/180)*l,y-Math.sin(a*Math.PI/180)*l]},
  type(a){return a===0?'Zero':a===90?'Right':a===180?'Straight':a<90?'Acute':a<180?'Obtuse':'Reflex'},
  distance(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1])},
  clockAngle(minutes){let d=Math.abs((minutes%60)*6-(minutes/2)%360);return Math.min(d,360-d)},
  fmtTime(t){return `${Math.floor(t/60)%12||12}:${String(t%60).padStart(2,'0')}`},
  angleDiff(a,b){let d=((a-b)%360+360)%360;return Math.min(d,360-d)},
  escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
};
