'use strict';
(() => {
const S=SAFARI,U=S.util,A=S.art,P=U.pt;
const {svg,txt,line,circle,angle,wedge,face,flower,btn,button,pointsPoly}=A;
const supported=['loops','tester','painter','fold','yoga','garden','towers','clock','degrees','doodle'];
const names={loops:'Pencil Polygons',tester:'Copy a Corner',painter:'Sketch an Angle',fold:'Crease Sketcher',yoga:'Pose Pencil',garden:'Garden Sketches',towers:'Draw the Brace',clock:'Clock Sketcher',degrees:'Degree Sketcher',doodle:'The Doodle D Game'};
const ink=(ps,color='#536a65',width=5)=>`<polyline points="${pointsPoly(ps)}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linejoin="round" stroke-linecap="round"/>`;
const direction=(a,b)=>(Math.atan2(a[1]-b[1],b[0]-a[0])*180/Math.PI+360)%360;
const edgeDistance=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1];return Math.abs(dy*p[0]-dx*p[1]+b[0]*a[1]-b[1]*a[0])/Math.max(1,U.distance(a,b));};
function straight(ps){if(ps.length<2)return false;const a=ps[0],b=ps.at(-1),length=U.distance(a,b);return length>=32&&ps.every(p=>edgeDistance(p,a,b)<=Math.max(16,length*.1))&&ps.reduce((s,p,i)=>s+(i?U.distance(ps[i-1],p):0),0)<length*1.55+20;}
function endpointMatch(ps,target,tol=29){const a=ps[0],b=ps.at(-1);return (U.distance(a,target.a)<tol&&U.distance(b,target.b)<tol)||(U.distance(b,target.a)<tol&&U.distance(a,target.b)<tol);}
function rayMatch(ps,target){let [a,b]=[ps[0],ps.at(-1)];if(U.distance(b,target.a)<U.distance(a,target.a))[a,b]=[b,a];const length=U.distance(target.a,b);return U.distance(a,target.a)<=30&&length>=(target.minLength||65)&&length<=(target.maxLength||205)&&U.angleDiff(direction(target.a,b),direction(target.a,target.b))<=7;}
function prepare(g){g.mode='doodle';g.title=names[g.id];g.drawingGame=true;g.pointerOnTargets=true;g.q.targets=[];g.s={accepted:[],strokes:[],active:[],mistake:[],input:'draw',tapStart:null};g.hint='Draw a fairly straight stroke between the correct points. Lift your finger after each line. Tap ends gives a keyboard-friendly alternative.';
 g.accept=(target,stroke)=>{if(g.s.accepted.includes(target.id))return;g.s.accepted.push(target.id);g.s.strokes.push({id:target.id,points:stroke});g.s.mistake=[];g.scene();g.api.tell(`${g.s.accepted.length} / ${g.q.targets.length} lines in place. ${g.s.accepted.length===g.q.targets.length?'Check your sketch when ready.':'Draw the next line.'}`);};
 g.recognize=ps=>{if(!straight(ps)){g.s.mistake=ps;g.say('Try a straighter line. Begin and end near the correct points.');g.scene();return}const target=g.q.targets.find(t=>!g.s.accepted.includes(t.id)&&(t.ray?rayMatch(ps,t):endpointMatch(ps,t)));if(target){g.accept(target,ps)}else{g.s.mistake=ps;g.say(g.retry||'That line does not match yet. Check the starting point and the opening.');g.scene()}};
 g.pointer=(x,y,phase)=>{if(g.s.input!=='draw')return;if(phase==='start'){g.s.active=[[x,y]];g.s.mistake=[]}else if(phase==='move'&&g.s.active.length){if(g.s.active.length<600&&U.distance(g.s.active.at(-1),[x,y])>1)g.s.active.push([x,y])}else if(phase==='end'&&g.s.active.length){g.s.active.push([x,y]);const stroke=g.s.active;g.s.active=[];g.recognize(stroke)}else if(phase==='cancel')g.s.active=[];g.scene()};
 g.action=(k,v)=>{if(k==='input-mode'){g.s.input=g.s.input==='draw'?'tap':'draw';g.s.tapStart=null;g.s.active=[];g.refresh();return}if(k==='undo'){const removed=g.s.accepted.pop();g.s.strokes=g.s.strokes.filter(s=>s.id!==removed);g.s.mistake=[];g.refresh();return}if(k==='anchor'&&g.s.input==='tap'){const p=g.anchors[+v];if(g.s.tapStart){g.recognize([g.s.tapStart,p]);g.s.tapStart=null}else{g.s.tapStart=p;g.scene()}return}if(k==='check'){if(g.s.accepted.length===g.q.targets.length)g.success(g.explanation);else g.say(`Your sketch still needs ${g.q.targets.length-g.s.accepted.length} line${g.q.targets.length-g.s.accepted.length===1?'':'s'}. ${g.hint}`)}};
 g.controls=()=>btn('↶ Undo','undo','','secondary')+btn(g.s.input==='draw'?'Tap ends':'✎ Draw','input-mode','','secondary')+btn(g.checkLabel||'Check sketch','check');
 g.ink=()=>g.s.strokes.map(s=>ink(s.points,'#edb67c',3)).join('')+g.q.targets.filter(t=>g.s.accepted.includes(t.id)).map(t=>line(t.a,t.b,t.color||'#437d6a',6)).join('')+(g.s.mistake.length?ink(g.s.mistake,'#d48073',3):'')+(g.s.active.length?ink(g.s.active,'#68584e',5):'');
 g.dots=()=>g.anchors.map((p,i)=>button(`Drawing point ${i+1}`,'anchor',i,circle(...p,g.s.input==='tap'?27:17,'transparent')+circle(...p,g.s.tapStart&&U.distance(g.s.tapStart,p)<1?11:7,'#fff8d4',`stroke="#80968a" stroke-width="2"`)+(g.s.input==='tap'?txt(p[0],p[1]-14,i+1,12):''))).join('');
 g.caption=()=>txt(300,341,g.s.input==='draw'?'Draw with your finger · lift after each line':'Tap the start, then the end of each line',14,'#796c53');
 return g;
}
function rayAnchors(origin,base,target,radius){const angles=[0,30,60,90,120,150,180,target].map(v=>((base+v)%360+360)%360);return [origin,...[...new Set(angles)].map(a=>P(...origin,a,radius))];}
function loops(g){const q=g.q,originalCheck=g.action;prepare(g);g.q=q;g.s.path=[];g.anchors=q.points;g.prompt=`Draw ${q.closed?'a closed':'an open'} shape with ${q.n} straight sides.`;g.hint='Draw from one numbered peg to another. Start each new stroke at the last peg; join your first peg only when you want to close the shape.';
 g.recognize=ps=>{if(!straight(ps)){g.say('Draw one straight side at a time, then lift your finger.');return}let from=g.anchors.findIndex(p=>U.distance(p,ps[0])<28),to=g.anchors.findIndex(p=>U.distance(p,ps.at(-1))<28);if(from<0||to<0||from===to){g.say('Join two different pegs with one stroke.');return}const path=g.s.path;if(path.length&&from!==path.at(-1)&&to===path.at(-1))[from,to]=[to,from];if(path.length&&from!==path.at(-1)){g.say('Continue from the last peg, so your sides form one path.');return}if(path.length>1&&path[0]===path.at(-1)){g.say('Your shape is closed. Check it or undo the last side.');return}if(path.includes(to)&&to!==path[0]){g.say('Use a new peg, or close the shape at your first peg.');return}if(!path.length)path.push(from);path.push(to);g.s.strokes.push({points:ps});g.scene();};
 const inherited=g.action;g.action=(k,v)=>{if(k==='check'){originalCheck('check');return}if(k==='undo'){if(g.s.path.length>1)g.s.path.pop();else g.s.path=[];g.s.strokes.pop();g.scene();return}inherited(k,v)};
 g.draw=()=>svg(`<path d="M105 22h390v296H105Z" fill="#fff9" stroke="#bbbe9e" stroke-width="2" stroke-dasharray="3 4"/>${g.s.path.length>3&&g.s.path[0]===g.s.path.at(-1)?`<polygon points="${pointsPoly(g.s.path.map(i=>q.points[i]))}" fill="#dce8b988"/>`:''}${g.s.strokes.map(s=>ink(s.points,'#ddab78',3)).join('')}${g.s.path.slice(1).map((p,i)=>line(q.points[g.s.path[i]],q.points[p],'#617e65',5)).join('')}${q.points.map((p,i)=>button(`Drawing point ${i+1}`,'anchor',i,circle(...p,28,'transparent')+circle(...p,12,'#fff4cf',`stroke="#7e927b" stroke-width="2"`)+txt(p[0],p[1]+5,i+1,14))).join('')}${g.s.active.length?ink(g.s.active):''}${txt(300,340,`${Math.max(0,g.s.path.length-1)} / ${q.n} sides · draw one side per stroke`,15)}`);
 g.doodleKey=JSON.stringify([q.n,q.closed,q.points]);return g;
}
function singleRay(g,kind){const old=g.q,target=old.target;prepare(g);g.q.target=target;g.q.origin=[300,250];g.q.base=0;g.q.context=kind;
 if(kind==='tester'){g.q.base=U.pick(g.r,[-15,0,15,30]);g.q.referenceAngle=U.pick(g.r,[-10,0,20,45])}
 if(kind==='painter'){g.q.target=U.pick(g.r,[30,45,60,90,110,125,150]);g.q.family=U.type(g.q.target);g.q.base=U.pick(g.r,[-20,0,20,40])}
 if(kind==='garden'){g.q.context=U.pick(g.r,['branch','beak','leaf']);g.q.base=U.pick(g.r,[0,15,30]);g.q.target=U.pick(g.r,g.q.context==='beak'?[25,35,45,55]:[30,45,60,90,110,125,140]);}
 if(kind==='degrees')g.q.target=U.pick(g.r,[30,45,60,90,120,135,150,180]);
 const q=g.q;q.targets=[{id:0,a:q.origin,b:P(...q.origin,q.base+q.target,145),ray:true}];g.anchors=rayAnchors(q.origin,q.base,q.target,145);
 g.prompt=kind==='tester'?'Draw an arm that copies the reference angle.':kind==='painter'?`Sketch ${q.family==='Acute'?'an acute':q.family==='Obtuse'?'an obtuse':'a right'} corner from the dot.`:kind==='garden'?`Draw the second ${q.context==='beak'?'beak edge':q.context==='leaf'?'leaf vein':'branch'} at ${q.target}°.`:`Draw a ray at ${q.target}° on the degree clock.`;
 g.hint=kind==='tester'?'Compare the little reference at the top. Draw from the big pivot to give your new angle the same opening.':kind==='painter'?'Start at the large dot and draw a second ray. Acute is below 90°, right is 90°, and obtuse lies between 90° and 180°.':'Draw from the large dot. Read the opening anticlockwise from the existing brown ray.';
 g.explanation=kind==='tester'?`Your copied opening matches ${q.target}°. Arm lengths can differ; the opening stays equal.`:kind==='painter'?`Your ${q.family.toLowerCase()} corner has the correct opening. The straight ray and your new stroke meet at one vertex.`:kind==='garden'?`This ${q.target}° opening is ${U.type(q.target).toLowerCase()}. Angles occur between branches, leaf veins and the edges of a beak.`:`The drawn ray snaps to ${q.target}°. The zero ray tells you where to start reading the degree scale.`;
 if(kind==='painter'){
  g.recognize=ps=>{if(!straight(ps)){g.say('Try one straight stroke from the dot.');return}let [a,b]=[ps[0],ps.at(-1)];if(U.distance(b,q.origin)<U.distance(a,q.origin))[a,b]=[b,a];const d=(direction(q.origin,b)-q.base+360)%360,rounded=Math.abs(d-90)<=7?90:d;
   if(U.distance(a,q.origin)>30||U.distance(q.origin,b)<70||U.distance(q.origin,b)>205||d>177||d<12||U.type(rounded)!==q.family){g.say(`Make a ${q.family.toLowerCase()} opening from the existing ray. A right angle looks like L.`);g.s.mistake=ps;g.scene();return}
   const t=q.targets[0];t.b=P(...q.origin,q.base+rounded,145);g.s.accepted=[];g.s.strokes=[];g.accept(t,ps);
  };
 }
 g.draw=()=>{let body='';if(kind==='tester')body+=angle(182,94,q.target,q.referenceAngle,58,'#8e856f')+txt(367,61,'REFERENCE OPENING',14,'#897458');
  if(kind==='degrees')body+=A.gauge(300,250,168);
  if(kind==='painter')body+=txt(300,52,`${q.family.toUpperCase()} ANGLE PAINT`,17,'#986d4f')+`<path d="M168 297q23 23 53 0m155 0q23 23 53 0" stroke="#b9d2b3" stroke-width="8" stroke-linecap="round" fill="none"/>`;
  if(kind==='garden'){if(q.context==='branch')body+=line([300,250],[300,318],'#9a8060',13)+flower(125,281,'#e0b496');if(q.context==='beak')body+=`<ellipse cx="260" cy="275" rx="52" ry="43" fill="#f3d98d" stroke="#a28d62" stroke-width="3"/>`+circle(273,263,4,'#665541');if(q.context==='leaf')body+=`<ellipse cx="300" cy="205" rx="170" ry="94" fill="#e6edb955" stroke="#a6b68d" stroke-width="2"/>`;body+=txt(300,45,`${q.context.toUpperCase()} SKETCH · ${q.target}°`,16,'#788953');}
  body+=line(q.origin,P(...q.origin,q.base,160),'#9d876c',6)+circle(...q.origin,12,'#f2d998',`stroke="#7c8061" stroke-width="3"`)+g.ink();if(g.s.input==='tap')body+=g.dots();return svg(body+g.caption());};
 g.doodleKey=JSON.stringify([q.context,q.target,q.family,q.base]);return g;
}
function fold(g){prepare(g);g.q.target=U.pick(g.r,[45,90]);g.q.rotation=U.pick(g.r,[-20,-10,0,10,20,30]);const rotate=([x,y])=>{const a=g.q.rotation*Math.PI/180;return [300+x*Math.cos(a)-y*Math.sin(a),180+x*Math.sin(a)+y*Math.cos(a)]};
 const ps=[[-103,-103],[103,-103],[103,103],[-103,103]].map(rotate);g.q.corners=ps;g.q.targets=[{id:0,a:g.q.target===45?ps[0]:rotate([-103,0]),b:g.q.target===45?ps[2]:rotate([103,0])}];g.anchors=[...ps,...[[-103,0],[103,0],[0,-103],[0,103]].map(rotate)];
 g.prompt=g.q.target===45?'Draw the crease that halves the top-left corner.':'Draw a crease at 90° to the dark paper edge.';g.hint=g.q.target===45?'Connect the two opposite corners. A square’s diagonal splits a 90° corner into two 45° openings.':'Connect the two side midpoints. The new crease must meet the dark side at a right angle.';g.explanation=g.q.target===45?'A diagonal fold splits the square’s 90° corner into two equal 45° angles.':'The crease meets the side at 90°. Rotating the paper does not change that opening.';
 g.draw=()=>svg(`<polygon points="${pointsPoly(ps)}" fill="#fffaf0" stroke="#a7a897" stroke-width="3"/>${line(ps[0],ps[3],'#9a785f',7)}${g.ink()}${g.dots()}${g.caption()}`);g.doodleKey=JSON.stringify([g.q.target,g.q.rotation]);return g;
}
function yoga(g){const target=U.pick(g.r,[30,45,60,90,110,120,135,150]);prepare(g);g.q.target=target;g.q.elbow=[343,191];g.q.targets=[{id:0,a:g.q.elbow,b:P(...g.q.elbow,180-target,104),ray:true,minLength:78,maxLength:145}];g.anchors=[g.q.elbow,...[30,45,60,90,110,120,135,150].map(a=>P(...g.q.elbow,180-a,104))];
 g.prompt=`Draw the missing forearm to make a ${target}° elbow.`;g.hint='The brown upper arm points left from the elbow. Draw a forearm that gives the marked opening its target size.';g.explanation=`Your drawn forearm makes a ${target}° ${U.type(target).toLowerCase()} elbow. The joint is the vertex, and the two arm parts are the angle’s arms.`;
 g.draw=()=>svg(`${line([236,234],[192,301],'#999485',12)}${line([257,234],[285,301],'#999485',12)}<rect x="218" y="155" width="64" height="91" rx="24" fill="#dcd4df" stroke="#8d8391" stroke-width="3"/>${face(250,114,30,'#ece0dc')}${line([223,180],[177,215],'#9b9297',12)}${line([268,191],g.q.elbow,'#a58a6b',12)}${circle(...g.q.elbow,12,'#ffe1a2',`stroke="#9d8865" stroke-width="3"`)}${wedge(...g.q.elbow,180-target,target,33,'#f2d59855','#c0a378')}${g.ink()}${g.s.input==='tap'?g.dots():''}${txt(466,291,'elbow',15,'#88795e')}${g.caption()}`);
 g.doodleKey=JSON.stringify([target]);return g;
}
function towers(g){const q=g.q;prepare(g);g.q=q;g.q.targets=[];q.frames.forEach((f,i)=>{if(q.prebraced.includes(i))return;g.q.targets.push({id:i,a:[f.x,f.y+f.h],b:[f.x+f.w,f.y],other:{a:[f.x,f.y],b:[f.x+f.w,f.y+f.h]}})});
 g.anchors=[];q.frames.forEach(f=>[[f.x,f.y],[f.x+f.w,f.y],[f.x+f.w,f.y+f.h],[f.x,f.y+f.h]].forEach(p=>{if(!g.anchors.some(a=>U.distance(a,p)<1))g.anchors.push(p)}));
 g.prompt=`Draw ${q.targets.length} missing diagonal brace${q.targets.length===1?'':'s'} in this ${q.layout}.`;g.hint='Join opposite corners of each weak four-sided bay. Either diagonal makes two triangles; a horizontal or vertical line does not brace the corners.';g.explanation=`The ${q.layout} is steady. Each new diagonal divides a weak four-sided bay into two rigid triangles.`;g.checkLabel='Test sketch';
 g.recognize=ps=>{if(!straight(ps)){g.say('Make each brace one fairly straight line from corner to opposite corner.');return}let t=q.targets.find(t=>!g.s.accepted.includes(t.id)&&(endpointMatch(ps,t)||endpointMatch(ps,t.other)));if(!t){g.s.mistake=ps;g.say('That line does not brace a weak bay. Join opposite corners of an unbraced frame.');g.scene();return}if(endpointMatch(ps,t.other)){[t.a,t.b]=[t.other.a,t.other.b]}g.accept(t,ps)};
 g.draw=()=>svg(`${q.frames.map((f,i)=>`<rect x="${f.x}" y="${f.y}" width="${f.w}" height="${f.h}" fill="#fff9" stroke="#899887" stroke-width="7"/>${q.prebraced.includes(i)?line([f.x,f.y+f.h],[f.x+f.w,f.y],'#90af81',7):''}`).join('')}${g.ink()}${g.dots()}<path d="M60 282h480" stroke="#ac9e81" stroke-width="9" stroke-linecap="round"/>${txt(300,314,`${g.s.accepted.length} / ${q.targets.length} missing braces drawn`,16)}${g.caption()}`);
 g.doodleKey=JSON.stringify([q.layout,q.frames,q.prebraced]);return g;
}
function clock(g){const time=g.q.time;prepare(g);g.q.time=time;g.q.angle=U.clockAngle(time);g.q.targets=[{id:0,a:[300,180],b:P(300,180,90-(time/2)%360,80),ray:true,minLength:58,maxLength:99,color:'#8a77a0'},{id:1,a:[300,180],b:P(300,180,90-(time%60)*6,121),ray:true,minLength:101,maxLength:145,color:'#ba8960'}];g.s.quiz=false;g.anchors=[[300,180],...Array.from({length:12},(_,i)=>P(300,180,90-i*30,121)),...g.q.targets.map(t=>t.b)];
 g.prompt=`Draw the short hour hand and long minute hand for ${U.fmtTime(time)}.`;g.hint='Start both strokes at the centre. Draw the hour hand shorter. At half past, the hour hand is halfway between two numbers.';g.explanation=`${U.fmtTime(time)} makes a ${g.q.angle}° ${U.type(g.q.angle).toLowerCase()} opening. The hour hand also moves as the minutes pass.`;
 const inherited=g.action,controls=g.controls;g.action=(k,v)=>{if(k==='check'&&g.s.accepted.length===2){g.s.quiz=true;g.prompt='Which family is the smaller angle between your hands?';g.refresh();return}if(k==='clock-family'){if(v===U.type(g.q.angle))g.success(g.explanation);else g.say(`Compare the smaller ${g.q.angle}° opening with 90° and 180°.`);return}inherited(k,v)};
 g.controls=()=>g.s.quiz?['Acute','Right','Obtuse',...(g.q.angle===180?['Straight']:[])].map(c=>btn(c,'clock-family',c,'secondary small')).join(''):controls();
 g.draw=()=>svg(`${circle(300,180,145,'#fffaf0',`stroke="#a59aae" stroke-width="3"`)}${Array.from({length:12},(_,i)=>{const p=P(300,180,90-i*30,129);return txt(p[0],p[1]+5,i||12,17,'#8a8092')}).join('')}${g.s.quiz?(()=>{let a=90-(time/2)%360,b=90-(time%60)*6,d=(b-a+720)%360;return wedge(300,180,d>180?b:a,g.q.angle,34)})():''}${g.ink()}${circle(300,180,9,'#edd8ac',`stroke="#9e8f78" stroke-width="3"`)}${g.s.input==='tap'?g.dots():''}${txt(300,347,g.s.quiz?'Look at the smaller marked opening':`${U.fmtTime(time)} · short hour hand, long minute hand`,15)}`);g.doodleKey=JSON.stringify([time]);return g;
}
S.doodles={supports:id=>supported.includes(id),names,straight,endpointMatch,rayMatch,create(g){if(g.id==='doodle'){g.mode='doodle';g.title=names.doodle;g.doodleKey=JSON.stringify([g.q.target]);return g}if(g.id==='loops')return loops(g);if(['tester','painter','garden','degrees'].includes(g.id))return singleRay(g,g.id);return {fold,yoga,towers,clock}[g.id](g)}};
})();
