'use strict';
(() => {
const S=SAFARI,U=S.util,A=S.art,$=s=>document.querySelector(s),app=$('#app');
const SAVE='gokurious-maths-mela-4-v2';
let saveOK=true,records={version:1,xp:0,mode:'arcade',world:0,games:{}},game=null,activeId=null,world=0,mode='arcade',busy=false,animation=0,run=0,assisted=false,sound=false,audioCtx=null,pointer=false,lessonId=null,lessonAnswers={},lessonQuestion=0,stageObserver=null;
try{const raw=localStorage.getItem(SAVE);if(raw){const p=JSON.parse(raw);if(p?.version!==1||typeof p.games!=='object'||!p.games||!Number.isFinite(p.xp)||p.xp<0)throw Error('Invalid save');for(const v of Object.values(p.games))if(!Number.isInteger(v.round)||v.round<0||!Number.isInteger(v.seed))throw Error('Invalid progress');records=p;world=Number.isInteger(p.world)?Math.max(0,Math.min(S.worlds.length-1,p.world)):0;mode=p.mode==='doodle'?'doodle':'arcade'}}catch{saveOK=false;}
function save(){records.world=world;records.mode=mode;if(saveOK)try{localStorage.setItem(SAVE,JSON.stringify(records))}catch{saveOK=false}$('#save-label').textContent=saveOK?'Progress stays on this device':'Playing without saving';$('#total-xp').textContent=records.xp;}
function record(id){if(!records.games[id])records.games[id]={round:0,seed:Math.floor(Math.random()*0xffffffff),assisted:0,error:0,estimated:0};return records.games[id]}
function setMode(m){if(!['arcade','doodle'].includes(m))return;mode=m;save();if(game)start(activeId);else if(activeId)showSummary();else renderHome()}
function chirp(success=true){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const n=audioCtx.currentTime;[0,.1,.21].slice(0,success?3:1).forEach((d,i)=>{const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type='sine';o.frequency.value=success?[440,554,659][i]:260;v.gain.setValueAtTime(0,n+d);v.gain.linearRampToValueAtTime(.06,n+d+.015);v.gain.exponentialRampToValueAtTime(.001,n+d+.18);o.connect(v);v.connect(audioCtx.destination);o.start(n+d);o.stop(n+d+.2)})}catch{}}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('#confetti').innerHTML=Array.from({length:30},(_,i)=>`<i style="--c:${['#eaa075','#bedc76','#a28bcb','#7db6aa'][i%4]};--x:${Math.random()*100}%;--d:${Math.random()*.4}s"></i>`).join('');setTimeout(()=>{$('#confetti').innerHTML=''},2200)}
function cancel(){stageObserver?.disconnect();run++;cancelAnimationFrame(animation);busy=false;pointer=false;}
function modes(){return activeId?'<span class="mode-note">'+(topic()?.doodle?'✎ Doodle game':'✦ Arcade game')+'</span>':'<button class="btn secondary" data-action="chapter">All chapters ↗</button>'}
function heroArt(){return `<svg class="hero-art" viewBox="0 0 500 265" fill="none" aria-hidden="true"><path d="M41 201c-49-80 33-134 108-137C212-1 344 0 408 72c78 91 30 173-92 172-63 28-200 9-275-43Z" fill="#e1ebc9"/><path d="M57 157C23 71 162 19 241 78S476 103 433 191" stroke="#aebf8c" stroke-width="2" stroke-dasharray="5 7"/><ellipse cx="235" cy="227" rx="160" ry="14" fill="#bbcba55c"/><g transform="rotate(-12 165 143)" class="floaty"><path d="m165 60 81 138H84Z" fill="#f9b177" stroke="#ce8551" stroke-width="2"/><path d="m84 198 9 13h160l-7-13Z" fill="#d99960"/><path d="m165 60 9 14 79 137-7-13Z" fill="#e5a062"/><circle cx="150" cy="146" r="4" fill="#4d4d34"/><circle cx="178" cy="146" r="4" fill="#4d4d34"/><path d="M153 163q11 12 23 0" stroke="#634d35" stroke-width="3" stroke-linecap="round"/><circle cx="134" cy="157" r="6" fill="#f89e78"/><circle cx="191" cy="157" r="6" fill="#f89e78"/></g><g transform="rotate(10 335 163)"><rect x="274" y="110" width="116" height="116" rx="20" fill="#98b878"/><rect x="266" y="101" width="116" height="116" rx="20" fill="#bedb90" stroke="#8ca969" stroke-width="2"/><circle cx="304" cy="150" r="4" fill="#36563f"/><circle cx="337" cy="150" r="4" fill="#36563f"/><path d="M310 169q11 11 23 0" stroke="#41603f" stroke-width="3" stroke-linecap="round"/><path d="M275 201h24v-24" stroke="#789958" stroke-width="2"/><path d="M273 108v95h99" stroke="#d3e9b1" stroke-width="3"/></g><g transform="rotate(13 330 51)"><path d="m286 48 95-26-42 70-15-31Z" fill="#83babc" stroke="#589a9d" stroke-width="2"/><path d="m324 61 57-39-44 51-6 20Z" fill="#d1ebe1"/></g><path d="m76 60 4 11 11 4-11 4-4 11-4-11-11-4 11-4Z" fill="#d9aa54"/><path d="m438 122 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z" fill="#d9aa54"/><circle cx="230" cy="31" r="5" fill="#a696c1"/><circle cx="431" cy="214" r="5" fill="#eab675"/><circle cx="74" cy="207" r="4" fill="#93b6aa"/><path d="m411 61 10-9m-13 2 5-10M66 116l-12-3" stroke="#9cb27f" stroke-width="3" stroke-linecap="round"/><g transform="rotate(-8 230 230)"><rect x="175" y="226" width="128" height="26" rx="13" fill="#fffaf0" stroke="#ccd4ba"/><text x="239" y="243" text-anchor="middle" fill="#6c7d56" font-family="Nunito,sans-serif" font-size="11" font-weight="800">a little curiosity goes far</text></g></svg>`}
function thumbnail(id){const g=S.games.create(id,0,1976,{stage(){},tell(){},render(){},complete(){},animate(){},markSelected(){}},{mode:mode});if(id==='model')g.s.h=g.q.heights.map((n,i)=>Math.max(1,n-(i===0?1:0)));if(g.drawingGame)return g.draw().replace(/<text\b[^>]*>[\s\S]*?<\/text>/g,'').replace(/role="[^"]*"|tabindex="[^"]*"|data-action="[^"]*"|data-value="[^"]*"|aria-label="[^"]*"/g,'').replace('<svg ','<svg aria-hidden="true" ');if(id==='loops')g.s.path=[0,1,2,3,4,5,0];if(id==='painter')g.s.painted=[0,1];if(id==='fold')g.s.folds=3;if(id==='towers')g.s.braces=[0];if(id==='degrees')g.s.value=60;if(id==='clock')g.s.value=180;if(id==='doodle')g.s.reveal=true;let s=g.draw();return s.replace(/<text\b[^>]*>[\s\S]*?<\/text>/g,'').replace(/role="[^"]*"|tabindex="[^"]*"|data-action="[^"]*"|data-value="[^"]*"|aria-label="[^"]*"/g,'').replace('<svg ','<svg aria-hidden="true" ');}
function renderHome(){cancel();game=null;activeId=null;document.body.classList.toggle('doodle',mode==='doodle');const w=S.worlds[world];history.replaceState(null,'','#ch'+(world+1));let total=Object.values(records.games).reduce((s,g)=>s+Math.min(g.round,24),0),complete=Object.values(records.games).filter(g=>g.round>=24).length;
 app.innerHTML=`<section class="home"><div class="hero"><div><div class="eyebrow"><span class="dot"></span>MATHS MELA <span class="chapter-pill">CHAPTER ${String(world+1).padStart(2,'0')}</span></div><h1>A world of<br><em>${w.hero}</em></h1><p>Build, bend and play your way to a discovery.<br>One little concept. A whole lot of adventure.</p></div>${heroArt()}</div><div class="world-bar"><div class="world-title"><h2>${String(world+1).padStart(2,'0')} / ${w.name}</h2><p>${w.subtitle}</p></div>${modes()}</div><div class="game-grid">${S.topics.slice(world*4,world*4+4).map((t,i)=>{let p=records.games[t.id]?.round||0;return `<button class="game-card" data-action="play" data-value="${t.id}" aria-label="${p?'Continue':'Play'} ${t.name}: ${t.concept}" style="--tile:${t.color}"><div class="card-art"><span class="card-number">${String(world*4+i+1).padStart(2,'0')} / ${t.tag.split(' ')[0]}</span>${thumbnail(t.id)}<span class="card-state">${p>=24?'★ ★ ★':p?'✦ '+p+'/24':'✦ NEW'}</span></div><div class="card-text"><h3>${mode==='doodle'&&S.doodles.supports(t.id)?S.doodles.names[t.id]:t.name}</h3><p>${t.concept}</p><span class="card-arrow">↗</span></div><div class="card-meta"><span>${p?'CONTINUE EXPLORING':'24 ROUNDS + FREE PLAY'}</span><span>${t.doodle?'✎ DRAWING':'✦ ARCADE'}</span></div></button>`}).join('')}</div><div class="journey-bottom"><div class="journey-note"><span class="badge">✧</span><span><b>${complete}/${S.topics.length} adventures</b> complete<br>${total?total+' rounds explored':'Your discovery trail starts here'}</span></div><div class="journey-nav"><button data-action="world" data-value="-1" aria-label="Previous island" ${world===0?'disabled':''}>←</button><div class="world-dots">${String(world+1).padStart(2,"0")} / ${S.worlds.length}</div><button data-action="world" data-value="1" aria-label="Next island" ${world===S.worlds.length-1?'disabled':''}>→</button></div><button class="text-btn" data-action="chapter">Explore the chapter map ↗</button></div></section>`;
 save();}
function topic(){return S.topics.find(t=>t.id===activeId)}
const api={render:()=>renderPlay(),stage:()=>renderStage(),tell:text=>tell(text),complete:(text,extra)=>completeRound(text,extra),animate:(duration,onFrame,onEnd)=>animate(duration,onFrame,onEnd),markSelected:(key,value)=>{document.querySelectorAll(`[data-action="${key}"]`).forEach(el=>{let on=el.dataset.value===String(value);el.classList.toggle('orange',on);el.setAttribute('aria-pressed',String(on))})}};
function start(id,updateHash=true){cancel();activeId=id;const t=topic();if(!t){home();return}world=Math.floor(S.topics.indexOf(t)/4);assisted=false;const p=record(id);p.serial=(Number.isInteger(p.serial)?p.serial:0)+1;const fresh=(p.seed+Math.imul(p.serial,2654435761))>>>0;game=S.games.create(id,p.round,fresh,api,{mode,previous:p.lastProblem,recent:Array.isArray(p.recent)?p.recent:[]});p.currentSeed=game.seed;p.currentMode=game.mode;p.lastProblem=game.problemKey;p.recent=[...(Array.isArray(p.recent)?p.recent:[]),{problem:game.problemKey,visual:game.visualKey}].slice(-4);renderPlay();save();if(updateHash)history.replaceState(null,'','#'+id);}
function restartGame(){if(!activeId)return;const id=activeId,p=record(id);cancel();const earned=Math.max(0,p.round*10-Math.min(p.round,p.assisted||0)*4);records.xp=Math.max(0,records.xp-earned);records.games[id]={round:0,seed:Math.floor(Math.random()*0xffffffff),assisted:0,error:0,estimated:0};if(lessonId===id){lessonAnswers={};lessonQuestion=0}game=null;start(id);}
function restartButton(){return '<button class="restart-button" data-action="restart" aria-label="Restart game from beginning" title="Restart this game from Round 1"><span aria-hidden="true">↺</span><span class="restart-label">Restart</span></button>';}
function home(){history.replaceState(null,'',location.pathname+location.search);renderHome()}
function renderPlay(){if(!game)return;document.body.classList.toggle('doodle',game.mode==='doodle');const t=topic(),p=record(t.id),localRound=game.round%24+1,level=Math.min(2,Math.floor(game.round/8));
 app.innerHTML=`<section class="play"><div class="play-top"><div class="back-actions"><button class="back-btn" data-action="home">← Map</button>${restartButton()}</div><div class="mobile-tip"><button data-action="learn">Read</button><button data-action="hint">Hint ✧</button></div>${modes()}</div><div class="play-heading"><div><h1>${game.title||t.name}</h1><p>${t.concept} · ${game.mode==='doodle'?'Draw & discover':'Maths Mela'}</p></div><div class="mission-stats"><div><span>${p.round>=24?'FREE PLAY':'EXPEDITION'}</span><b>${Math.min(localRound,24)}<small>/24</small></b></div><div><span>STARS</span><b>${'★'.repeat(Math.floor(Math.min(p.round,24)/8))}${'☆'.repeat(3-Math.floor(Math.min(p.round,24)/8))}</b></div></div></div><div class="game-layout"><div class="game-box" style="--scene:${t.color}"><div class="game-instruction"><h2 id="mission-prompt">${U.escape(game.prompt)}</h2><button class="round-chip" data-action="remix" aria-label="New puzzle for this concept" title="New puzzle · keep your completed rounds">${['Discover','Explore','Challenge'][level]} ${localRound%8||8}/8 ↻</button></div><div class="stage" id="stage"></div><div class="controls" id="controls"></div><div class="feedback" id="feedback" role="status" aria-live="polite"><span class="feedback-icon">✧</span><span class="feedback-text">${U.escape(game.feedback||defaultFeedback())}</span></div></div><aside class="side-panel"><section class="concept-card"><div class="eyebrow">✦ A LITTLE DISCOVERY</div><h3>${t.concept}</h3><p>${t.learn}</p><div class="example">${t.example}</div></section><section class="mission-card"><h3>Your expedition</h3>${['Discover the idea','Explore new variations','Take the challenge'].map((s,i)=>`<div class="milestone ${p.round>=(i+1)*8?'done':''}"><i>${p.round>=(i+1)*8?'✓':i+1}</i><span>${s}<br><small>${i*8+1}–${(i+1)*8} rounds</small></span></div>`).join('')}<div class="progress-track"><span style="width:${Math.min(100,p.round/24*100)}%"></span></div></section><div class="help-row"><button class="btn secondary" data-action="hint">Hint ✧</button><button class="btn secondary" data-action="learn">Read & explore</button></div></aside></div></section>`;
 renderControls();if(game.done)paintSuccess(game.successText);else if(game.feedback)tell(game.feedback,false);renderStage();attachPointers();}
function defaultFeedback(){if(game?.drawingGame)return 'Draw with your finger or mouse. Tap points is here if you need it.';if(game?.mode==='doodle')return 'Estimate, check, and try the pen. Explore one idea at a time.';return 'Take your time. Tap, try and discover. Hints are here to help.'}
function renderStage(){if(!game||!$('#stage'))return;const stage=$('#stage');stage.innerHTML=game.draw();const box=stage.getBoundingClientRect();if(box.height>box.width&&['time','duration','time-pen','pour','pour-pen','mirror','axis','position','treasure'].includes(game.id)){const v={time:'155 25 290 300',duration:'145 40 310 310','time-pen':'155 25 300 320',pour:'190 30 280 320','pour-pen':'190 30 290 320',mirror:'128 20 345 330',axis:'135 20 330 320',position:'117 25 340 325',treasure:'117 25 340 325'};stage.querySelector('svg').setAttribute('viewBox',v[game.id]);}const input=$('[data-range="main"]');if(input&&game.s.value!==undefined){input.value=game.s.value;const out=input.parentElement.querySelector('output');if(out)out.textContent=game.formatValue?game.formatValue(game.s.value):game.s.value;}}
function renderControls(){if(!game||!$('#controls'))return;$('#controls').innerHTML=game.done?'':game.controls();$('#controls').querySelectorAll('button,input').forEach(el=>{el.disabled=busy});if(game.id==='painter'&&!game.drawingGame)api.markSelected('brush',game.s.brush);if(game.id==='clock')renderStage();}
function tell(text,sfx=true){if(!game||game.done)return;game.feedback=text;const f=$('#feedback');if(f){f.className='feedback retry';f.innerHTML=`<span class="feedback-icon">✧</span><span class="feedback-text">${U.escape(text)}</span>`;}renderStage();if(sfx)chirp(false)}
function completeRound(text,extra={}){if(!game)return;const p=record(game.id);p.round++;if(assisted)p.assisted=(p.assisted||0)+1;if(Number.isFinite(extra.error)){p.error=(p.error||0)+extra.error;p.estimated=(p.estimated||0)+1}records.xp+=assisted?6:10;game.successText=text;save();renderControls();paintSuccess(text);renderStage();chirp(true);if(p.round%8===0)celebrate();}
function paintSuccess(text){const f=$('#feedback');if(!f)return;f.className='feedback success';f.innerHTML=`<span class="feedback-icon">✓</span><span class="feedback-text">${U.escape(text)}</span><button class="btn" data-action="next">${record(activeId).round%24===0?'Finish':'Next'} →</button>`;}
function animate(duration,onFrame,onEnd){if(busy)return;busy=true;renderControls();const token=run,startTime=performance.now(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){onFrame(1);busy=false;renderControls();onEnd();return}const frame=now=>{if(token!==run)return;const t=Math.min(1,(now-startTime)/duration);onFrame(t);if(t<1)animation=requestAnimationFrame(frame);else{busy=false;renderControls();onEnd()}};animation=requestAnimationFrame(frame)}
function next(){if(!game?.done)return;if(record(activeId).round%24===0){cancel();game=null;showSummary()}else start(activeId)}
function showSummary(){const t=topic(),p=record(activeId),idx=S.topics.indexOf(t);app.innerHTML=`<section class="done-screen"><div class="trophy" aria-hidden="true">✦</div><div class="eyebrow">EXPEDITION COMPLETE</div><h1>${t.name}, explored!</h1><p>${t.why}</p><div class="summary-pills"><span><b>${p.round}</b>rounds completed</span><span><b>★★★</b>expedition stars</span>${p.estimated?`<span><b>${(p.error/p.estimated).toFixed(1)}°</b>average D-game error</span>`:''}</div><p>Ready for another discovery? Keep playing new rounds of this concept, or visit the next adventure.</p><div class="done-actions"><button class="btn" data-action="play" data-value="${S.topics[(idx+1)%S.topics.length].id}">Next concept →</button><button class="btn secondary" data-action="play" data-value="${activeId}">Keep playing ↻</button><button class="btn secondary" data-action="restart">↺ Restart game</button><button class="btn secondary" data-action="home">Adventure map</button></div></section>`;celebrate();}
function openModal(title,body){$('#modal').classList.remove('lesson-dialog');$('#modal-body').innerHTML=`<h2>${title}</h2>${body}`;if(!$('#modal').open)$('#modal').showModal()}
function learn(id=activeId){if(!S.lessons[id]){chapter();return}if(lessonId!==id)lessonAnswers={};lessonId=id;lessonQuestion=0;renderLesson();}
function renderKnowledgeCheck(){const l=S.lessons[lessonId],i=lessonQuestion,q=l.checks[i],picked=lessonAnswers[i],answered=Number.isInteger(picked),finished=Object.keys(lessonAnswers).length===l.checks.length;const target=$('#article-quiz');if(!target)return;
 target.innerHTML=`<p class="gk-counter">Question ${i+1} of ${l.checks.length}</p><div class="gk-challenge"><p class="gk-question">${q.q}</p><div class="gk-options">${q.options.map((o,j)=>`<button data-action="lesson-answer" data-value="${i}:${j}" aria-pressed="${picked===j}" class="${answered&&j===q.answer?'correct':picked===j?'incorrect':''}">${o}</button>`).join('')}</div>${answered?`<p class="gk-feedback ${picked===q.answer?'correct':'incorrect'}" role="status">${picked===q.answer?'Correct.':'Try the idea again.'} ${q.why}</p>`:''}</div>${finished?`<p class="gk-score">${l.checks.filter((c,n)=>lessonAnswers[n]===c.answer).length} of ${l.checks.length} correct. Read the explanations to keep learning.</p>`:''}<button class="gk-button gk-next" data-action="lesson-next" ${!answered?'disabled':''}>${i===l.checks.length-1?'Try questions again':'Next question'}</button>`;
}
function renderLesson(){const t=S.topics.find(t=>t.id===lessonId),l=S.lessons[lessonId],next=S.topics.find(t=>t.id===l.related[0]);
 const body=`<article class="gk-article" aria-labelledby="article-title" data-topic="${t.id}"><header class="gk-head"><p><button class="gk-text-button" data-action="close">‹ Back to ${game?.title||topic()?.name||'the games'}</button></p><p class="gk-meta">Maths / Class 4 / Chapter ${t.chapter+1}</p><h1 id="article-title">${t.concept}</h1><p class="gk-lead">${l.objective}</p><p class="gk-pages">${t.name} · NCERT pages ${t.pages}</p></header>
 <section class="gk-panel gk-soft"><h2>Before you try</h2><p>${l.predict}</p></section>
 <section class="gk-section"><h2>Try these ideas</h2><ul class="gk-ideas">${l.explore.map(p=>`<li>${p}</li>`).join('')}</ul><button class="gk-text-button gk-play-link" data-action="${activeId===t.id?'close':'modal-play'}" data-value="${t.id}">Try it in ${t.name} ›</button></section>
 <section class="gk-prose"><h2>Why it works</h2>${l.article.map(([h,p])=>`<section class="article-section"><h3>${h}</h3><p>${p}</p></section>`).join('')}<div class="gk-worked"><h3>Worked example</h3><p><strong>${l.worked.q}</strong></p><ol>${l.worked.steps.map(p=>`<li>${p}</li>`).join('')}</ol></div></section>
 <section class="gk-section gk-checks" aria-labelledby="article-checks"><h2 id="article-checks">Check your understanding</h2><div id="article-quiz"></div><details class="gk-answers"><summary>Show answers</summary><ol>${l.checks.map(q=>`<li><strong>${q.options[q.answer]}.</strong> ${q.why}</li>`).join('')}</ol></details></section>
 <section class="gk-section"><h2>Explain it in your own words</h2><p>${l.reflect}</p></section>
 <section class="gk-panel gk-soft"><h2>What will you discover next?</h2><p>Explore ${next.concept.toLowerCase()} in ${next.name}.</p><button class="gk-button" data-action="lesson-open" data-value="${next.id}">Continue learning</button></section>
 <section class="gk-section gk-faqs"><h2>Frequently asked questions</h2>${l.faqs.map(f=>`<details><summary>${f.q}</summary><p>${f.a}</p></details>`).join('')}</section>
 <section class="gk-panel gk-adults"><h2>For parents &amp; teachers</h2><ul>${l.activities.map(a=>`<li><strong>${a.title}.</strong> ${a.text}</li>`).join('')}</ul></section>
 <section class="gk-section"><h2>Related activities</h2><ul class="gk-related">${l.related.map(id=>{const r=S.topics.find(t=>t.id===id);return `<li><button data-action="lesson-open" data-value="${id}"><span><strong>${r.name}</strong><small>${r.concept} / Class 4</small></span><span aria-hidden="true">›</span></button></li>`}).join('')}</ul></section>
 <footer class="gk-article-footer"><p>${S.worlds[t.chapter].name} · <a href="${S.worlds[t.chapter].source}" target="_blank" rel="noopener">NCERT Maths Mela, Chapter ${t.chapter+1}</a></p><button class="gk-button" data-action="close">Back to my game</button></footer></article>`;
 $('#modal').classList.add('lesson-dialog');$('#modal-body').innerHTML=body;renderKnowledgeCheck();if(!$('#modal').open)$('#modal').showModal();$('#modal').scrollTop=0;
}
function hint(){if(!game||game.done)return;assisted=true;openModal('A little nudge',`<p>${game.hint||topic().hint}</p><p>${topic().example}</p><button class="btn" data-action="close">Try it out →</button>`)}
function chapter(){openModal('Maths Mela · Class 4',`<p>Four adventures for each of the 14 NCERT Maths Mela chapters: three interactive games and one guided Doodle. Explore 24 rounds in each game, followed by unlimited varied practice.</p><div class="guide-list">${S.worlds.map((w,i)=>`<div class="chapter-guide"><button class="btn secondary" data-action="chapter-select" data-value="${i}">${i+1}. ${w.name} ↗</button><p>NCERT pages ${w.pages} · Priority ${w.priority} · <a href="${w.source}" target="_blank" rel="noopener">Official chapter</a></p></div>`).join('')}</div><h3>One concept at a time</h3><p>Each game has 8 Discover, 8 Explore and 8 Challenge rounds. New puzzle ↻ changes the current puzzle. Restart ↺ clears only this game’s rounds, stars and earned XP. Progress stays in this browser. A completed round earns 10 XP, or 6 XP after a hint.</p><h3>Read, try, explain</h3><p>Read inside any game opens its own original article, worked example, practice questions, FAQs and parent or teacher activities. The reading layout and fonts follow the Class 5 package and GoKurious article structure. Doodles check complete strokes, not just pen movement; Tap points offers an accessible alternative.</p><h3>Curriculum reference</h3><p>NCERT Maths Mela, Grade 4, first edition March 2025 (book code 0433). The chapter names and order follow this book. Repeating colour patterns, bar graphs and transport routes also cover the requested simulator topics. Transport games include the chapter’s multiplication and division work. Wildlife counts are invented practice data.</p><p><a href="https://gokurious.com/simulators/moon-phases/" target="_blank" rel="noopener">GoKurious article reference</a> · <a href="../../index.html">Class 4 chapter library</a></p>`)}
function dispatch(k,v){if(k==='chapter-select'){world=+v;$('#modal').close();renderHome();return}if(k==='lesson-open'){learn(v);return}if(k==='lesson-answer'){const [i,j]=v.split(':').map(Number);if(i===lessonQuestion&&S.lessons[lessonId]?.checks[i]?.options[j]!==undefined){lessonAnswers[i]=j;renderKnowledgeCheck();$(`[data-action="lesson-answer"][data-value="${v}"]`)?.focus({preventScroll:true})}return}if(k==='lesson-next'){if(!Number.isInteger(lessonAnswers[lessonQuestion]))return;if(lessonQuestion===S.lessons[lessonId].checks.length-1){lessonAnswers={};lessonQuestion=0}else lessonQuestion++;renderKnowledgeCheck();$('#article-quiz')?.scrollIntoView({block:'nearest'});$('#article-quiz button')?.focus({preventScroll:true});return}if(k==='restart'){restartGame();return}if(k==='remix'){if(game&&!busy)start(activeId);return}if(['mode','home','play','world','world-index','chapter','learn','hint','close','modal-play','next'].includes(k)){
 if(k==='mode'){setMode(v);return}if(k==='home'){home();return}if(k==='play'){start(v);return}if(k==='world'){world=Math.max(0,Math.min(S.worlds.length-1,world+(+v)));renderHome();return}if(k==='world-index'){world=+v;renderHome();return}if(k==='chapter'){chapter();return}if(k==='learn'){learn();return}if(k==='hint'){hint();return}if(k==='close'){$('#modal').close();return}if(k==='modal-play'){$('#modal').close();start(v);return}if(k==='next'){next();return}}
 if(game&&!game.done&&!busy)game.action(k,v);
}
function attachPointers(){const stage=$('#stage');if(!stage)return;stageObserver?.disconnect();stageObserver=new ResizeObserver(()=>{if(stage.isConnected&&game)renderStage()});stageObserver.observe(stage);function point(ev){const el=stage.querySelector('svg');if(!el)return [0,0];const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(el.getScreenCTM().inverse());return [p.x,p.y-Number(el.dataset.offsetY||0)]}
 stage.addEventListener('pointerdown',e=>{if(!game?.pointer||game.done||busy||(e.target.closest('[data-action]')&&!(game.pointerOnTargets&&game.s.input==='draw')))return;pointer=true;stage.setPointerCapture(e.pointerId);game.pointer(...point(e),'start');e.preventDefault()});stage.addEventListener('pointermove',e=>{if(pointer&&game?.pointer&&!busy&&!game.done){game.pointer(...point(e),'move');e.preventDefault()}});const end=e=>{if(pointer&&game?.pointer&&!game.done&&!busy)game.pointer(...point(e),e.type==='pointercancel'?'cancel':'end');pointer=false;};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;dispatch(el.dataset.action,el.dataset.value)});
document.addEventListener('keydown',e=>{const el=e.target.closest('svg [role="button"]');if(el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();dispatch(el.dataset.action,el.dataset.value)}});
document.addEventListener('input',e=>{if(e.target.matches('[data-number]')&&game&&!busy&&!game.done)game.action('number',e.target.value);if(e.target.matches('[data-range]')&&game&&!busy&&!game.done)game.action('range',e.target.value)});
$('#brand').addEventListener('click',home);$('#guide').addEventListener('click',chapter);$('#close-modal').addEventListener('click',()=>$('#modal').close());$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#sound').addEventListener('click',()=>{sound=!sound;$('#sound').innerHTML=sound?'♪':'♪<span class="sound-off"></span>';$('#sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');$('#sound').title=sound?'Turn sound off':'Turn sound on';if(sound)chirp()});
addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(S.topics.some(t=>t.id===id))start(id,false);else {const m=id.match(/^ch(\d+)$/);if(m)world=Math.max(0,Math.min(S.worlds.length-1,+m[1]-1));renderHome()}});
addEventListener('resize',()=>{if(game)renderStage()});
save();const initial=location.hash.slice(1);if(S.topics.some(t=>t.id===initial))start(initial,false);else {const m=initial.match(/^ch(\d+)$/);if(m)world=Math.max(0,Math.min(S.worlds.length-1,+m[1]-1));renderHome();}
})();
