'use strict';
(() => {
const S=SAFARI,U=S.util,A=S.art,{svg,text,line,rect,dot,poly,btn,hit,I,pick,C,clock}=A;
const segment=(a,b)=>[a,b],outline=(x,y,w,h)=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h],[x,y]];
function path(points,color='#8a77c7',width=7,dash=''){return `<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linejoin="round" stroke-linecap="round" ${dash?`stroke-dasharray="${dash}"`:''}/>`}
const D={};
D['shape-pen']=g=>{if(g.level>0&&g.r()<.4){const x=I(g,170,210),y=I(g,95,115),z=110,dx=67,dy=-48,front=[[x,y],[x+z,y],[x+z,y+z],[x,y+z]],back=front.map(([a,b])=>[a+dx,b+dy]),edges=[...front.map((p,i)=>[p,front[(i+1)%4]]),...back.map((p,i)=>[p,back[(i+1)%4]]),...front.map((p,i)=>[p,back[i]])],missing=U.shuffle(g.r,Array.from({length:12},(_,i)=>i)).slice(0,3);g.q.paths=missing.map(i=>edges[i]);g.prompt='Draw the three missing straight edges of this cube model.';g.background=()=>edges.filter((p,i)=>!missing.includes(i)).map(p=>path(p,'#75a18c',4)).join('')+text(300,315,'A cube has 12 edges, including hidden edges.',19);return}const n=pick(g,g.level?[3,4,5,6]:[3,4]),turn=I(g,0,3)*30,r=I(g,92,125);const p=Array.from({length:n},(_,i)=>U.pt(300,176,90+turn+i*360/n,r));g.q.paths=p.map((v,i)=>segment(v,p[(i+1)%n]));g.prompt=`Join the vertices to draw all ${n} straight sides.`;g.background=()=>poly(p,'#c1d9a933','stroke-dasharray="3 8"')+text(300,334,`${n} vertices • ${n} sides • one closed polygon`,20)};
D['map-pen']=g=>{const start=[I(g,95,145),I(g,70,140)],a=[I(g,230,310),start[1]],b=[a[0],I(g,235,285)],end=[I(g,420,490),b[1]];g.q.paths=[segment(start,a),segment(a,b),segment(b,end)];g.prompt='Draw the route: start → tree → bridge → treasure.';g.background=()=>g.q.paths.map(p=>path(p,'#adc7a888',36)).join('')+[start,a,b,end].map((p,i)=>text(p[0],p[1]-25,['START','TREE','BRIDGE','TREASURE'][i],15)).join('')+text(420,90,'→ then ↓ then →',19)};
D['pattern-pen']=g=>{const shape=pick(g,[3,4]),size=I(g,30,46),cy=180,points=x=>shape===3?[[x,cy-size],[x+size,cy+size],[x-size,cy+size],[x,cy-size]]:outline(x-size,cy-size,size*2,size*2);g.q.paths=[points(445)];g.prompt=`Draw the missing ${shape===3?'triangle':'square'} to repeat the border.`;g.background=()=>[135,290].map((x,i)=>path(points(x),C[i],6)+dot(x+74,cy,18,C[3])).join('')+text(300,82,'Shape, circle • shape, circle • shape …',20)+text(445,282,'Complete the motif',17)};
D['place-pen']=g=>{const tens=I(g,1,g.level?3:2),loose=I(g,1,9);g.q.tens=tens;g.q.loose=loose;g.q.paths=Array.from({length:tens},(_,i)=>outline(126,71+i*65,345,48));g.prompt=`Bundle ${tens*10+loose} ones: enclose each group of ten.`;g.background=()=>Array.from({length:tens*10+loose},(_,i)=>dot(145+i%10*33,95+Math.floor(i/10)*65,9,i>=tens*10?C[0]:C[2])).join('')+text(300,328,`${tens} tens and ${loose} loose ones`,21)};
D['fraction-pen']=g=>{const x=I(g,105,150),w=I(g,260,325),y=90,h=170,quarters=g.level>0||g.r()<.5;g.q.paths=[segment([x+w/2,y],[x+w/2,y+h])];if(quarters)g.q.paths.push(segment([x,y+h/2],[x+w,y+h/2]));g.prompt=`Cut this whole into ${quarters?'four equal quarters':'two equal halves'}.`;g.background=()=>rect(x,y,w,h,'#f0ca9888',`rx="0" stroke="#b38a63" stroke-width="3"`)+text(300,324,'Equal parts of the same whole',21)};
D['length-pen']=g=>{const start=I(g,0,5),len=I(g,3,8),x=n=>65+n*32;g.q.paths=[segment([x(start),158],[x(start+len),158])];g.prompt=`Draw ${len} model cm from the start dot at ${start} cm.`;g.background=()=>rect(62,186,478,63,'#ead29b')+Array.from({length:16},(_,i)=>line([x(i),185],[x(i),204],'#7d704d',2)+text(x(i),230,i,15)).join('')+text(300,307,'Length = end reading − start reading',20)};
D['sum-pen']=g=>{const start=I(g,10,49),a=I(g,1,5)*10,b=I(g,1,9),end=start+a+b,scale=440/(a+b);g.q.paths=[segment([80,190],[80+a*scale,130]),segment([80+a*scale,130],[520,190])];g.prompt=`Sketch ${start} + ${a} + ${b}: two jumps to ${end}.`;g.background=()=>line([60,233],[540,233])+[[80,start],[80+a*scale,start+a],[520,end]].map(([x,n])=>line([x,222],[x,242])+text(x,273,n,20)).join('')+text(235,105,'+'+a,26)+text(490,105,'+'+b,26)+text(300,328,'A jump joins the start and finish markers.',18)};
D['pour-pen']=g=>{const target=I(g,1,9)*100,y=305-target/1000*240;g.q.paths=[segment([215,y],[385,y])];g.prompt=`Draw a level water line at ${target} mL.`;g.background=()=>rect(210,60,180,247,'#fff9',`stroke="#7ba4a0" stroke-width="4"`)+Array.from({length:11},(_,i)=>line([382,305-i*24],[404,305-i*24],'#688e81',2)+text(437,311-i*24,i*100,16)).join('')+text(300,340,'1000 mL = 1 L',20)};
D['array-pen']=g=>{const groups=I(g,2,4),size=I(g,2,g.level?6:4);g.q.groups=groups;g.q.size=size;g.q.paths=Array.from({length:groups},(_,i)=>outline(80+i*112,104,99,140));g.prompt=`Draw ${groups} separate groups of ${size} counters.`;g.background=()=>Array.from({length:groups},(_,i)=>Array.from({length:size},(_,j)=>dot(105+i*112+j%2*42,135+Math.floor(j/2)*39,12,C[i])).join('')).join('')+text(300,302,`${groups} × ${size} = ${groups*size}`,25)};
D['wild-pen']=g=>{const start=I(g,2,8)*100,step=pick(g,[25,50,100]),a=I(g,0,3),b=I(g,5,8);g.q.paths=[segment([75+a*55,163],[75+b*55,163])];g.prompt=`Join ${start+a*step} to ${start+b*step}. The gap is ${(b-a)*step}.`;g.background=()=>line([75,206],[515,206])+Array.from({length:9},(_,i)=>line([75+i*55,196],[75+i*55,216])+text(75+i*55,250,start+i*step,15)).join('')+text(300,315,'Invented wildlife counts • equal number-line steps',17)};
D['mirror-pen']=g=>{const y=I(g,74,104),w=I(g,75,130);const left=[[300,y],[300-w,y+60],[300-w+30,255],[300,222]],right=left.map(([x,y])=>[600-x,y]);g.q.paths=right.slice(1).map((p,i)=>segment(right[i],p));g.prompt='Reflect the outline across the dotted mirror.';g.background=()=>path(left,C[2],7)+line([300,36],[300,305],C[0],3,'stroke-dasharray="7 7"')+text(300,334,'Match the distance on both sides.',20)};
D['time-pen']=g=>{const t=I(g,0,g.level?143:23)*(g.level?5:30),cx=300,cy=176;const pt=(a,r)=>[cx+Math.sin(a)*r,cy-Math.cos(a)*r];g.q.paths=[segment([cx,cy],pt((t%720)*Math.PI/360,63)),segment([cx,cy],pt((t%60)*Math.PI/30,94))];g.prompt=`Draw ${U.fmtTime(t)}: short hour hand, then long minute hand.`;g.background=()=>dot(cx,cy,128,'#fff9',`stroke="#769988" stroke-width="4"`)+Array.from({length:12},(_,i)=>text(...pt((i+1)*Math.PI/6,108),i+1,18)).join('')+text(300,335,'Short = hours • long = minutes',20)};
D['route-pen']=g=>{const a=I(g,5,19),b=I(g,5,19),extra=I(g,2,9),up=g.r()<.5,y=up?75:265,other=up?265:75;g.q.distances=[a,b,extra];g.q.paths=[segment([90,170],[300,y]),segment([300,y],[510,170])];g.prompt=`Draw the shorter museum route: ${a}+${b} or ${a+extra}+${b} km.`;g.background=()=>path([[90,170],[300,y],[510,170]],'#bacfa8',19)+path([[90,170],[300,other],[510,170]],'#bfb5d477',19)+text(190,y-20,a+' km',20)+text(415,y-20,b+' km',20)+text(190,other+(up?37:-20),a+extra+' km',20)+text(415,other+(up?37:-20),b+' km',20)+text(74,214,'Start',17)+text(518,214,'Museum',17)};
D['data-pen']=g=>{const step=pick(g,[1,2,5]),values=Array.from({length:g.level?3:2},()=>I(g,2,7)*step);g.q.paths=values.map((v,i)=>segment([205+i*105,282],[205+i*105,282-v/step*28]));g.prompt='Draw each bar up from zero to its fruit count.';g.background=()=>Array.from({length:9},(_,i)=>line([145,282-i*28],[490,282-i*28],'#88a18f55',1)+text(121,289-i*28,i*step,16)).join('')+values.map((v,i)=>text(205+i*105,34,['Apple','Banana','Orange'][i]+': '+v,19)+text(205+i*105,318,['A','B','O'][i],20)).join('')};
function pointSegment(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l)):0;return U.distance(p,[a[0]+t*dx,a[1]+t*dy])}
// Require endpoint accuracy, route coverage, and closeness along the whole stroke.
function matches(stroke,target,tolerance=20){if(stroke.length<2)return false;const closed=U.distance(target[0],target.at(-1))<1;let t=target;if(!closed&&U.distance(stroke[0],t.at(-1))<U.distance(stroke[0],t[0]))t=[...t].reverse();if(U.distance(stroke[0],t[0])>tolerance||U.distance(stroke.at(-1),t.at(-1))>tolerance)return false;const segments=t.slice(1).map((p,i)=>[t[i],p]);if(stroke.some(p=>Math.min(...segments.map(([a,b])=>pointSegment(p,a,b)))>tolerance))return false;const drawn=stroke.slice(1).map((p,i)=>[stroke[i],p]);for(const [a,b]of segments)for(let j=0;j<=10;j++){const p=[a[0]+(b[0]-a[0])*j/10,a[1]+(b[1]-a[1])*j/10];if(Math.min(...drawn.map(([c,d])=>pointSegment(p,c,d)))>tolerance)return false}return true}
Object.entries(D).forEach(([id,setup])=>{S.constructors[id]=g=>{g.mode='doodle';g.drawingGame=true;setup(g);g.s={paths:[],stroke:[],input:'draw',taps:[]};const original=g.prompt;g.feedback='Follow the numbered start dots. Every stroke is checked for shape and position.';g.hint='Draw between the dots in order. Follow the requested measurement or construction. Tap points is an alternative to freehand drawing.';g.draw=()=>{const next=g.q.paths[g.s.paths.length];return svg(g.background()+g.s.paths.map(p=>path(p,C[2])).join('')+(next?next.map((p,i)=>{const closed=U.distance(next[0],next.at(-1))<1;if(closed&&i===next.length-1)return '';const index=closed&&i===0&&g.s.taps.length===next.length-1?next.length-1:i;return hit('Point '+(index+1),'point',index,dot(...p,23,'transparent')+dot(...p,7,i===0?C[0]:'#fff',`stroke="#8e77b1" stroke-width="3"`)+text(p[0]+16,p[1]-11,closed&&i===0?'1 ↩':i+1,14))}).join(''):'')+(next&&g.level===0?path(next,'#967cad66',2,'4 7'):'')+path(g.s.stroke,C[1],5)+path(g.s.taps,C[1],5)+text(90,25,`${g.s.paths.length}/${g.q.paths.length} strokes`,16),original)};g.controls=()=>btn('↶ Undo','undo','',true)+btn(g.s.input==='draw'?'Tap points':'Use pen','input','',true)+btn('Check drawing','check');function submit(points){const target=g.q.paths[g.s.paths.length];if(!target)return;if(matches(points,target)){g.s.paths.push(target);g.s.stroke=[];g.s.taps=[];g.scene();if(g.s.paths.length===g.q.paths.length)g.say('All strokes placed. Check your finished drawing.');else g.say('That stroke fits. Draw the next marked part.')}else{g.s.stroke=[];g.s.taps=[];g.say('Try again: begin at point 1, cover the marked route, and end at the last point.')}}g.pointer=(x,y,phase)=>{if(g.s.input!=='draw'||g.s.paths.length>=g.q.paths.length)return;if(phase==='start')g.s.stroke=[[x,y]];if(phase==='move'&&g.s.stroke.length)g.s.stroke.push([x,y]);if(phase==='end'&&g.s.stroke.length){g.s.stroke.push([x,y]);submit(g.s.stroke)}if(phase==='cancel')g.s.stroke=[];g.scene()};g.pointerOnTargets=true;g.action=(k,v)=>{if(k==='input'){g.s.input=g.s.input==='draw'?'tap':'draw';g.s.stroke=[];g.s.taps=[];g.refresh()}if(k==='undo'){g.s.paths.pop();g.s.stroke=[];g.s.taps=[];g.scene()}if(k==='point'&&g.s.input==='tap'){const p=g.q.paths[g.s.paths.length];if(!p)return;const i=+v;if(i!==g.s.taps.length){g.say('Tap the numbered points in order, starting with 1.');return}g.s.taps.push(p[i]);if(g.s.taps.length===p.length)submit(g.s.taps);g.scene()}if(k==='check'){if(g.s.paths.length===g.q.paths.length)g.success('Your drawing matches the mathematical construction. Beautifully done!');else g.say(`Complete all ${g.q.paths.length} strokes before checking.`)}}}});
S.drawingMatches=matches;
})();
